---
title: "My Solutions to Old Algebra Quals"
author: "Jacob S Townson"
date: "May-July 2017"
output:
  html_document:
    fig_height: 4
    fig_width: 5
  pdf_document:
    fig_height: 4
    fig_width: 5
  word_document:
    fig_height: 4
    fig_width: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Prelude
This document is written in reference to qualifying exams given at the University of Louisville in past years. These solutions are not given from the University, but of my work alone as a way to study for my own qualifying exam. If any tips or recommendations come up and you feel you should share, feel free to raise an issue on GitHub where I have this document saved and open to the public [here](https://github.com/obewanjacobi/gradwork/tree/master/Classes/Old%20Qualifying%20Exams/My%20Solutions). To see the qualifying exams for yourself, [visit this link](http://www.math.louisville.edu/GraduateFAQ/qualifiers/QualifierStudyGuides/). Thank you.

Jacob Townson


## January 2016

### Let $(G,·)$ be a group and $Z = Z(G)$ its center. Suppose that the group $G/Z$ is cyclic. Show that $G$ is Abelian.
#### My Solution:

Let $G/Z$ be cyclic with generator $xZ$. Every element in $G/Z$ can be written as $x^k Z$ where $k \in \mathbb{Z}$ and $z \in Z$. We want to show first for all $g \in G$ that $g$ can be written in the form $x^k z$ for some $k \in \mathbb{Z}$ and $z \in Z$. We know that $G/Z$ is cyclic, so there exists some $g \in G$ such that $gZ = (xZ)^m = x^m Z$ for some $m$. Well, this is true iff $(x^m)^{-1} g \in Z$. So there exists a $z \in Z$ such that $(x^m)^{-1} g = z \implies g = x^m z$.

Now let $g,h \in G$. Then

$$g=x^a z$$ and $$h = x^b w$$ for $a,b \in \mathbb{Z}$ and $z,w \in Z$. 

Thus 
$$gh = x^a z x^b w = x^{a+b} zw = x^{b+a} wz = x^b w x^a z = hg$$
because $z,w \in Z$. THus $gh = hg$ which implies that G is Abelian. QED



### Prove that every prime ideal is maximal in a PID.
#### My Solution:

Let $P$ be a prime ideal in the PID $R$. So $ab \in P$ iff $a$ or $b \in P$. But $R$ is a PID, so $P =(a)$ where $a \in R$. So we want to show $P$ is maximal using this information, ie. if $I$ is an ideal that contains $P$, then $I=P$ or $I=R$. So let $I$ be an ideal containing $P$ such that $P \subset I \subset R$. Let $I =(b)$ where $b \in R$ because $R$ is a PID. Now, $a \in (a) \subset (b)$ which implies that there exists $c \in R$ such that $a =bc$. Since $a = bc \in P$, we know either $b$ or $c$ is in $P$ because it's prime. 

If $b \in P$, then $I = (b) \subset P$ which implies $P=I$. On the other hand, if $c \in P =(a)$, then there exists $d \in R$ such that $c = ad$. So $$a =bc =bad$$

Because $R$ is an integral domain (because it'e a PID), we can reduce the above formula to $$1 = bd$$

Thus $b$ is a unit which implies that $I = (b) = R$.

Thus either $P=I$ or $I=R$ for all $I$ containing $P$, so $P$ is maximal in $R$.  QED



### Let $R$ be a commutative ring with $1$. For any two ideals $I$ and $J$ of $R$, let $IJ$ be the ideal generated by all products $xy$ where $x \in I$ and $y\in J$. Suppose $I+J = R$, prove that $IJ = I \cap J$.

#### My Solution:

We will prove this using set containment.

Because $I$ and $J$ are ideals in $R$, for all $x_i \in I$ and all $y_i \in J$, $x_i y_i \in I$ and $x_i y_i \in J$. Moreover, $\sum_{i=1}^{n} x_i y_i \in I$ and $\sum_{i=1}^{n} x_i y_i \in J$. Thus 
$$\sum_{i=1}^{n} x_i y_i \in IJ$$
which implies
$$\sum_{i=1}^{n} x_i y_i \in I \cap J$$
Thus $IJ \subset I \cap J$

Now we just need to show that $IJ \supset I \cap J$. To do this we will use the fact that $I+J=R$. Let $a \in I \cap J$. We know $1 \in R = I + J$. So $1 = i + j$ for some $i \in I$ and $j \in J$. Then since $R$ is commutative, 
$$a = a 1 = a (i+j) = ai + aj = ia + aj$$
However $ia \in IJ$ since $i \in I$ and $a \in J$ and $aj \in IJ$ for similar reasons as our previous argument. By the definition of $IJ$, this shows us $a \in IJ$. Thus $I \cap J \subset IJ$.

Thus we've proven that $IJ = I \cap J$ in this circumstance. QED



### Prove that any finite group is isomorphic to a subgroup of $A_n$ for some $n$, where $A_n$ is the alternating group on $n$ elements.
#### My Solution:

To do this proof, we will use the broader proof of Cayley's Theorem. This theorem states that if $G$ is a group of order $n < \infty$, then $G$ is isomorphic to a subgroup of $S_n$.

Let $S$ be the set of all elements of $G$. Now consider the action of $G$ on $S$,
$$G \times S \rightarrow S, a*b:=ab$$
This action defines a homomorphism $\gamma: G \rightarrow \mathrm{Perm}(S)$. It is fairly easy to see that this homomorphism is one-to-one and onto. Thus, it follows that $G$ is isomorphic to a subgroup of $\mathrm{Perm}(S)$. And finally, since $|S| = n$ we have that $\mathrm{Perm}(S) \cong S_n$ This tells us that $G \cong S_n$.

Thus we just need to show that $S_n \cong A_m$. Let $\Gamma : S_n \rightarrow A_{n+2}$ such that $\Gamma : \sigma \mapsto \sigma$ if $\sigma$ is even, or $\Gamma : \sigma \mapsto (n+1 \ n+2) \sigma$ if $\sigma$ is odd where $\sigma \in S_n$. We just need to show that $\Gamma$ is an isomorphism. Let $\sigma_1, \sigma_2 \in S_n$. If $\sigma_1, \sigma_2$ are even, then 
$$\Gamma (\sigma_1 \sigma_2) = \sigma_1 \sigma_2 = \Gamma (\sigma_1) \Gamma (\sigma_2)$$
If $\sigma_1, \sigma_2$ are both odd, then 
$$\Gamma (\sigma_1 \sigma_2) = \sigma_1 \sigma_2 = \Gamma (\sigma_1) \Gamma (\sigma_2)$$ This is true because $(n+1 \ n+2)^2$ is the identity permutation, and $\sigma_1 \sigma_2$ is even.
Finally WLOG let $\sigma_1$ be even and $\sigma_2$ be odd. Then
$$\Gamma(\sigma_1) \Gamma(\sigma_2) = \sigma_1 (n+1 \ n+2) \sigma_2 = (n+1 \ n+2) \sigma_1 \sigma_2 = \Gamma (\sigma_1 \sigma_2)$$
Thus $\Gamma$ is a homomorphism. It is also obvious that for all $\sigma$ there exists a $\Gamma(\sigma)$, so we know that $\Gamma$ is onto. And finally, it is obvious that if $\Gamma(\sigma_1) = \Gamma(\sigma_2)$, then $\sigma_1 = \sigma_2$. Thus $\Gamma$ is an isomorphism.

Using this fact and Cayley's Theorem, we then know that $G \cong S_n \cong A_{n+2}$ which proves that any finite group is isomorphic to a subgroup of $A_n$. QED



### Determine if the field extension $\mathbb{Q}(\sqrt[3]{2})/\mathbb{Q}$ is Galois.
#### My Solution:

In order to prove that $\mathbb{Q}(\sqrt[3]{2})/\mathbb{Q}$ is or is not Galois, we will use the fundamental theorem of Galois theory. Thus, we know if we prove that $\mathbb{Q}(\sqrt[3]{2})$ is a splitting field over some function $t(x)$ in $\mathbb{Q}$, then we know the extension is Galois. Consider the polynomial $t(x) = x^3 - 2$. This polynomial has no roots in $\mathbb{Q}$, but has root $\sqrt[3]{2} \in \mathbb{Q}(\sqrt[3]{2})$. Unfortunately, this is not enough for us to factor $t(x)$ into linear factors, as we will need some $\omega \in \mathbb{Q}$ to further factor the polynomial. Thus we know that $\mathbb{Q}(\sqrt[3]{2})$ is not a splitting field, and thus it must not be Galois by the fundamental theorem of Galois theory. QED



### Let $G$ be a group. Consider the commutator subgroup $[G,G]$ of $G$, the subgroup generated by all commutators, $aba^{-1} b^{-1}$ where $a,b \in G$. It is known that $[G,G]$ is a normal subgroup of $G$. Prove that a) $G/[G,G]$ is Abelian, and b) if $K \unlhd G$ such that $G/K$ is Abelian, then $[G,G] \unlhd K$.
#### My Solution:
a)
First off, to save time let $[G,G] =C$. So we want to show that for all $aC, bC \in G/C$ that 
$$abC = aCbC = bCaC = baC$$
Well, $aba^{-1} b^{-1}$ generates $C$. So, $C = aba^{-1} b^{-1}C$, which implies that $abC = baC$ through cancellation. Thus $G/C$ is Abelian. QED

b)
First we must show that $C \subseteq K$. Well, because $G/K$ is Abelian, we know that $abK = baK$ which implies that $a{-1}b^{-1}abK = K$. Thus $C \subseteq K$. Then, because $C$ is a subgroup of $G$, we know that $G$ must then be a subgroup of $K$ since $K$ is a group containing $C$. Lastly, we must show that $C \unlhd K$. Well, because $C \unlhd G$, $K \unlhd G$, and $C \leq K$, we can easily see that these things imply that $C$ is normal in $K$. Thus $C \unlhd K$. QED



### Let $R$ be a commutative ring. Prove that the following are equivalent: (a) $R$ is a field; and (b) $R \neq \{0\}$ and the only ideals of $R$ are $\{0\}$ and $R$.
#### My Solution:
($a \implies b$)

Suppose $I$ is a nonzero ideal of a field $R$. So $I$ contains some $0 \neq a$. Then since $R$ is a field, $a^{-1}$ exists and $1 = a^{-1} a \in I$, so $I$ contains $1$ and hence $I = R$. The trivial ideal also exists, and is trivial to show. 

($b \implies a$)

Let $R$ have only two ideals, the trivial and $R$. Suppose $R$ is not a field. Then some nonzero element $a$ does not have an inverse. If we set $aR = \{ar | r \in R \}$. This is a proper nonzero ideal, which gives us a contradiction to our original statement. Thus $R$ must be a field for $R$ to only contain 2 ideals, the trivial and $R$ itself. 

Thus the two statements are equivalent, $R$ is a field and $R$ contains only two ideals, those being the trivial ideal and $R$ itself. QED



### (a) Find the degree $[F: \mathbb{Q}]$ of the extension $F = \mathbb{Q}(i, \sqrt{3})$ over $\mathbb{Q}$. Find a basis of the vector space $F$ over $\mathbb{Q}$. (b) Find a primitive element of the extension $F$ of $\mathbb{Q}$.
#### My Solution:
(a) Here we can use what I like to call the *double extension lemma* to find the degree of the extension. So we know that $[F: \mathbb{Q}] = [\mathbb{Q}(i, \sqrt{3}): \mathbb{Q}(\sqrt{3})][\mathbb{Q}(\sqrt{3}): \mathbb{Q}]$. Thus because the minimum polynomials for the extensions are $x^2 +1$ and $x^2 - 3$ respectively, we know that the degree of the extension is $2*2=4$. A basis for this extension is $[1, i, \sqrt{3} , i \sqrt{3}]$. QED

(b) The primitive element of this extension is $i+\sqrt{3}$ as this element makes the simple extension $\mathbb{Q}(i+\sqrt{3}) = F$. This can be shown through the following containment arguments:

First let $\mathbb{Q}(i+\sqrt{3}) = K$. It is obvious that $K \subset F$, so we're good there. Thus we just need to show that $F \subset K$. So we need to show that $i, \sqrt{3} \in K$. Well, let $a = i+\sqrt{3}$. We know $a, a^2 \in K$. $a^2 = -1 +2i \sqrt{3} +3$, which implies that $2i \sqrt{3} \in K$. Then we can look at $2i \sqrt{3} * (i + \sqrt{3}) \in K$ which implies that $3i - \sqrt{3} \in K$, which implies that $(3i-\sqrt{3})+(i +\sqrt{3}) \in K \implies i \in K$. Thus $i+ \sqrt{3} -i \in K \implies \sqrt{3} \in K$. So finally we have proven both directions of containment, implying that the primitive element $i+\sqrt{3}$ makes $F$ into a simple extension of $\mathbb{Q}$ which we call $K$. QED
























## August 2015

### Prove that a group of order $300$ cannot be simple.
#### My Solution:
To begin, we must understand what it means for a group to be simple. A simple group is a group of whose only normal subgroups are the trivial group and the entire group itself. Thus we want to show there are no proper normal subgroups other than the trivial group.

To do this we will use Sylow's Theorem and a proof by contradiction.

Let $G$ be a group of order $300$ such that $G$ is simple. Well, $300 = 3 \times 2^2 \times 5^2$. We will denote the number of Sylow-p subgroups as $n_p$. Notice then that $n_5 | 12$ and $n_5 = 1 + 5k$. This implies that $n_5 = 1$ or $6$. However, because $G$ is simple there cannot only be one Sylow-5 subgroup, otherwise we would have a proper nontrivial normal subgroup. Thus $n_5 = 6$. Because of this, and because $G$ is simple, we can say that $G$ embeds into $S_6$ if we let $G$ act on the Sylow-5 subgroups by conjugation. But then by Lagrange's Theorem, $300$ should divide $6!$, which it does not. Thus we have a contradiction, which implies that $G$ is not simple, thus a group of order $300$ cannot be simple. QED



### Let $F = \mathbb{Q}(i,\sqrt{3})$ where $i$ is imaginary. Find the degree of the extension $[F:\mathbb{Q}]$ and a basis of $F$ over $\mathbb{Q}$. Justify.
#### My Solution:
(a) Here we can use what I like to call the *double extension lemma* to find the degree of the extension. So we know that $[F: \mathbb{Q}] = [\mathbb{Q}(i, \sqrt{3}): \mathbb{Q}(\sqrt{3})][\mathbb{Q}(\sqrt{3}): \mathbb{Q}]$. Thus because the minimum polynomials for the extensions are $x^2 +1$ and $x^2 - 3$ respectively, we know that the degree of the extension is $2*2=4$. A basis for this extension is $[1, i, \sqrt{3} , i \sqrt{3}]$. QED

(b) The primitive element of this extension is $i+\sqrt{3}$ as this element makes the simple extension $\mathbb{Q}(i+\sqrt{3}) = F$. This can be shown through the following containment arguments:

First let $\mathbb{Q}(i+\sqrt{3}) = K$. It is obvious that $K \subset F$, so we're good there. Thus we just need to show that $F \subset K$. So we need to show that $i, \sqrt{3} \in K$. Well, let $a = i+\sqrt{3}$. We know $a, a^2 \in K$. $a^2 = -1 +2i \sqrt{3} +3$, which implies that $2i \sqrt{3} \in K$. Then we can look at $2i \sqrt{3} * (i + \sqrt{3}) \in K$ which implies that $3i - \sqrt{3} \in K$, which implies that $(3i-\sqrt{3})+(i +\sqrt{3}) \in K \implies i \in K$. Thus $i+ \sqrt{3} -i \in K \implies \sqrt{3} \in K$. So finally we have proven both directions of containment, implying that the primitive element $i+\sqrt{3}$ makes $F$ into a simple extension of $\mathbb{Q}$ which we call $K$. QED



### Let $A$ and $B$ be ideals of a ring $R$ with $B \subseteq A$. Show that $A/B = \{ a+B|a \in A \}$ is an ideal of the ring $R/B$.
#### My Solution:
Recall for this problem the definition of an ideal for rings. $I$ is an ideal of the ring $R$ if for all $x \in R$ and $y \in I$, then $xy, yx \in I$. 

We will use this definition to show $A/B$ is an ideal of $R/B$. Notice $R/B = \{ r + B|r \in R \}$. So let's consider two elements, $r+B \in R/B$ and $a + B \in A/B$ such that $r \in R$ and $a \in A$. We want to show that $(r+B)(a+B) \in A/B$ and $(a+B)(r+B) \in A/B$. Well, 
$$(r+B)(a+B) = ra+aB+rB+B = ra+B$$ 
because $B$ is an ideal of $R$. But $A$ is also an ideal of $R$ so $ra \in A$, which implies that $ra + B \in A/B$. Looking at the other direction, we find that
$$(a+B)(r+B) = ar+aB+rB+B = ar+B$$
and for similar reasons, we then know that $ar+B \in A/B$. Thus $A/B$ is an ideal of $R/B$. QED

- Note: This statement also follows directly from the third isomorphism threorem for rings.



### Let $A$ and $B$ be ideals of a ring $R$ with $B \subseteq A$. Show that the map $f: R/B \rightarrow R/A$ given by $f(x+B) = x+A$ for every $x \in R$, is well-defined, onto, and a homomorphism.
#### My Solution:
We will need to separate this problem into three parts.

- First we must prove that $f$ is well-defined. So we want to show that if $x=y \in R$, then $f(x+B)=f(y+B)$. Well, if $x=y$, then 
$$f(x+B) = x+A = y+A = f(y+B)$$
Thus $f$ is well-defined by definition.

- Next we will show that $f$ is an onto function. So we need to show that for all $x \in R$, and $x+B \in R/B$, then $f(x+B) \in R/A$. Well, by definition this is obvious, because for all $x \in R$ and $x+B \in R/B$, $f(x+B) = x+A \in R/A$. Thus the function must be onto.

- Finally we must show that $f$ is a homomorphism. First note that $f(B)=A$ by definition, so the identity maps to the respective identity. Now we must prove that addition and multiplication are preserved. First, let's look at $f(x+B+y+B)$ where $x,y \in R$. So,
$$f(x+B+y+B) = f(x+y+b) = x+y+A = (x+A) + (y+A) = f(x+B)+f(y+B)$$
Thus addition is preserved. So now we must only prove that multiplication is preserved. Assume a similar situation as above, but let's look at $f((x+B)(y+B))$. Well,
$$f((x+B)(y+B)) = f(xy+xB+yB+B) = f(xy+B)$$
because $B$ is an ideal. Now we can further this manipulation using that $A$ is an ideal to see that
$$f(xy+B)=xy+A=xy+xA+yA+A=(x+A)(y+A)=f(x+B)f(y+B)$$
Thus because identities, addition, and multiplication are preserved, we know then that $f$ is a homomorphism.

Thus $f$ is a well-defined, onto, homomorphism. QED



### Let $A$ and $B$ be ideals of a ring $R$ with $B \subseteq A$. Show that $(R/B)/(A/B)$ is isomorphic to $R/A$.
#### My Solution:
This statement is easily shown by the first isomorphism theorem for rings, where the kernel of $f$ is simply $A/B$. More formal proof is given later in the document.



### Determine the splitting field and its degree over $\mathbb{Q}$ for the polynomial $t(x) = x^6 - 4$. Justify.
#### My Solution:
First note that $t(x) = x^6 -4 = (x^3 - 2)(x^3 + 2)$. The roots of this polynomial are $\sqrt[3]{2}, -\sqrt[3]{2}, \omega_1\sqrt[3]{2},\omega_2\sqrt[3]{2},\alpha_1\sqrt[3]{2},\alpha_2\sqrt[3]{2}$ where $\omega_1, \omega_2, \alpha_1, \alpha_2 \in \mathbb{C}$. We can then see that the splitting field of $t(x)$ over $\mathbb{Q}$ is $\mathbb{Q}(\sqrt[3]{2},i)$. This is the splitting field because in this extension $t(x)$ can be factored into linear factors. QED



### A ring $R$ (not necessarily commutative) with identity $1_R \neq 0$ in which every nonzero element is a unit is called a *division ring* . Prove that a ring $R$ with identity $1_R$ is a division ring iff $R$ has no proper left ideal.
#### My Solution:
First, recall if $I \subset R$, $I$ is a left ideal if for all $r \in R$ and $a \in I$, $ra \in I$.

Assume $R$ has no proper left ideal, thus the only left ideals are the trivial and the entire ring. So if $s \in R$ is nonzero and $R$ has no proper left ideals, then we can define $I := \{rs|r \in R\} =R$ and there exists $r \in R$ such that $rs = 1_R$. Also note 
$$(rs)r=r(sr)=r \implies r(1_R -sr)=0 \implies sr =1_R$$
Because $rs = 1_R = sr$, $R$ must be a division ring.

Now we must prove the other direction. Assume $R$ is a division ring and $I \neq \{0\}$ is a left ideal of $R$. Then for all $s \in I$, 
$$1_R = s^{-1}s \in I \implies I=R$$
Thus $R$ has no proper left ideals. QED.




### Let $G$ be an arbitrary group. For any two subgroups $H$ and $K$ of $G$, define $HK = \{ hk | h \in H, k \in K\}$. Assume $H \unlhd G$ and $K \leq G$. (a) Prove that $HK \leq G$. (b) Prove that $H \unlhd HK$ and $(H \cap K) \unlhd K$. (c) Prove that $\frac{HK}{H} \cong \frac{K}{H \cap K}$.
#### My Solution:
**Note: This is the proof of the 2nd Isomorphism Theorem for Groups**

(a) Recall that $HK$ can only be a subgroup if $HK = KH$. Thus if $H \unlhd G$, and we let $h \in H$ and $k \in K$, by assumption $khk^{-1} \in H$. Thus
$$kh = (khk^{-1})k \in HK$$ 
This proves that $KH \subseteq HK$. Similarly, $hk = k(k^{-1}hk) \in KH$ which proves the reverse containment. Thus $HK \leq G$. QED

(b) Since $K$ normalizes $H$ and $H$ normalizes itself trivially, this implies that $HK$ normalizes $H$. Thus $H \unlhd HK$. Since $H \unlhd HK$, the quotient group $\frac{HK}{H}$ is well defined. Define the map $\Gamma : K \rightarrow \frac{HK}{H}$ by $\Gamma (k) = kH$. Since the group operation in $\frac{HK}{H}$ is well defined, it's easy to see that $\Gamma$ is a homomorphism:
$$\Gamma(k_1 k_2) = (k_1 k_2)H = k_1 H *k_2 H = \Gamma(k_1) \Gamma(k_2)$$
Alternatively, the map $\Gamma$ is just the restriction to the subgroup $K$ of the natural progression homomorphism $\pi : HK \rightarrow \frac{HK}{H}$, so it's also a homomorphism. It is clear then from the definition of $HK$ that $\Gamma$ is onto. The identity of $\frac{HK}{H}$ is simply $H$, so the kernel of $\Gamma$ consists of the elements $k \in K$ with $kH = H$, or where $k \in H$. Thus $\mathrm{ker}\Gamma = H \cap K$. So by the first isomorphism theorem, $H \cap K \unlhd K$. QED

(c) Following the proof of part (b), by the First Isomorphism Theorem, $\frac{HK}{H} \cong \frac{K}{H \cap K}$ QED



### Let $F$ be a field and let $f(x) \in F[x]$. (a) What is the definition of the *splitting field* of the polynomial $f(x)$ over the field $F$. (b) Let $a \in F$. Show that $f(x)$ and $f(x+a)$ have the same splitting field over $F$.
#### My Solution:
(a)
The extension field $K$ of $F$ is a splitting field for the polynomial $f(x) \in F[x]$ if $f(x)$ factors completely into linear factors in $K[x]$ and $f(x)$ does not factor completely into linear factors over any proper subfield of $K$ containing $F$.

(b)
Let $f(x) = c_1x^n+c_{n-1}x^{n-1}+...+c_1x+c_0$. Let $K$ be the splitting field of $f(x)$ over $F$. And finally, this all means that $f(x+a) = c_1(x+a)^n+c_{n-1}(x+a)^{n-1}+...+c_1(x+a)+c_0$. Since $K$ is the splitting field of $f(x)$ over $F$, we then know that $f(x)$ has roots $r_1,r_2,...,r_n \in K$. Also note that some of these $r_i$ values could be duplicates or even zeroes. So by definition, in $K$, $f(x) = (x-r_1)(x-r_2)...(x-r_n)$. This means that in $K$, $f(x+a) = (x+a-r_1)(x+a-r_2)...(x+a-r_n)$. From here it is easy to see that the roots of $f(x+a)$ are simply $r_1-a,r_2-a,...,r_n-a$. All of these values are in $K$ as well because for all $i$, $r_i \in K$ and $a \in F \subset K$. So because we can factor $f(x+a)$ into linear factors in $K$, $K$ must also be the splitting field of $f(x+a)$. Note, the situation in which we switch assumptions such that $K$ is the splitting field over $f(x+a)$ to prove that $K$ must also be the splitting field of $f(x)$ over $F$ is similar, so we leave this out. QED

















## January 2015

### If $N$ is a normal subgroup of $G$ and $H$ is any subgroup of $G$, prove that $NH := \{nh|n \in N, h \in H\}$ is a subgroup of $G$.
#### My Solution:
Let $H \leq G$ and $N$ be a normal subgroup of $G$. Let $NH$ be defined as above. So we want to show for all $nh \in NH$, $(nh)^{-1} \in NH$. Well, $(nh)^{-1}=h^{-1}n^{-1}$. First note because $N$ is a normal subgroup of $G$ and $H \leq G$, $n^{-1} \in N$ and $h^{-1} \in H$. Also note because $N$ is normal in $G$, for all $g \in G$, $gN = Ng$, ie. for all $n \in N$, $gn = ng$. Thus in $NH$, 
$$nh = hn \implies (nh)^{-1} = h^{-1}n^{-1} = n^{-1}h^{-1} \in NH$$
Thus $NH$ is a subgroup of $G$. QED



### Show that a group of order $56$ is not simple
#### My Solution:
Let $G$ be a group of order $56 = 2^3 * 7$. We will denote the number of Sylow-$p$ subgroups by $n_p$. So $n_2 = 2k + 1$ where $k \in \mathbb{Z^+}$ and $n_2 | 7$. Also $n_7 = 7j+1$ where $j \in \mathbb{Z^+}$ and $n_7 | 2^3 = 8$. So $n_2 \in \{1,7\}$ and $n_7 \in \{1,8\}$.

If either $n_7$ or $n_2$ are $1$, then we're done as this means that there exists a normal proper nontrivial Sylow-$p$ subgroup in our group $G$. Consider $n_7 = 8$. Because $7$ is prime and the subgroups are cyclic, and because we know the subgroups intersect trivially, $n_7 = 8 \implies$ there exists $8*6 = 48$ non identity elements in all of the Sylow $7$-subgroups. Notice, $56=48+8$. But if $n_2 = 7$, then there are $8$ distinct elements in each of the Sylow-$2$ subgroups. But we run into a problem, because $56=48+8$, so then there must be only 1 Sylow-$2$ subgroup in order to have $56$ elements. Thus either $n_2 =1$ or $n_7 = 1$, thus $G$ could not be simple as it has a normal proper nontrivial subgroup. QED



### A ring $R$ is *Boolean* if every element is idempotent, that is $a^2=a$ for all $a \in R$. Prove that every Boolean ring is commutative.
#### My Solution:
Recall that a ring is commutative if the multiplication operation in the ring is commutative. Thus we want to show that for every Boolean ring, if $a,b \in R$ then $ab = ba$. 

To begin this problem, consider $a+b = (a+b)^2$. Well,
$$(a+b)^2 = (a+b)(a+b)=a(a+b)+b(a+b)$$
$$ = a^2 +ab+ba+b^2=a+ab+ba+b$$
When cancelling $a$ and $b$ from both sides, we find that $0 = ab+ba \implies ab = -ba$, but because $R$ is Boolean, we can easily see that $-c = c$ for all $c \in R$. Thus we have proven that all Boolean rings are indeed commutative. QED.



### Show that every prime element in an integral domain is irreducible.
#### My Solution:
Recall an integral domain is a commutative ring with no zero divisors. Also an element in an integral domain is irreducible if it is not equal to the product of two non-units. Also recall that if $R$ is our integral domain, $u \in R$ is a unit if for some $v \in R$, $uv = e$ where $e$ is the identity in $R$. Lastly, recall that $p \in R$ is prime if $p|ab \implies p|a$ or $p|b$. 

Let $p \in R$ be a prime element where $R$ is an integral domain. Assume $p = ab$ where $a,b \in R$. Obviously $p|ab$, so because $p$ is prime, $p|a$ or $p|b$. WLOG, assume $p|a$ such that $px = a$ for some $x \in R$. If $1$ is the identity of $R$, then 
$$1*a=a=px=(ab)x=a(bx)$$
Because $R$ is an integral domain, $a$ can be cancelled out implying that $1=bx$, thus $b$ is a unit. This proves that $p$ is also irreducible in an integral domain. QED.



### Prove or provide a counterexample: Galois extensions of Galois extensions are Galois extensions. That is, if $K/F$ is Galois and $L/K$ is Galois, then $L/F$ is Galois. 
#### My Solution:
This statement is false! Consider $L = \mathbb{Q}(\sqrt[4]{2})$, $K = \mathbb{Q}(\sqrt{2})$, and $F = \mathbb{Q}$. In this case, $K/F$ is Galois because $K$ is a splitting field over $F$, and it is similar for $L/K$. However, $L/F$ is not Galois, as $L$ does not make a splitting field over $F$. This can be seen from the polynomial $f(x)=x^4-2 \in \mathbb{Q}[x]$. Not all of the roots of $f(x)$ are contained in $L$, as $L$ does not contain any imaginary numbers. QED



### Let $E$ be a finite extension of field $F$. Prove that $E$ is algebraic over $F$.
#### My Solution:
Assume $E/F$ is finite. Let $\beta \in E/F$. We have then that $F \subseteq F(\beta) \subseteq E$. We know
$$[E:F] =n \in \mathbb{N} \implies [F(\beta):F] \leq n$$
Consider $\{1,\beta,\beta ^2, ..., \beta ^n\} \subseteq E$. So there exists $c_0, ..., c_n \in F$ such that $c_0+ c_1 \beta + ... + c_n \beta ^n =0$, where at least one $c_i \neq 0$. Let $v(x) = c_n x^n +...+c_0$, so $v(\beta) =0$. Thus if $E/F$ is finite, then $E$ is algebraic over $F$. QED



### Find the degree of the extension $[F: \mathbb{Q}]$, where $F = \mathbb{Q}(\sqrt{-1},\sqrt{3})$. Is this a simple extension? Why or why not?
#### My Solution:
(a) Here we can use what I like to call the *double extension lemma* to find the degree of the extension. So we know that $[F: \mathbb{Q}] = [\mathbb{Q}(i, \sqrt{3}): \mathbb{Q}(\sqrt{3})][\mathbb{Q}(\sqrt{3}): \mathbb{Q}]$. Thus because the minimum polynomials for the extensions are $x^2 +1$ and $x^2 - 3$ respectively, we know that the degree of the extension is $2*2=4$. A basis for this extension is $[1, i, \sqrt{3} , i \sqrt{3}]$. QED

(b) The primitive element of this extension is $i+\sqrt{3}$ as this element makes the simple extension $\mathbb{Q}(i+\sqrt{3}) = F$. This can be shown through the following containment arguments:

First let $\mathbb{Q}(i+\sqrt{3}) = K$. It is obvious that $K \subset F$, so we're good there. Thus we just need to show that $F \subset K$. So we need to show that $i, \sqrt{3} \in K$. Well, let $a = i+\sqrt{3}$. We know $a, a^2 \in K$. $a^2 = -1 +2i \sqrt{3} +3$, which implies that $2i \sqrt{3} \in K$. Then we can look at $2i \sqrt{3} * (i + \sqrt{3}) \in K$ which implies that $3i - \sqrt{3} \in K$, which implies that $(3i-\sqrt{3})+(i +\sqrt{3}) \in K \implies i \in K$. Thus $i+ \sqrt{3} -i \in K \implies \sqrt{3} \in K$. So finally we have proven both directions of containment, implying that the primitive element $i+\sqrt{3}$ makes $F$ into a simple extension of $\mathbb{Q}$ which we call $K$. QED



### Let $G$ be an arbitrary group with a center $Z(G)$. Prove that the inner automorphism group $Inn(G)$ is isomorphic to $G/Z(G)$. (Recall by definition $Inn(G)$ is the group of all automorphisms $\phi_h$ of the form $\phi_h(g)=h^{-1}gh$, for all $g \in G$.)
#### My Solution:
Consider the map $\theta : G \rightarrow \mathrm{Aut}(G)$ defined as $\theta(g) = \gamma_g$, where $\gamma_g$ is the automorphism of $G$ defined by $\gamma_g(h) = ghg^{-1}$. 

**Lemma 1**: $\theta$ is a homomorphism.

*Proof*: We have $\theta(g_1 g_2) = \gamma_{g_{1}g_{2}}$, and
$$\gamma_{g_{1}g_{2}}(h)=(g_1 g_2)h(g_1 g_2)^{-1} =g_1(g_2 h g_2 ^{-1})g_1 ^{-1} = \gamma_{g_1}(\gamma_{g_2}(h)).$$

**Lemma 2**: $\mathrm{ker}(\theta) = Z(G)$.

*Proof*: We have 
$$ker(\theta) = \{g: \theta (g) = e \} = \{g : \gamma_g = e\}$$
$$= \{g: \gamma_g (h) = h\} = \{g: gh = hg\} = Z(G)$$

Finally, by the first isomorphism theorem, we have $G/ker(\theta) = G/Z(G) \cong im (\theta) = \mathrm{Inn}(G)$, as desired. QED.



### Let $G$ be a finite group and let $H \unlhd G$. Prove that for any Sylow $p$-subgroup $P$ of $G$, $P \cap H$ is a Sylow $p$-subgroup of $H$.
#### My Solution:
Since $P \cap H$ is a $p$-group, as it is contained $P$, we only need to show that $P \cap H$ has maximal $p$-power order in $N$. By the Sylow Theorem, $P \cap H$ is contained in a conjugate of $P$, which we'll call $K$ such that $K \subset gPg^{-1}$. Thus $g^{-1}Kg \subset P$. Also $g^{-1}Kg \subset g^{-1}Hg = H$, so $g^{-1}Kg \subset P \cap H \subset K$. Since $|K| = |g^{-1}Kg|$, we get that $|P \cap H| = |K|$, so $P \cap H = K$ is a $p$-Sylow subgroup of $H$. QED



### Let $R$ be a commutative ring with unity and let $P \neq R$ be an ideal of $R$. Prove that the following are equivalent: (i) $P$ is prime, and (ii) For any ideals $I,J \in R$, if $IJ \subseteq P$ then $I \subseteq P$ or $J \subseteq P$.
#### My Solution:
(i) $\implies$ ii

Let $IJ \subseteq P$ and suppose WLOG that $J \nsubseteq P$. Then there is some $b \in J$ such that $b \notin P$. But then $aRb \subseteq P$ for all $a \in I$, so by (i), $a \in P$ for all $a \in I$.

(ii) $\implies$ i

Let $IJ \subseteq P$ so that $I \subseteq P$ or $J \subseteq P$. Then if we let $a \in I$ and $b \in J$, if $aRb \subseteq P$, then $RaRb \subseteq P$, so by (ii), $a \in P$ or $b \in P$ which implies by definition that $P$ is prime.



### Determine the Galois group of $f(x) = x^4 - 5x^2 +6$ over $\mathbb{Q}$. 
#### My Solution:
Recall that the Galois group of a separable polynomial $f(x) \in F[x]$ is defined to be the Galois group of the splitting field of $f(x)$ over $F$.

Well, $f(x) = x^4 - 5x^2 +6 = (x^2-2)(x^2-3)$. We cannot factor $f(x)$ any futher in $\mathbb{Q}$ but in $\mathbb{Q}(\sqrt{2}, \sqrt{3})$, $f(x)$ can be factored into linear factors. So the plitting field over $\mathbb{Q}$ is $\mathbb{Q}(\sqrt{2}, \sqrt{3})$. So the automorphisms in the Galois group map $\sqrt{2} \rightarrow -\sqrt{2}$, $\sqrt{3} \rightarrow -\sqrt{3}$, the identity map, and interchanging the $\sqrt{2}$ and $\sqrt{3}$. Thus the Galois group has order $4$ and is not cyclic, implying that the Galois group must be $\mathbb{Z}_2 \times \mathbb{Z}_2$. QED














## August 2014

### Let $H \leq G$. Prove that $N_G(H)/C_G(H)$ is isomorphic to a subgroup of $Aut(H)$. Recall the normalizer $N_G(H) = \{g \in G | gHg^{-1} = H\}$ and the centralizer $C_G(H) = \{g \in G | gh = hg, \forall h \in H\}$
#### My Solution:
For $g \in N_G(H)$, it is clear that $\sigma_g:h \rightarrow ghg^{-1}$ defines an automorphism of $H$. Define a map:
$$ \sigma : N_G(H) \rightarrow Aut(H)$$
where $g \rightarrow \sigma_g$. Since for all $a,b \in N_G(H), h \in H$, we have that $\sigma_a \sigma_b (h) = abhb^{-1} a^{-1} = \sigma_{ab}(h)$. Then $\sigma$ is a group homomorphism from $N_G(H)$ to $Aut(H)$. Note that
$$\mathrm{Ker}(\sigma) = \{g \in N_G(H) | ghg^{-1} = h, \forall h \in H\}$$
$$ = C_G(H) \cap N_G(H) = C_G(H)$$
From the first isomorphism theorem we then have that $N_G(H)/C_G(H)$ is isomorphic to a subgroup of $Aut(H)$. QED



### An integral domain $D$ is said to be **Artinian** if for any descending chain of ideals $$I_1 \supseteq I_2 \supseteq I_3 \supseteq ...$$ of $D$, there is an integer $n$ such that $I_i - I_n$ for all $i \geq n$. Prove that an integral domain $D$ is Artinian if and only if it is a field.
#### My Solution:
Assume $D$  is Artinian, and has a unit $1_D$ that is a multiplicative identity element. For any $0 \neq a \in D$, consider the principle ideal generated by $a^i$, $(a^i)$. Since $a^{n+1}d=a^n (ad)$ for any $d \in D$, we have that $(a^{n+1}) \subseteq (a^n)$. Thus we have our descending chain of ideals
$$(a) \supseteq (a^2) \supseteq ... \supseteq (a^n) \supseteq ...$$
which will stabilize because $D$ is Artinian. Thus for some positive integer $m$, $$(a^m)=(a^{m+1})$$
Then since $a^m = a^m 1_D \in (a^m)$, there exists $s \in D$ such that $a^{m+1} s = a^m$ or $a^m (1_D - a s)=0$.
Using the properties of an integral domain, this implies that $as=1_D$. Thus we have shown that every $0 \neq a \in D$ has a multiplicative inverse thus $D$ is also a field.

Assume $D$ is an integral domain and a field. Then $D$ has only two ideals, the trivial and $D$ itself. Thus every strictly descending chain of ideals is of finite length, implying that $D$ is Artinian. QED



### A *principal ideal ring* is a ring in which every ideal has a single generator. (a) Prove that an element of a principal ideal domain is prime iff it is irreducible. (b) Provide an example of a principal ideal ring containing an element which is prime but not irreducible.
#### My Solution:
(a)
Recall that a PID is also an integral domain. Also recall that an integral domain is a commutative ring with no zero divisors. Also an element in an integral domain is irreducible if it is not equal to the product of two non-units. Also recall that if $R$ is our integral domain, $u \in R$ is a unit if for some $v \in R$, $uv = e$ where $e$ is the identity in $R$. Lastly, recall that $p \in R$ is prime if $p|ab \implies p|a$ or $p|b$. 

Let $p \in R$ be a prime element where $R$ is an integral domain. Assume $p = ab$ where $a,b \in R$. Obviously $p|ab$, so because $p$ is prime, $p|a$ or $p|b$. WLOG, assume $p|a$ such that $px = a$ for some $x \in R$. If $1$ is the identity of $R$, then 
$$1*a=a=px=(ab)x=a(bx)$$
Because $R$ is an integral domain, $a$ can be cancelled out implying that $1=bx$, thus $b$ is a unit. This proves that $p$ is also irreducible in an integral domain. 

Now assume that $p$ is irrecucible. To complete the proof, we want to show that $p$ is prime. If $p$ is irreducible, then $(p)$ is maximal in the set of all proper principal ideals of $R$. Since $R$ is a principal ideal domain then every ideal is principal, so in fact $(p)$ is maximal in $R$ itself. Since $R$ is an integral domain (because it's a PID), then $R$ has an identity. So then $(p)$ must be prime which implies $p$ must then be prime. QED

(b)
In $\mathbb{Z}_6$ $2$ is prime but not irreducible because $2*4 = 2$ and neither $2$ nor $4$ are units.



### Prove that $G$ is a simple group if it's order is $56$. 
#### My Solution:
Let $G$ be a group of order $56 = 2^3 * 7$. We will denote the number of Sylow-$p$ subgroups by $n_p$. So $n_2 = 2k + 1$ where $k \in \mathbb{Z^+}$ and $n_2 | 7$. Also $n_7 = 7j+1$ where $j \in \mathbb{Z^+}$ and $n_7 | 2^3 = 8$. So $n_2 \in \{1,7\}$ and $n_7 \in \{1,8\}$.

If either $n_7$ or $n_2$ are $1$, then we're done as this means that there exists a normal proper nontrivial Sylow-$p$ subgroup in our group $G$. Consider $n_7 = 8$. Because $&$ is prime and the subgroups are cyclic, and because we know the subgroups intersect trivially, $n_7 = 8 \implies$ there exists $8*6 = 48$ non identity elements in all of the Sylow $7$-subgroups. Notice, $56=48+8$. But if $n_2 = 7$, then there are $8$ distinct elements in each of the Sylow-$2$ subgroups. But we run into a problem, because $56=48+8$, so then there must be only 1 Sylow-$2$ subgroup in order to have $56$ elements. Thus either $n_2 =1$ or $n_7 = 1$, thus $G$ could not be simple as it has a normal proper nontrivial subgroup. QED



### Let $E$ be a finite extension of the field $F$. Prove that $E$ is algebraic over $F$.
#### My Solution:
Assume $E/F$ is finite. Let $\beta \in E/F$. We have then that $F \subseteq F(\beta) \subseteq E$. We know
$$[E:F] =n \in \mathbb{N} \implies [F(\beta):F] \leq n$$
Consider $\{1,\beta,\beta ^2, ..., \beta ^n\} \subseteq E$. So there exists $c_0, ..., c_n \in F$ such that $c_0+ c_1 \beta + ... + c_n \beta ^n =0$, where at least one $c_i \neq 0$. Let $v(x) = c_n x^n +...+c_0$, so $v(\beta) =0$. Thus if $E/F$ is finite, then $E$ is algebraic over $F$. QED



### Let $a = \sqrt{1+\sqrt{2}}$ and put $E = \mathbb{Q}(a)$. (a) Find the minimal polynomial of $a$ over $\mathbb{Q}$. (b) Find $[E;\mathbb{Q}]$. (c) Identify the group $Gal(E/\mathbb{Q})$, the set of all automorphisms of $E$ which fix $\mathbb{Q}$.
#### My Solution:
(a)
We will denote the minimal polynomial here as $m(x)$. Consider $m(x) = x^4 - 2x^2 -1$. First we can see that $m(a)=0$. We can also see from Eisenstein's Criteria that $m(x)$ is irreducible in $\mathbb{Q}$. Thus $m(x)$ is indeed the minimal polynomial of $a$ over $\mathbb{Q}$. 

(b)
We know that $[E:\mathbb{Q}] = \mathrm{deg}(m(x))$. Thus $[E:\mathbb{Q}]=4$.

(c)
Well, $Gal(E/\mathbb{Q})$ fixes all $q \in \mathbb{Q}$, so to find the automorphisms we just need to observe the roots. Well, there are $4$ possible automorphism maps for the roots:
$$\sqrt{1+\sqrt{2}} \rightarrow \sqrt{1+\sqrt{2}}$$
$$\sqrt{1+\sqrt{2}} \rightarrow -\sqrt{1+\sqrt{2}}$$
$$\sqrt{1+\sqrt{2}} \rightarrow \sqrt{1-\sqrt{2}}$$
$$\sqrt{1+\sqrt{2}} \rightarrow -\sqrt{1-\sqrt{2}}$$
Notice first off that these automorphisms do not make a cyclic group, so our Galois group is not $\mathbb{Z}_4$, and our Galois group turns out to be $\mathbb{Z}_2 \times \mathbb{Z}_2$. QED











## January 2014
### Let $q(x) = x^4 +1$. (a) Show that $q(x)$ is irreducible over $\mathbb{Q}$. (b) Determine the four roots of $q(x)$. (c) Let $S$ be the splitting field of $q(x)$ over $\mathbb{Q}$. Determine $[S: \mathbb{Q}]$. Justify. (d) Determine the Galois group of $q(x)$ over $\mathbb{Q}$. Justify.
#### My Solution:
(a)
This is obviously irreducible by Eisenstein's Criteria. 

(b)
Let $\psi$ be the primitive $8^{th}$ root of unity. Then $\psi, \psi^2, \psi^3, \psi^4$ are the roots of $q(x)$.

(c)
Let $S = \mathbb{Q}(\psi)$. Since $q(x)$ is irreducible in $\mathbb{Q}$, and $q(x)$ can be reduced into linear factors in $\mathbb{Q}(\psi)$, $S$ must be the splitting field of $q(x)$ over $\mathbb{Q}$. Thus, with $q(x)$ as the minimal polynomial, $[S:\mathbb{Q}] = \mathrm{deg}(q(x))=4$.

(d)
We know by the fundamental theorem of Galois Theory that $|\mathrm{Gal}(S/\mathbb{Q})| = 4 = [S:\mathbb{Q}]$. Thus $\mathrm{Gal}(S/\mathbb{Q}) = \mathbb{Z}_4$ where $\psi$ maps to all possible powers of $\psi$. 



### Show that $A_8$ has no subgroup of index $7$.
#### My Solution:
Assume that $A_8$ does in fact have a subgroup of index $7$. We'll call this subgroup $H$. Then $[A_8:H] = 7$. Then there exists a group action of $A_8$ on the cosets of $H$ by conjugation. Define $f$ to be a homomorphism such that $f$ embeds $A_8$ into $S_7$. Thus by Lagrange's Theorem, $7!$ should divide the order of $A_8$, $8!/2$, which is not true. Thus we have a contradiction, so $A_8$ has no subgroup with index $7$. QED



### Suppose $G$ is a group acting on a set $X$. We define everything the user needs to know before answering the problem. (a) Suppose $a \in X$. Prove that $G_a \leq G$. (b) Explicitly define a bijection $\phi$ from $G/G_a$ to $O(a)$. You need to justify that $\phi$ is well-defined, and is indeed a bijection. (c) Let $G$ act on itself by conjugation. Suppose $p$ is a prime number and $G$ is a finite $p$-group, then $G$ has a non-trivial center.
#### Needed Definitions:
For $a \in X$, let $O(a) = \{g(a)| g\in G\}$. This is the *orbit* of $a$ under the action of $G$ on $X$. Also for $a \in X$, let $G_a = \{g \in G | g(a) = a\}$. This is the *stablilizer* of $a$ in $G$. Let $\mathbb{O} = \{O(a)|a \in X\}$ be the set of orbits, and let $G/G_a = \{hG_a | h \in G\}$ be the set of all left cosets of $G_a$ in $G$.

#### My Solution:
(a)
Let $a \in X$. We want to show that for all $g,h \in G_a$, $gh^{-1} \in G_a$. Well, let $g,h \in G_a$. Then
$$gh(a) = g(h(a)) = g(a) = a$$ 
by associativity, so $gh \in G_a$. Also note that $e \in G_a$ where $e$ is the identity element of $G$, so,
$$e(a) = a = h^{-1}h(a) = h^{-1}(a)$$
which implies that $h^{-1} \in G_a$. Thus from here we can tell that $gh^{-1} \in G_a$ which implies that $G_a \leq G$. QED

(b)
Define $\phi : G/G_a \rightarrow O(a)$. So for any $gG_a \in G/G_a$, $\phi(gG_a) = g(a)$ where if $h \in G_a$, $$h(a) = \phi(hG_a) = \phi(G_a) = a$$
To show that $\phi$ is well-defined, let $g = h \in G$. Then 
$$\phi(gG_a) = g(a) = h(a) = \phi(hG_a)$$
So $\phi$ is indeed well-defined.
In order to show $\phi$ is onto, notice that for all $g(a) \in O(a)$, there exists sone $gG_a \in G/G_a$ such that $\phi(gG_a) = g(a)$. Thus $\phi$ is indeed onto. Finally, to show that $\phi$ is one-to-one, let
$$\phi(gG_a) = g(a) = h(a) = \phi(hG_a)$$
Because $g(a) = h(a)$, we can easily see that either $g = h$ or $g,h \in G_a$, which implies that $gG_a = hG_a$. Thus $\phi$ is one-to-one. QED

(c)
The orbits are the conjugacy classes of $G$. $x$ belongs to an orbit of size $1$ iff $x \in Z(G)$ since $gxg^{-1} = x$ for all $g \in G$ iff $gx = xg$ for all $g \in G$ iff $x \in Z(G)$. By the orbit stabilizer theorem, an orbit size that is greater than $1$ must divide $|G|$ and therefore must be a positive power of $p$. If $Z(G) = \{1\}$, then we have one orbit of size $1$ with all other orbit sizes being defined as $0 \mathrm{mod}p$. Thus $|G| = 1 \mathrm{mod} p$, contradicting the assumption that $G$ is a non-trivial $p$-group. QED



### There are five nonisomorphic groups of order $12$. List them all and explain why none are isomorphic.
#### My Solution:
The groups are $D_{12}, \mathbb{Z}_{12}, A_4, \mathbb{Z}_6 \times \mathbb{Z}_2$, and the dicyclic group of order $12$. The dicyclic group is not isomorphic to any of these because it is not Abelian but cyclic. The group $\mathbb{Z}_{12}$ is not isomorphic to any of these because it is cyclic and Abelian. The group $A_4$ is not isomorphic to these because it is not Abelian, and has a normal Sylow-$2$ subgroup. The group $D_{12}$ is not isomorphic to any of these because it is not Abelian, and doesn't have any normal Sylow-$2$ subgroups. And finally $\mathbb{Z_6} \times \mathbb{Z_2}$ is not isomorphic to any of these because it is Abelian and has a normal Sylow-$2$ subgroup. QED



### Let $R$ be a commutative ring with identity. For any two ideals $I$ and $J$ if $R$, let $IJ$ be the ideal generated by all products of $xy$ where $x \in I$ and $y \in J$. (a) Suppose that $P$ is a prime ideal of $R$ and that $IJ \subseteq P$. Show that either $I \subseteq P$ or $J \subseteq P$. (b) Suppose $I+J = R$, show that $IJ = I \cap J$. 
#### My Solution:
(a)
Let $IJ \subseteq P$ where $P$ is prime. Suppose WLOG that $J \nsubseteq P$. Then there is some $b \in J$ such that $b \notin P$. But then $aRb \subseteq P$ for all $a \in I$, so because $P$ is prime, $a \in P$ for all $a \in I$.

(b)
We will prove this using set containment.

Because $I$ and $J$ are ideals in $R$, for all $x_i \in I$ and all $y_i \in J$, $x_i y_i \in I$ and $x_i y_i \in J$. Moreover, $\sum_{i=1}^{n} x_i y_i \in I$ and $\sum_{i=1}^{n} x_i y_i \in J$. Thus 
$$\sum_{i=1}^{n} x_i y_i \in IJ$$
which implies
$$\sum_{i=1}^{n} x_i y_i \in I \cap J$$
Thus $IJ \subset I \cap J$

Now we just need to show that $IJ \supset I \cap J$. To do this we will use the fact that $I+J=R$. Let $a \in I \cap J$. We know $1 \in R = I + J$. So $1 = i + j$ for some $i \in I$ and $j \in J$. Then since $R$ is commutative, 
$$a = a 1 = a (i+j) = ai + aj = ia + aj$$
However $ia \in IJ$ since $i \in I$ and $a \in J$ and $aj \in IJ$ for similar reasons as our previous argument. By the definition of $IJ$, this shows us $a \in IJ$. Thus $I \cap J \subset IJ$.

Thus we've proven that $IJ = I \cap J$ in this circumstance. QED



### Let $D$ be the integral domain $\mathbb{Z}[\sqrt{-5}]$. (a) Show that $2$ is an irreducible element of $D$. (b) Show that $2$ is not a prime element of $D$. (c) Show that $D$ is not a UFD.
#### My Solution:
(a) TO BE DONE LATER

(b)

(c)

















## August 2012
### For any group $G$ we denote $G^2$ as the subgroup of $G$ generated by the squares of elements of $G$. In other words, $G^2 = \{x^2 | x \in G\}$. First, prove that $G^2$ is a normal subgroup of $G$, then prove that $\frac{G}{G^2}$ is Abelian. 
#### My Solution:
 First, we will prove that $G^2 \unlhd G$. Let $h \in G^2$ and $g \in G$. So 
$$g^{-1}hg = g^{-1}g^{-1}ghg = (g^{-1})^2h^{-1}(hg)^2 \in G^2$$
because $(g^{-1})^2, g^2, h \in G^2$. Thus, $G^2 \unlhd G$.

Next we just need to prove that $\frac{G}{G^2}$ is Abelian. Well, for all $yG^2, xG^2 \in \frac{G}{G^2}$, we want to show that $xG^2 yG^2 = yG^2 xG^2$. First, note that $xG^2 yG^2 = xyG^2$ and $yG^2 xG^2 = yxG^2$. And $xyG^2 = yxG^2$ iff $xy(yx^{-1}) \in G^2$. So if we can show that $xyx^{-1}y^{-1} \in G^2$, then we know that $\frac{G}{G^2}$ is Abelian. Well,
$$xyx^{-1}y^{-1} = x^{-1}xxyyy^{-1}x^{-1}y^{-1} = x^{-1}(xy)^2y^{-1}x^{-1}y^{-1} = h(x^{-1}y^{-1})^2$$
Where $h \in G^2$ because $G^2 \unlhd G$. Thus we have $h(x^{-1}y^{-1})^2 \in G^2$, implying that $xyx^{-1}y^{-1} \in G^2$, which shows us that $\frac{G}{G^2}$ must be Abelian. QED



### If $N \unlhd G$ and $H \leq G$, prove that $NH \leq G$. Moreover, if $H \unlhd G$, prove then that $NH \unlhd G$.
#### My Solution:
Well, $NH \leq G$ iff $NH = HN$. So for all $n \in N$ and $h \in H$, $nh \in NH$ and $hn \in HN$. Also because $N \unlhd G$, for all $h \in H$, $hnh^{-1} \in N$. So $hnh^{-1}*h \in NH \implies hn \in NH \implies NH \subseteq HN$. And $h^{-1}hnh^{-1} \in HN \implies nh^{-1} \in HN \implies HN \subseteq NH$. Thus $NH = HN$ implying that $NH \leq G$. 

Now assume that $H \unlhd G$. We want to show that $NH \unlhd G$. Well, then we want to show that for all $nh \in NH$, $gnhg^{-1} \in NH$. Well, $gn = n'g$ and $hg^{-1} = g^{-1}h'$ where $n' \in N$ and $h' \in H$. So 
$$gnhg^{-1} = n'gg^{-1}h' = n'h' \in NH$$
Thus $NH \unlhd G$. QED



### Show that any group $G$ of order $105$ are not simple.
#### My Solution:
First note that $105 = 3*5*7$. Let's denote the number of Sylow-$p$ subgroups of $G$ by $n_p$. Then $n_3 = 3k+1$ and $n_3|35$; $n_5 = 5k+1$ where $n_5|21$; and finally $n_7 = 7k+1$ where $n_7|15$, where in all of these cases $k$ is some integer. We know that if $n_p=1$ for any $p$, then $G$ cannot be simple. Notice $n_5 = \{1,21\}$ and $n_7 = \{1,15\}$. 

Assume $G$ is simple. Then $n_5 = 21$, $n_7 = 15$. This implies that there are $21*4=44$ non-identity elements in Sylow-$5$ subgroups and $15*6=90$ non-identity elements in Sylow-$7$ subgroups, all of which intersect trivially. But $44+90=134$ which gives us too many elements, thus either $n_5=1$ or $n_7 =1$ which implies that $G$ must not be simple. QED



### Let $F[x]$ be a ring of polynomials where the coefficients belong to the field $F$. Prove that every ideal in$F[x]$ is principal. Is this fact still true if we replace $F$ with any commutative ring $R$?
#### My Solution:
Let $I \subseteq F[x]$. If $I = (0)$ or $I=(1)=F$, then the case is trivial and we're done. Suppose $p \in I$ is a nonzero polynomial of smallest possible degree. So, if $f \in I$, $\mathrm{deg}(f) \geq \mathrm{deg}(p)$. Also there exists a unique $q,r \in F$ such that $f=pq+r$ and $0 \leq \mathrm{deg}(r) \leq \mathrm{deg}(p)$. Because $I$ is an ideal containing $p$ and $f$, $r = f-pq \in I$ which implies that $r=0$ and $f=pq$. Thus for all $f \in I$, $f$ is generated by $p$. Thus $I$ is principal. QED

Note, this trait is not true necessarily if $F$ is not a field. This is because a field is a Euclidean Domain, meaning that we can use the division algorithm. However, not all commutative rings are Euclidean Domains. 



### Consider the subring $R = \{a+bi\sqrt{3}|a,b\in \mathbb{Z}\}$ of $\mathbb{C}$. (a) Show that the map $\phi : R \rightarrow \mathbb{Z}$, given by $\phi (a+bi\sqrt{3})=a^2+3b^2$ satisfies the property $\phi(uv) = \phi(u) \phi(v)$ for all $u,v \in R$. Show also that $\phi(u) >3$ for every $u \in R$, unless $u \in \{0,1,-1\}$. (b) Use part a) to show that the only units of $R$ are $1$ and $-1$. (c) Use part a) to show that the elements $2$, $1+i\sqrt{3}$, $1-i\sqrt{3}$ of $R$ are irreducible. Deduce that $R$ is not a UFD.
#### My Solution:
(a)
Let $a+bi\sqrt{3},c+di\sqrt{3} \in R$. Then $$\phi(a+bi\sqrt{3})\phi(c+di\sqrt{3}) = (a^2+3b^2)(c^2+3d^2) = a^2c^2+a^23d^2+3b^2c^2+9b^2d^2$$
Also, 
$$\phi((a+bi\sqrt{3})(c+di\sqrt{3})) = (a^2+3b^2)(c^2+3d^2) = a^2c^2+a^23d^2+3b^2c^2+9b^2d^2$$
Thus $\phi(uv)=\phi(u)\phi(v)$. Now, because $a,b \in \mathbb{Z}$, and $a^2,b^2 \in \mathbb{Z^+}$, we can easily see that $\phi(u) > 3$ whenever $u \notin \{0,1,-1\}$. If $u \in \{0,1,-1\}$, then $\phi(u) \in \{0,1\}$ where $\phi(0) = 0$ and $\phi(\pm{1})=1$, both of which cases make $\phi(u) < 3$. 

(b)
An element $u$ of $R$ is a unit if $uv=1$. This is only true if $b=0$ and $a = \pm 1$, otherwise we will have a complex element. Thus the only units of $R$ are $\pm 1$.

(c) Notice that $\phi$ is simply the norm of our ring $R$.

- Let $uv = 2$. Then $\phi(2) = 4 = \phi(u) \phi(v)$. WLOG, assume $u$ is not a unit. So $\phi(u)\phi(v) = 4$. Suppose $u = a+bi \sqrt{3}$. This implies that $a^2+3b^2 = 2$ or $4$. But for $a^2+3b^2 = 2$, $b=0$ and $a = \sqrt{2} \notin \mathbb{Z}$. Thus $\phi(a) = 4$ which implies that $\phi(v) = 1$ so $v = \pm 1$. Thus $v$ is a unit and $2$ is irreducible.

- Let $uv = 1+i\sqrt{3}$. Then $\phi(1+i\sqrt{3})=4= \phi(u) \phi(v)$. But as we showed above, this implies that either $u$ or $v$ is a unit, thus $1+i\sqrt{3}$ is irreducible in $R$.

- Let $uv = 1-i\sqrt{3}$. Then $\phi(1-i\sqrt{3})=4= \phi(u) \phi(v)$. But as we showed above, this implies that either $u$ or $v$ is a unit, thus $1-i\sqrt{3}$ is irreducible in $R$.

- We can deduce from here that $R$ is not a UFD. This can be seen because $2*2 = 4 = (1+\sqrt{-3})(1-\sqrt{-3})$. This shows us that $R$ is a UFD because $2, 1+\sqrt{-3}, 1-\sqrt{-3}$ are not associates in $R$ because none of them differ by a unit ($\pm 1$). QED



### Let $D = \{\frac{r}{s} \in \mathbb{Q} | r,s \in \mathbb{Z}\}$ where $s$ is odd and $r,s$ are relatively prime. (a) Show that $D$ is a subring of $\mathbb{Q}$. (b) Describe the units of $D$. (c) Show that $D$ is a PID. 
#### My Solution:
(a)
A subring of $R$ is a subset of $R$ that is closed under multiplication. So we want to show that for any $\frac{r}{s}, \frac{t}{q} \in D$ that $\frac{rt}{sq} \in D$. Well, we know that $(r,s)=1=(t,q)$ (they are all rel. prime). If $(r,q) = 1 = (t,s)$, then we're done as the numerator and denominators are both relatively prime, and an odd times an odd makes an odd. But what if $(r,q) \neq 1 \neq (t,s)$? This is the case we need to consider. Well, WLOG, assume $t$ and $s$ are not relatively prime. Then $t = gh$ and $s = jh$ such that both $s$ and $t$ are divisible by $h$. Then
$$\frac{rt}{sq} = \frac{rgh}{jhq} = \frac{rg}{jq}$$
This process can be continued until we find $\frac{n}{d} = \frac{rt}{sq}$ such that $n$ and $d$ are relatively prime and both are contained in $D$. Also, $d$ will be odd because if $a$ and $b$ are odd such that $a=cb$ which implies $c$ is odd, and because you can't factor an even from an odd. Thus we've proven that $D$ is a subring of $\mathbb{Q}$. QED

(b)
The units of $D$ are many elements $\frac{r}{s} \in D$ such that $r$ and $s$ are odd and $r$ and $s$ are relatively prime. This is because $\frac{r}{s}*\frac{s}{r} = 1$ which implies that $\frac{r}{s}$ and $\frac{s}{r}$ are units in $D$. It is important to note that both $r$ and $s \in \mathbb{Z}$ must be odd for this to be the case. $1$ and $-1$ are also units. 

(c)
A "proof" of this part of the problem can be found [here](https://math.stackexchange.com/questions/140150/show-that-the-ring-of-all-rational-numbers-which-when-written-in-simplest-form). However, I believe I have a counter example to this in the fraction $\frac{7}{15} \in D$ as this fraction cannot be generated by $2^n$ for any $n \in \mathbb{Z}$.



### Find the minimal polynomial of $\alpha = \sqrt{3+\sqrt{7}}$ over the field $\mathbb{Q}$ and *prove* that it is the minimal polynomial.
#### My Solution:
Consider the polynomial $f(x) = x^4 - 6x^2 + 2$. In order to be the minimal polynomial of $\alpha$ over $\mathbb{Q}$, it must be the polynomial with smallest degree with $\alpha$ as a root, and be irreducible. Well, it's fairly obvious that $f(\alpha)=0$ by simply testing $x=\alpha$. It is also fairly easy to see that this polynomial has the lowest possible degree that could have $\alpha$ as a root, as $\alpha$ is made up of two square roots that can only be cancelled out by a polynomial of degree $4$. And finally, by checking Eisenstein's Criteria, we can see that $f(x)$ is indeed irreducible. Thus $f(x)$ is our minimal polynomial for $\alpha$ over $\mathbb{Q}$. QED



### Let $G = \mathrm{Gal}(\mathbb{Q}(\sqrt[3]{5},i\sqrt{3})/\mathbb{Q})$. (a) How many elements are there in $G$? (b) Give a proper nontrivial subgroup $H$ of $G$. Describe the subfield $K$ of $\mathbb{Q}(\sqrt[3]{5},i\sqrt{3})$ consisting of the elements fixed by $H$. What is $[\mathbb{Q}(\sqrt[3]{5},i\sqrt{3}):K]$?
#### My Solution:
Not yet Finished



















## August 2011
### Let $R$ be an Artinian ring. (a) For every ideal $I$ in $R$ show that $R/I$ is Artinian. (b) Show that every prime ideal in $R$ is also a maximal ideal.
#### My Solution:
We will skip part (b) as it is a repeat of an earlier problem because if $R$ is Artinian, then it is an integral domain.

(a)
So for all descending chains of ideals in $R$
$$I_1 \supseteq I_2 \supseteq ... \supseteq I_n \supseteq ...$$
the descending chain stabilizes such that for some $I_i$, $I_i = I_{i+1}$. Well, note that $R/I = \{rI| \forall r \in R\}$. We will now prove a lemma stating that $J/I$ is an ideal of $R/I$ if $I$ and $J$ are ideals of $R$. 

For all $r /in R$, $rJ = Jr = J$. So then for all $rI \in R/I$, $rI(J/I) = r(J/I) = J/I$. So $J/I$ is an ideal of $R$. 

Now consider a descending chain of ideals 
$$J_1 \supseteq J_2 \supseteq ... \supseteq J_n \supseteq ...$$
where all $J_i$'s are ideals in $R$. Then 
$$J_1/I \supseteq J_2/I \supseteq ... \supseteq J_n/I \supseteq ...$$
is a descending chain of ideals in $R/I$. Let $J_m = J_{m+1}$ because $R$ is Artinian. Then $J_m/I = J_{m+1}/I$ because $J_m = J_{m+1}$. So $R/I$ is Artinian. QED



### Let $H$ be the set of all $3 \times 3$ upper right triangular matrices with $1$ in the diagonal. Prove that $H$ is a noncommutative group under matrix multiplication.
#### My Solution:
First off, in order to be a group all elements must be closed under the operation, the operation must be associative, and ther must be an identity and an inverse. Also, for the sake of simplicity, let
$$A = \bigl( \begin{smallmatrix}1 & a & b\\ 0 & 1 & c\\ 0 & 0 & 1 \end{smallmatrix}\bigr) \in H$$
$$B = \bigl( \begin{smallmatrix}1 & x & y\\ 0 & 1 & z\\ 0 & 0 & 1 \end{smallmatrix}\bigr) \in H$$
$$C = \bigl( \begin{smallmatrix}1 & 1-a & c-b\\ 0 & 1 & -c\\ 0 & 0 & 1 \end{smallmatrix}\bigr) \in H$$

Well, the identity is obviously the identity matrix $I = \bigl( \begin{smallmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 0 & 1 \end{smallmatrix}\bigr)$. Also, 
$$A \times B = \bigl( \begin{smallmatrix}1 & x+a & y+az+b\\ 0 & 1 & z+c\\ 0 & 0 & 1 \end{smallmatrix}\bigr) \in H$$
So $H$ is closed under the operation. We can also check that $A \times C = C \times A = I$, thus we have an inverse. And finally, we know from experience that matrix multiplication is associative, thus $H$ is indeed a group. So the last thing here to show is just that $H$ is not an Abelian group. Well, using $A \times B$ that we found above, we can check 
$$B \times A = \bigl( \begin{smallmatrix}1 & x+a & cx+y+b\\ 0 & 1 & z+c\\ 0 & 0 & 1 \end{smallmatrix}\bigr) \neq A \times B$$
Thus $H$ is a noncommutative group. QED



### Let $H$ and $K$ be normal subgroups of a group $G$. Assume that $HK = G$ and $H \cap K = \{1\}$. (a) Prove that $hk = kh$ for all $h \in H$ and $k \in K$. (b) Prove that $G$ is isomorphic to $H \times K$.
#### My Solution:
(a)
For all $h \in H$ and $k \in K$ we have 
$$hkh^{-1}k^{-1} = (hkh^{-1})k^{-1} = h(kh^{-1}k^{-1}) \in H \cap K$$
so $hkh^{-1}k^{-1} = e$ if $e =1$ is the identity. This implies that $hk = kh$.

(b)
Let $f : H \times K \rightarrow G$ such that $f(h,k) = hk$. For any $h, h' \in H$ and $k, k' \in K$, 
$$f(h,k)f(h',k') = (hk)(h'k') = hh'kk'=(hh')(kk') = f(hh',kk') = f((h,k)(h',k'))$$
Thus $f$ is a homomorphism. Since $HK = G$, any element $g \in G$ is simply $g = hk$ for some $h \in H$ and $k \in K$, and $f(h,k) = hk = g$ so $f$ is obviously onto. Finally if $(h,k) \in \mathrm{ker}(f)$, then $hk = e$. So $h = k^{-1} \in H \cap K = \{1\}$ so $(h,k) = (e,e)$ which implies that $f$ is one-to-one. Thus $f$ must be an isomorphism. QED



### Show that every prime element in an integral domain is irreducible.
#### My Solution:
Let $R$ be an integral domain. Let $p \in R$ be a prime element in $R$. Assume $p=ab$. This implies that $p|a$ or $p|b$. WLOG, assume that $p|a$. Then $pq = a$ for some $q \in R$. Thus
$$1*a = a = pq = abq \implies 1 = bq$$
Thus $b$ is a unit and $p$ must be irreducible. QED



### Consider the set $\mathbb{Z}[i]$, the *Gaussian integers*. (a) Show that $\mathbb{Z}[i]$ is an integral domain. (b) Find all units of $\mathbb{Z}[i]$. (c) It is known that $\mathbb{Z}[i]$ is a UFD. Does $13 = (2+3i)(2-3i)=(3+2i)(3-2i)$ contradict this fact? (d) Express $5$ as a product of irreducible elements in $\mathbb{Z}[i]$.
#### My Solution:
(a)
In order for $\mathbb{Z}[i]$ to be an integral domain, it must contain no zero divisors. Let $a,b \in \mathbb{Z}[i]$ such that $ab = 0$. Well, if $a = x+yi$ and $b = w+zi$ then 
$$ab = (x+yi)(w+zi) = xw+yi+xzi+yizi$$
$$= (xw-yz)+i(yw+xz) = 0$$
This implies that $xw = yz$ and $yw = -xz$, but this is only the case if either $x,y = 0$ or $w,z = 0$. Thus $\mathbb{Z}[i]$ is an integral domain.

(b)
The units of $\mathbb{Z}[i]$ are $\{1,-1,i,-i\}$ because $(a+bi)(c+di)=xy = 1$ is only true for these values.

(c)
No, because $(2+3i)$ is an associate of $3-2i$ because $(2+3i)*-i = 3-2i$. Similarly, $2-3i$ is an associate of $3+2i$ because $(2-3i)*i = 3+2i$. Thus this does not make a contradiction.

(d)
$5=(1+2i)(1-2i)$ 



### Prove that every finite integral domain is a field.
#### My Solution:
Let $R$ be a finite integral domain with $0 \neq a \in R$. Consider $a,a^2,a^3,...$, since there are only finitely many elements, we must have $a^m = a^n$ where $m < n$. Then 
$$0 = a^m - a^n = a^m(1-a^{n-m})$$
Since there are no zero divisors, we must have $a^m \neq 0$ and hence $1-a^{n-m} = 0$ which implies that $1 = a(a^{n-m-1})$. Thus $a \in R$ has a multiplicative inverse, thus $R$ is a field. QED



### (a) Show that the polynomial $f(x) = x^4 -2$ is irreducible over $\mathbb{Q}$. (b) Find a factorization of $f(x)$ into linear factors over $\mathbb{C}$. Find the splitting field $F$ of $f(x)$ over $\mathbb{Q}$. (c) Find the degree of $F$ over $\mathbb{Q}$. Justify.
#### My Solution:
(a)
It is easy to see by Eisenstein's Criteria that $f(x)$ is irreducible over $\mathbb{Q}$.

(b)
$$f(x) = x^4 - 2 = (x^2 + \sqrt{2})(x^2 - \sqrt{2})$$
$$= (x+i \sqrt[4]{2})(x-i \sqrt[4]{2})(x- \sqrt[4]{2})(x+ \sqrt[4]{2})$$
Thus we can easily see that the splitting field of $f(x)$ over $\mathbb{Q}$ will be $F = \mathbb{Q}(\sqrt[4]{2},i)$ as $f(x)$ can be factored into linear factors in $F$.

(c)
Here we will use what I like to call the *double extension lemma*. Using it, we find that
$$[\mathbb{Q}(\sqrt[4]{2},i):\mathbb{Q}]=[\mathbb{Q}(\sqrt[4]{2},i):\mathbb{Q}(i)][\mathbb{Q}(i):\mathbb{Q}]$$
Using this we can find that $$[\mathbb{Q}(\sqrt[4]{2},i):\mathbb{Q}] = \mathrm{deg}(x^4 - 2) \times \mathrm{deg}(x^2+1) = 4 \times 2 = 8$$
Thus the degree of the extension is $8$. QED















## August 2009
### Let $G$ be a group under the operation $*$. Let $u \in G$. Define a new binary operation $\times$ on $G$ as follows: $a \times b = a * u * b$ for all $a,b \in G$. (a) Prove that $\times$ is associative. (b) Show that $G$ contains an identity element under $\times$ and identify it. (c) Show that every element of $G$ contains an inverse under $\times$. (d) True or False: The groups $(G,*)$ and $(G, \times)$ are isomorphic. Justify.
#### My Solution:
(a)
Well, let $a,b,c \in G$. Then
$$(a \times b) \times c = (a*u*b)*u*c = a*u*(b*u*c) = a \times (b \times c)$$
because $*$ is associative. Thus $\times$ is associative as well. 

(b)
Well, 
$$a \times u^{-1} = a*u*u^{-1} = a = u^{-1}*u*a = u^{-1} \times a$$
This implies that $G$ has an identity under $\times$ and it's $u^{-1}$.

(c)
Let $a \in G$. Then $u^{-1}*a*u^{-1} \in G$ as well. Thus 
$$a \times (u^{-1}*a*u^{-1}) = a*u*u^{-1}*a*u^{-1} = u^{-1} $$
$$u^{-1}= u^{-1}*a*u^{-1}*u*a = (u^{-1}*a*u^{-1}) \times a$$
So for all $a \in G$ there exists an inverse $u^{-1}*a*u^{-1} \in G$ under $\times$. 

(d)
Let $\Gamma : (G, \times) \rightarrow (G,*)$. Then for all $a \in G$, $\Gamma(a) = a$, but $\Gamma(a \times b) = a*u*b$. Observe though that $\Gamma(a) \Gamma(b) = a*b \neq a*u*b$. Thus these groups couldn't be isomorphic because $\Gamma$ isn't even a homomorphism. QED



### Show that if $f: G \rightarrow H$ is a surjective group homomorphism and $K$ is a normal subgroup of $G$, then $f(K)$ is a normal subgroup of $H$ and $H/f(K) \cong G/K$.
#### My Solution:
First, let $K \unlhd G$ and $f(g) = h$ for all $g \in G$ and some $h \in H$. Let $k \in K$. This implies that $gkg^{-1} = k' \in K$. So $f(gkg^{-1}) = f(k') \in f(K)$. Also note then that $f(gkg^{-1}) = hf(k)h^{-1}$ because $f$ is a homomorphism. This implies that $f(K) \unlhd H$ thus we have proven the first part. 

Let $\Gamma :H \rightarrow G/K$. If we can show that $\Gamma$ is a homomorphism with a kernel of $f(K)$, then by the first isomorphism theorem, we're done. First off, define $f(g) = h$ and $f(g') = h'$ for some $g,g' \in G$ and $h,h' \in H$. If $h \in H$ and $gK \in G/K$, we can define $\Gamma$ by $\Gamma(h) = gK$. Then,
$$\Gamma(hh') = gg'K = gKg'K = \Gamma(h) \Gamma(h')$$
Thus $\Gamma$ is a homomorphism. Finally, $\mathrm{ker}(\Gamma) = \{a \in H| \Gamma(a) = K\}$. Well, $\Gamma(a) = K$ iff $f(a) \in f(K)$. This implies that $\mathrm{ker}(\Gamma) = f(K)$. Thus by the first isomorphism theorem, 
$$\frac{H}{f(K)} \cong \frac{G}{K}$$ QED























## August 2008
### Let $R = C[0,1]$ be the set of all continuous real-valued functions on $[0,1]$. Define addition and multiplication on $R$ as follows. For $f,g \in R$ and $x \in [0,1]$, $(f+g)(x) = f(x)+g(x)$ and $(fg)(x) = f(x)g(x)$. (a) Show that $R$ with these operations is a commutative ring with identity. (b) Find the units of $R$. (c) If $f \in R$ and $f^2 = f$, then show that $f=0_R$ or $f = 1_R$.
#### My Solution:
(a)
The identity function here is obvious, it is $f(x) = 1$. 

Let $f$ and $g$ be in $R$. Then $(f+g)(x) = f(x)+g(x) = g(x)+f(x) = (g+f)(x)$. So $(R, +)$ is Abelian.
Also for all $f(x)$ there exists a $g(x)=-f(x)$ such that $f(x)+(-f(x)) = 0_R$. Hence because of this and because $g(x)-f(x)$ is a continuous function from $0$ to $1$, so $(R,+)$ is an Abelian group.

Let $f,g,h \in R$. Consider $$((fg)h)(x) = (fg)h(x) = (fg)(x)h(x) = f(x)g(x)h(x) = f(x)((gh)(x)) = (f(gh))(x)$$ Thus multiplication is associative. 

Let $f,g,h \in R$. Consider $$(f(g+h))(x) = f((h+h)(x))= f(g(x) + h(x)) = f(x)g(x) + f(x)h(x) = (fg)(x)+(fh)(x)$$ Thus $R$ follows the distributive property. Thus $R$ is a ring. It is also easy to see that $(fg)(x) = (gf)(x)$ because all of the functions are continuous on $[0,1]$. Thus $R$ is a commutative ring with identity $f(x) = 1$.

(b)
The units of $R$ are just the inverse functions of $f(x)$. ie. $(fg)(x) = 1$ iff $g(x) = f^{-1}(x)$. 

(c)
Let $f^2 = f$. Then $f^2(x) = f(x)f(x)$. Then by cancellation, $f(x) = 1_R$ or $f(x) = 0$. QED



### Prove that a group $G$ of order $10000=2^4 * 5^4$ cannot be simple.
#### My Solution:
Assume $G$ is simple and denote the number of Sylow-$p$ subgroups as $n_p$. Then $n_2 = 2k+1$ where $k \in \mathbb{Z^+}+\{0\}$ and $n_2 | 5^4 = 625$. Also, $n_5 = 5k+1$ where $k \in \mathbb{Z^+}+\{0\}$ and $n_5 | 2^4 = 16$. So $n_5 \in \{1,16\}$. Since $G$ is not simple by assumption, then $n_5 = 16$. 

Thus because $G$ is smple and $n_5 = 16$, there exists $N \leq G$ such that $[G:N] = 16$. This implies that $G$ can be embedded in $S_{16}$ if we let $G$ act on $N$ by conjugation. But then by Lagrange's theorem $10,000$ should divide $16!$ which it does not. Thus we have a contradiction, so $G$ cannot be simple. QED














## Important proofs (not specific to Qualifiers)




### Prove the First Isomorphism Theorem for Groups
#### My Solution
First we will state the theorem itself:

Let $\phi : G \rightarrow H$ be a homomorphism of groups, then $\mathrm{ker} \phi \unlhd G$ and $\frac{G}{\mathrm{ker}\phi} \cong \phi(G)$.

To shorten things, let $K = \mathrm{ker}\phi$. Define the homomorphism $\psi : G/K \rightarrow \phi(G)$ by $\psi(Kg) = \phi(g)$. We claim that $\psi$ is an isomorphism. So we need to check that it's a well-defined homomorphism, and a bijection. First, to check that it's well-defined, we will check to see that if $a \in Kg$, then $\phi(a) = \phi(g)$. If we let $a = kg$ then for some $k \in K$, then 
$$\phi(a) = \phi(kg) = \phi(k)\phi(g) = \phi(g)$$
Now we will show that $\psi$ is a homomorphism. Consider $Kg, Kh \in G/K$. Then for any $a,b \in K$ we have that
$$\psi(Kg*Kh) = \psi(Kgh) =\phi(gh) = \phi(g) \phi(h) = \psi(Kg) \psi(Kh)$$
This proves that $\psi$ is a well-defined homomorphism. To prove that $\psi$ is one-to-one, we must prove that $\mathrm{ker}(\psi) = K$. Well, observe that 
$$\psi(Kg) = 1 \iff \phi(g) = 1 \iff g \in \mathrm{ker}(\phi) \iff g \in K \iff Kg = K$$
So $\mathrm{ker}(\psi) = K$. Finally we just need that $\psi$ is onto, which is somewhat obvious from the fact that $\phi(g) \in \phi(G)$ so that $\phi(g)$ has preimage $Kg$. Thus we have proven the First Isomorphism Theorem for Groups. QED



### Prove the 2nd Isomorphism Theorem for Groups
#### My Solution:

First we must state it. Let $G$ be an arbitrary group. For any two subgroups $H$ and $K$ of $G$, define $HK = \{ hk | h \in H, k \in K\}$. Assume $H \unlhd G$ and $K \leq G$. Then: (a) $HK \leq G$. (b) $H \unlhd HK$ and $(H \cap K) \unlhd K$. (c) $\frac{HK}{H} \cong \frac{K}{H \cap K}$.

(a) Recall that $HK$ can only be a subgroup if $HK = KH$. Thus if $H \unlhd G$, and we let $h \in H$ and $k \in K$, by assumption $khk^{-1} \in H$. Thus
$$kh = (khk^{-1})k \in HK$$ 
This proves that $KH \subseteq HK$. Similarly, $hk = k(k^{-1}hk) \in KH$ which proves the reverse containment. Thus $HK \leq G$. QED

(b) Since $K$ normalizes $H$ and $H$ normalizes itself trivially, this implies that $HK$ normalizes $H$. Thus $H \unlhd HK$. Since $H \unlhd HK$, the quotient group $\frac{HK}{H}$ is well defined. Define the map $\Gamma : K \rightarrow \frac{HK}{H}$ by $\Gamma (k) = kH$. Since the group operation in $\frac{HK}{H}$ is well defined, it's easy to see that $\Gamma$ is a homomorphism:
$$\Gamma(k_1 k_2) = (k_1 k_2)H = k_1 H *k_2 H = \Gamma(k_1) \Gamma(k_2)$$
Alternatively, the map $\Gamma$ is just the restriction to the subgroup $K$ of the natural progression homomorphism $\pi : HK \rightarrow \frac{HK}{H}$, so it's also a homomorphism. It is clear then from the definition of $HK$ that $\Gamma$ is onto. The identity of $\frac{HK}{H}$ is simply $H$, so the kernel of $\Gamma$ consists of the elements $k \in K$ with $kH = H$, or where $k \in H$. Thus $\mathrm{ker}\Gamma = H \cap K$. So by the first isomorphism theorem, $H \cap K \unlhd K$. QED

(c) Following the proof of part (b), by the First Isomorphism Theorem, $\frac{HK}{H} \cong \frac{K}{H \cap K}$ QED



### State and Prove the 3rd Isomorphism Theorem for Groups
#### My Solution:
First (once again) we must state it first. Let $K,N \unlhd G$ with $N \leq K$. Then $K/N \unlhd G/N$ and $(G/N)/(K/N) \cong G/K$.

The proof that $K/N \unlhd G/N$ is easy and follows from the 4th Isomorphism Theorem for Groups, so we will leave this aside. Now, define
$$\phi: G/N \rightarrow G/K$$
by $\phi(Ng) = Kg$. By the First Isomorphism Theroem, $(G/N)/\mathrm{ker}(\phi) \cong \phi(G)$. It is clear that $\phi$ is onto, so $\phi(G) = G/K$. Now
$$\mathrm{ker}(\phi) = \{Ng \in G/N | Kg = K\} = \{Ng \in G/N | g \in K\} = K/N$$
Thus by the First Isomorphism Theorem, $(G/N)/(K/N) \cong G/K$. QED



### State and Prove the 1st Isomorphism Theorem for Rings
#### My Solution:
If $\phi: R \rightarrow S$ is a homomorphism of rings, then the kernel of $\phi$ is an ideal of $R$, the image of $\phi$ is a subring of $S$, and $R/\mathrm{ker}(\phi) \cong \phi(R)$

Proof: 

If $I$ is the kernel of $\phi$, then the cosets of $I$ are precisely the fibers of $\phi$. In particular, the cosets $r+I,s+I,$ and $rs+I$ are the fibers of $\phi$ over $\phi(r), \phi(s),$ and $\phi(rs)$ respectively. Since $\phi$ is a ring homomorphism, $\phi(r) \phi(s) = \phi(rs)$, hence $(r+I)(s+I) = rs+I$. Multiplication of cosets is well defined and so $I$ is an ideal and $R/I$ is a ring. The correspondence $R+I \rightarrow \phi(r)$ is a bijection between rings $R/I$ and $\phi(R)$ which respects addition and multiplication, hence is a ring isomorphism. Proving that the image of $\phi$ is a subring of $S$ is trivial. QED 



### State and Prove the 2nd Isomorphism Theorem for Rings
#### My Solution:
Let $A$ be a subgring and let $B$ be an ideal of $R$. Then $A+B = \{a+b| a \in A, b \in B\}$ is a subring of $R$, $A \cap B$ is an ideal of $A$ and $\frac{(A+B)}{B} \cong \frac{A}{(A \cap B)}$

Proof:

(a)
$A$ is a subring and $B$ is an ideal, so $1+0 \in A+B$. Let $a_1 + b_1$ and $a_2 + b_2$ be elements of $A+B$. Then
$$(a_1+b_1) - (a_2+b_2) = (a_1-a_2)+(b_1-b_2)$$
and
$$(a_1+b_1)(a_2+b_2) = a_1a_2+a_1b_2+b_1a_2+b_1b_2$$
Hence $A+B$ is a subring of $R$.

(b)
The intersection $A \cap B$ is nonempty since $0$ is contained in $A$ and $B$. Let $b_1,b_2 \in A \cap B$ and let $a \in A$. Then $b_1+b_2 \in A \cap B$ sinc $A$ and $B$ are both closed under addition. Furthermore $ab_1$ and $ab_2$ are in $A \cap B$ since $B$ is closed under multiplication from $R \supset A$ and $A$ is closed under multiplication. Thus $A \cap B$ is an ideal of $A$.

(c)
Consider the map $\phi: A \rightarrow (A+B)/B$ which sends an element $a$ to $a+B$. THis is a ring homomorphism by definition of addition and multiplication in quotient rings (easy to prove). We claim that it is onto with kernel $A \cap B$ whcih would complete the proof by the first isomorphism theorem for rings. Consider the elements $a \in A$ and $b \in B$. Then $a + b + B = a +B$ since $b \in B$, so $a+b+B \in \mathrm{im} \phi$ and hence $\phi$ is onto. Let $a \in A$ be an element of $\mathrm{ker}(\phi)$. THen $a+B =B$ which holds iff $a \in B$ or equivalently if $a \in A \cap B$. Thus $\mathrm{ker}(\phi) = A \cap B$ and by the first isomorphism theorem we have our result. QED



### State and Prove the 3rd Isomorphism Theroem for Rings
#### My Solution:
Let $I$ and $J$ be ideals of $R$ with $J \subseteq I$. Then $\frac{I}{J}$ is an ideal of $\frac{R}{J}$ and $\frac{(R/J)}{(I/J)} \cong \frac{R}{I}$.

Proof:

Since $I$ and $J$ are ideals, they are nonempty and so $I/J = \{a+J|a \in I\}$ is also nonempty. Let $a_1,a_2 \in I$ and let $r \in R$. By definition of addition and multiplication of cosets, we have
$$(a_1+J)+(a_2+J)=(a_1+a_2)+J$$
$$(r+J)(a_1+J)=ra_1+J$$
and
$$(a_1+J)(r+J)=a_1r+J$$
Since $I$ is an ideal, $a_1+a_2,ra_1,$ and $a_1r$ are contained in$I$ so $I/J$ is an ideal of $R/J$. Consider the map $\phi:R/J \rightarrow R/I$ that sends $r+J$ to $r+I$. We claim that this is a well-defined onto homomorphism with kernel equal to $I/J$. This is fairly obvious to see as every input has an image in $R/I$. As for the kernel, take any $a+J \in I/J$ where $a \in I$. Well, $a+J \in R/J$ as well, and maps to $a+I = I$ because $a \in I$. Thus $I/J$ is the kernel. Thus we have proven the desired result by the first isomorphism theorem for rings. QED









## Definitions and Important Theorems (without proofs)
### Group Theory

- Hard to define in words, but remember what the dihedral group is ($D_2n$, where $n$ is the number of sides of the geometric representation).

- A map $\Gamma$ is a *homomorphism* if it maps a group $G$ to a group $H$ such that if $g \in G$ and $h \in H$
$$\Gamma(gh)=\Gamma(g)\Gamma(h)$$

- An *isomorphism* is a homomorphism that is a bijection

- The homomorphism given from $G$ to $S_A$ where $S_A$ is the permutation of the set $A$ is called the *permutation representation* associated to the given action.

- (One-Step-Subgroup Test) A subset $H$ of a group $G$ is a subgroup iff $H$ is nonempty and for all $x,y \in H, xy^{-1} \in H$.

- Define $C_G(A) = \{g \in G | gag^{-1} =a, \forall a \in A\}$. This subset of $G$ is called the *centralizer* of $A$ in $G$.

- Define $Z(G) = \{g \in G | gx = xg, \forall x \in G\}$. This subset of $G$ is the *center*

- Define $gAg^{-1} = \{gag^{-1} | a \in A\}$. Define the *normalizer* of $A$ in $G$ to be the set $N_G(A) = \{g \in G | gAg^{-1}=A\}$.

- The *kernel* of an action of $G$ on $S$ is defined as $\{g \in G | gs = s, \forall s \in S\}$.

- A group $G$ is *cyclic* if $G$ can be generated by a single element, in other words, there exists some $x \in G$ such that $G = \{x^n | n \in \mathbb{Z}\}$.

- If $\phi$ is a homomorphism of $G$ to $H$, the *kernel* of $\phi$ is the set $\{g \in G | \phi(g) = e\}$ where $e$ is the identity of $H$.

- Let $N$ be any subgroup of the group $G$. The set of left cosets of $N$ in $G$ form a partition of $G$. Furthermore, for all $u,v \in G$, $uN=vN$ iff $v^{-1}u \in N$. 

- The element $gng^{-1}$ is called the *conjugate* of $n \in N$ by $g$. The set $gNg^{-1} = \{gng^{-1}| n \in N\}$ is called the *conjugate* of $N$ by $g$. THe element $g$ is said to *normalize* $N$ if $gNg^{-1} = N$. A subgroup $N$ of $G$ is called *normal* if every element of $G$ normalizes $N$. 

- (Lagrange's Theorem) If $G$ is a finite group and $H$ is a subgroup of $G$, then the order of $H$ divides the order of $G$, and the number of left cosets of $H$ in $G$ equals $\frac{|G|}{|H|}$.

- If $G$ is a group and $H \leq G$, the number of left cosets of $H$ in $G$ is called the *index* of $H$ in $G$, denoted $[G:H]$.

- If $G$ is a group of prime order $p$, then $G$ is cyclic, hence $G \cong Z_p$.

- If $G$ is a finite group and $x \in G$, then the order of $x$ divides the order of $G$. In particular $x^{|G|} = 1$ for all $x \in G$. 

- (Cauchy's Theorem) If $G$ is a finite group and $p$ is a prime dividing $|G|$, then $G$ has an element of order $p$.

- If $H$ and $K$ are finite subgroupd of a group then $|HK| = \frac{|H||K|}{|H \cap K|}$

- If $H$ and $K$ are subgroups of a group, $HK$ is a subgroup iff $HK=KH$.

- IF $G$ is a finite abelian group and $p$ is a prime dividing $|G|$, then $G$ contains an element of order $p$.

- A group $G$ is called *simple* if $|G| > 1$ and the only normal subgroups of $G$ are $1$ and $G$. 

- In a group $G$ a sequence of subgroups $1 = N_0 \leq N_1 \leq N_2 \leq ... \leq N_{k-1} \leq N_k = G$ is called a *composition series* if $N_i \unlhd N_{i+1}$ and $N_{i+1}/N_i$ is a simple group. 

- If $G$ is a simple group of odd order, then $G \cong Z_p$ for some prime $p$.

- A group $G$ is *solvable* if there is a chain of subgroups $1 = G_0 \unlhd G_1 \unlhd G_2 \unlhd ... \unlhd G_s = G$ such that $G_{i+1}/G_i$ is abelian for all $i$.

- The permutation $\sigma$ is odd iff the number of cycles of even length in its cycle decomposition is odd. 

- A group action is *faithful* if its kernel is the identity.

- (Cayley's Theorem) Every group is isomorphic to a subgroup of some symmetric group. If $G$ is a group of order $n$, then $g$ is isomorphic to a subgroup of $S_n$.

- If $G$ is a finite group of order $N$ and $p$ is the smallest prime dividing $|G|$, then any subgroup of index $p$ is normal.

- Two elements $a$ and $b$ of $G$ are said to be *conjugate* in $G$ is there is some $g \in G$ such that $b = gag^{-1}$. The orbits of $G$ acting on itself by conjugation are called the *conjugacy classes* of $G$.

- (The Class Equation) $|G| = |Z(G)| + \sum_{i=1}^{r}|G:C_G(g_i)|$.

- Let $G$ be a group. An isomorphism from $G$ onto itself is called an *automorphism* of $G$.

- Let $G$ be a group and let $g \in G$. Conjugation by $g$ is called an *inner automorphism* of $G$ and the subgroup of $Aut(G)$ consisting of all inner automorphisms is denoted by $Inn(G)$.

- A subgroup $H$ of a group $G$ is called *characteristic* in $G$ if every automorphism of $G$ maps $H$ to itself.

- (Sylow's Theorem) Let $G$ be a group of order $p^\alpha m$ where $p$ is a prime not dividing $m$. Then: (i) Sylow $p$-subgroups of $G$ exist, (ii) If $P$ is a Sylow $p$-subgroup of $G$ and $Q$ is any $p$-subgroup of $G$, then there exists $g \in G$ such that $Q \leq gPg^{-1}$, in particular two Sylow $p$-subgroups of $G$ are conjugate in $G$, and (iii) The number of Sylow $p$-subgroups of $G$ is of the form $1+kp$, or $n_p \equiv 1(mod (p))$.

- If $P$ is a Sylow $p$-subgroup of $G$, then the following are equivalent: $P$ is characteristic in $G$; $P$ is the unique Sylow $p$-subgroup of $G$ ($n_p =1$); $P$ is normal in $G$.

- A *maximal subgroup* of a group $G$ is a proper subgroup $M$ of $G$ such that there are no subgroups $H$ of $G$ with $M \leq H \leq G$.



### Ring Theory

- A *ring* $R$ is a set together with two binary operations $+$ and $\times$ satisfying the following properties:

-- $(R, +)$ is an abelian group

-- $\times$ is associative

-- The distributive law holds for $R$

- A ring $R$ is commutative if multiplication is commutative.

- The ring $R$ is said to have an *identity* if there is an element $1 \in R$ such that $1a = a1 = a$ for all $a \in R$.

- A ring $R$ with $1$ is called a *division ring* if every nonzero element $a \in R$ has a multiplicative inverse. A commutative division ring is called a *field*.

- Let $R$ be a ring. A nonzero element of $a \in R$ is called a *zero divisor* if there is a nonzero element $b \in R$ such that either $ab =0$ or $ba=0$. 

- Assume $R$ has an identity $1 \neq 0$. An element $u$ of $R$ is called a *unit* in $R$ if there is some $v$ in $R$ such that $uv = vu = 1$.

- A commutative ring with identity $1 \neq 0$ is called an *integral domain* if it has no zero divisors. 

- A subring of the ring $R$ is a subgroup of $R$ that is closed under multiplication.

- Let $R$ and $S$ be rings. A *ring homomorphism* is a map $\phi : R \rightarrow S$ satisfying:

(a) $\phi(a+b) = \phi(a) + \phi(b)$ for all $a,b \in R$

(b) $\phi(ab) = \phi(a) \phi(b)$ for all $a,b \in R$.

- The *kernel* of the ring homomorphism $\phi$ is the set of elements of $R$ that map to $0$ in $S$. 

- A bijective ring homomorphism is a *ring isomorphism*.

- Let $R$ and $S$ be rings and let $\phi: R \rightarrow S$ be a homomorphism. Then the image of $\phi$ is a subgring of $S$. Also, the kernel of $\phi$ is a subring of $R$.

- Let $R$ be a ring and let $I$ be a subset of $R$, and let $ r \in R$. $rI = \{ra | a \in I\}$ and $Ir = \{ar | a \in I\}$. A subset $I$ of $R$ is a *left ideal* of $R$ if $I$ is a subring and $I$ is closed under left multiplication by elements from $R$, ie. $rI \subseteq I$ for all $r \in R$. A right ideal is identical to this, just replace left with right. Then an *ideal* is a subset $I$ of $R$ that is both a left and a right ideal. 

- Let $a \in R$. $(a)$ is the ideal generated by $a$.

- Let $I$ be an ideal of $R$. $I = R$ iff $I$ contains a unit. Assume $R$ is commutative. Then $R$ is a field iff its only ideals are $0$ and $R$.

- An ideal $M$ in a ring $R$ is a *maximal ideal* if $M \neq R$ and the only ideals containing $M$ are $M$ and $R$.

- Assume $R$ is commutative. The ideal $M$ is a maximal ideal iff the quotient ring $R/M$ is a field. 

- Assume $R$ is commutative. An ideal $P$ is called a *prime ideal* if $P \neq R$ and whenever the product $ab$ of two elements $a,b \in R$ is an element of $P$, then at least one of $a$ and $B$ is an element of $P$.

- Any function $N: R \rightarrow \mathbb{Z}^{+} \cup \{0\}$ with $N(0) =0$ is called a *norm* on the integral domain $R$. If $N(a) >0$ for $a \neq 0$ define $N$ to be a *positive norm*.

- The integral domain $R$ is said to be a *Euclidean Domain* if there is a norm $N$ on $R$ such that for any two elements $a$ and $b$ of $R$ with $b \neq 0$ there exists elements $q$ and $r$ in $R$ such that 
$$a = qb+r | r = 0 \lor N(r) < N(b)$$

- A *Principle Ideal Domain* or *PID* is an integral domain in which every ideal is principal.

- Every nonzero prime ideal in a PID is a maximal ideal.

- If $R$ is any commutative ring such that the polynomial ring $R[x]$ is a PID (or a Euclidean Domain), then $R$ is necessarily a field.

- Let $R$ be an integral domain. Suppose $r \in R$ is nonzero and is not a unit. Then $r$ is called *irreducible* in $R$ if whenever $r=ab$ with $a,b \in R$, at least one of $a$ or $b$ must be a unit in $R$. Otherwise $r$ is *reducible.

- Let $R$ be an integral domain. The nonzero element $p \in R$ is called *prime* in $R$ if the ideal $(p)$ generated by $p$ is a prime ideal. In other words, a nonzero element $p$ isa prime if it is not a unit and whenever $p | ab$ for any $a,b \in R$, then either $p|a$ or $p|b$.

- Let $R$ be an integral domain. Two elements $a$ and $b$ of $R$ differing by a unit are said to be *associate* in $R$.

- In an integral domain a prime element is always irreducible.

- In a PID a nonzero element is a prime iff it is irreducible.

- A *Unique Factorization Domain* or *UFD* is an integral domain $R$ in which every nonzero element $r \in R$ which is not a unit has the following two proporties: (i) $r$ can be written as a finite product of irreducibles $p_i$ of $R$ (not necessarily distinct), so $r = p_1p_2...p_n$; and (ii) the decomposition in (i) is *unique up to associates*, namely, if $r = q_1q_2...q_m$ is another factorization of $r$ into irreducibles, then $m =n$ and there is some renumbering of the factors so that $p_i$ is associate to $q_i$ for all $i$.

- In a UFD a nonzero element is a prime iff it's irreducible.

- The integers $\mathbb{Z}$ are a UFD

- finite fields $\subset$ fields $\subset$ Euclidean domains $\subset$ PIDs $\subset$ UFDs $\subset$ integral domains $\subset$ commutative rings

- If $F$ is a field, then $F[x]$ is a PID and a UFD.

- (Gauss' Lemma) Let $R$ be a UFD with field of fractions $F$ and let $p(x) \in R[x]$. If $p(x)$ is reducible in $F[x]$ then $p(x)$ is reducible in $R[x]$. 

- $R$ is a UFD iff $R[x]$ is a UFD.

- Let $F$ be a field and let $p(x) \in F[x]$. Then $p(x)$ has a factor of degree one iff $p(x)$ has a root in $F$.

- (Eisenstein's Criterion) Let $P$ be a prime ideal of the integral domain $R$ and let $f(x) = x^n + a_{n-1}x^{n-1}+...+a_1x+a_0$ be a polynomial in $R[x]$. Suppose $a_{n-1},...,a_1,a_0$ are all elements of $P$ and suppose $a_0$ is not an element of $P^2$. Then $f(x)$ is irreducible in $R[x]$.



### Field and Galois Theory

- Let $F \subseteq K \subseteq L$ be fields. Then
$$[L:F] = [L:K][K:F]$$

- The *characteristic* of a field $F$ is defined to be the smallest positive integer $p$ such that $p*1_F = 0$ if such a $p$ exists and is defined to be $0$ otherwise.

- The *prime subfield* of a field $F$ is the subfield of $F$ generated by the multiplicative identity $1_F$ of $F$. 

- If $K$ is a field containing the subfield $F$, then $K$ is said to be an *extension field* of $F$, denoted $K/F$.

- The *degree* of a field extension $K/F$ denoted $[K:F]$ is the dimension of $K$ as a vector space over $F$. 

- Let $K$ be an extension of the field $F$ and let $\alpha, \beta,... \in K$ be a collection of elements in $K$. Then the smallest subfield of $K$ containing both $F$ and the elements $\alpha, \beta,...$, denoted $F(\alpha, \beta,...)$ is called the field *generated* by $\alpha, \beta,...$ over $F$.

- If the field $K$ is generated by a single element $\alpha$ over $F$, $K = F(\alpha)$, then $K$ is said to be a *simple* extension of $F$ and the element $\alpha$ is called a *primitive element* for the extension.

- The element $\alpha \in K$ is said to be *algebraic* over $F$ if $\alpha$ is a root of some nonzero polynomial $f(x) \in F[x]$. If $\alpha$ is not algebraic over $F$ then $\alpha$ is said to be *transcendental* over $F$. The extension $K/F$ is said to be *algebraic* if every element of $K$ is algebraic over $F$.

- Let $\alpha$ be algebraic over $F$. Then there is a unique monic irreducible polynomial $m_{\alpha, F}(x) \in F[x]$ which has $\alpha$ as a root. A polynomial $f(x) \in F[x]$ has $\alpha$ as a root iff $m_{\alpha, F}(x)$ divides $f(x)$ in $F[x]$.

- The element $\alpha$ is algebraic over $F$ iff the simple extension $F(\alpha)/F$ is finite.

- If the extension $K/F$ is finite, then it's algebraic.

- Let $L/F$ be an arbitrary extension. Then the collection of elements of $L$ that are algebraic over $F$ form a subfield $K$ of $L$.

- If $K$ is algebraic over $F$ and $L$ is algebraic over $K$, then $L$ is algebraic over $F$.

- THe extension field $K$ of $K$ is called a *splitting field* for the polynomial $f(x) \in F[x]$ if $f(x)$ factors completely into linear factors in $K[x]$ and $f(x)$ does not factor completely into linear factors over any proper subfield of $K$ containing $F$.

- For any field $F$, if $f(x) \in F[x]$ then there exists an extension $K$ of $F$ which is a splitting field for $f(x)$.

- If $K$ is an algebraic extension of $F$ which is the splitting field over $F$ for a collection of polynomials $f(x) \in F[x]$ then $K$ is called a *normal* extension of $F$.

- (Uniqueness of Splitting Fields) Any two splitting fields for a polynomial $f(x) \in F[x]$ over a field $F$ are isomorphic.

- A field $K$ is said to be *algebraically closed* if every polynomial with coefficients in $K$ has a root in $K$. 

- (Fundamental Theorem of Algebra) The field $\mathbb{C}$ is algebraically closed.

- A polynomial over $F$ is called *separable* if it has no multiple roots.

- Let $F$ be a field of characteristic $p$. Then for any $a,b \in F$, 
$$(a+b)^p = a^p + b^p_{}\mathrm{and} (ab)^p = a^p b^p$$

- Suppose that $\mathbb{F}$ is a finite field of characteristic $p$. Then every element of $\mathbb{F}$ is a $p$th power in $\mathbb{F}$.

- If $H$ is a subgroup of the group of automorphisms of $K$, the subfield of $K$ fixed by all the elements of $H$ is called the *fixed field* of $H$.

- Let $K/F$ be a finite extension. Then $K$ is said to be *Galois* over $F$ and $K/F$ is a *Galois* extension if $|Aut(K/F)| = [K:F]$. If $K/F$ is Galois the group of automorphisms $Aut(K/F)$ is called the *Galois Group* of $K/F$, denoted $Gal(K/F)$.

- If $K$ is the splitting field over $F$ of a separable polynomial $f(x)$ then $K/F$ is Galois.

- If $f(x)$ is a separable polynomial over $F$, then the *Galois group of* $f(x)$ over $F$ is the Galois group of the splitting field of $f(x)$ over $F$.

- Let $G= \{\sigma_1 = 1, \sigma_2,...,\sigma_n\}$ be a subgroup of automorphisms of a field $K$ and let $F$ be the fixed field. Then $[K:F] = n = |G|$.

- The extension $K/F$ is Galois iff $K$ is the splitting field of some separable polynomial over $F$.

- (Fundamental Theorem of Galois Theory) Let $K/F$ be a Galois extension and set $G=Gal(K/F)$. Then there is an order reversing bijection between the subfields of $K$ containing $F$ and the subgroups of $G$. Theorem continues, but this is biggest idea.

















