---
title: "My Solutions to Old Analysis Quals"
author: "Jacob S Townson"
date: "August-December 2017"
output:
  word_document:
    fig_height: 4
    fig_width: 5
  html_document:
    fig_height: 4
    fig_width: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Prelude
This document is written in reference to qualifying exams given at the University of Louisville in past years. These solutions are not given from the University, but of my work alone as a way to study for my own qualifying exam. If any tips or recommendations come up and you feel you should share, feel free to raise an issue on GitHub where I have this document saved and open to the public [here](https://github.com/obewanjacobi/gradwork/tree/master/Classes/Old%20Qualifying%20Exams/My%20Solutions). To see the qualifying exams for yourself, [visit this link](http://www.math.louisville.edu/GraduateFAQ/qualifiers/QualifierStudyGuides/). When referencing the Royden book, this is in reference to the *Real Analysis; 4th Edition*. Special thanks to Trevor Leach for sharing his solutions with me for reference on this document. Thank you for reading, and for every advice.

Jacob Townson


# What to Expect:
- differentiation and Riemann integration of functions of one real variable, sequences of
functions, uniform convergence, Lebesgue's characterization of Riemann integrability

- topology of the line, countable and uncountable sets, Borel sets, Cantor sets and Cantor
functions, Baire category theorem

- Lebesgue measure and integration on the line, measurable functions, convergence theorems

- AC and BV functions, fundamental theorem of calculus, Lebesgue differentiation theorem

- 
Hilbert spaces, Lp spaces, lp spaces, Hölder and Minkowski inequalities, completeness



# My Solutions from Quals

## Spring 2017

### Prove that if $A \subset \mathbb{R}$ has Lebesgue measure $0$, then $m(\{e^x | x \in A\}) = 0$.
#### My Solution:
Let $m(A) = 0$ and $E = \{\mathrm{e}^x|x \in A\}$. First note that we know $f(x) = \mathrm{e}^x$ is continuous on $\mathbb{R}$. Let $A_N = [-N,N] \cap A$, then 
$$A = \bigcup_{N=1}^{\infty} A_N$$
Also, $m(A) = 0 \implies m(A_N) = 0$ for all $N \in \mathbb{N}$. By definition of Lebesgue measure, for all $\epsilon > 0$, there exists a sequence of intervals $\{I_n\}^{\infty}_{n=1}$ such that $I_i \cap I_j$ is the empty set for all $i$ and $j$. Also, $A_N \subset \cup I_n$ such that $\sum_n l(I_n) < \epsilon$ since $m(A_N) = 0$. Let $I_n = (a_n,b_n)$, $I_n^* = [a_n,b_n]$, then $m(I_n) = m(I_n^*)$. Then 
$$m(f(A_N)) < \sum_n m(f(I_n)) = \sum_n m(f(I_n^*))$$
Since $f$ is continuous, we know that $m(f(I_n^*)) = \max_{x \in I_n^*} f(x) - \min_{x \in I_n^*} f(x)$. Since $I_n^*$ is a closed interval and $f$ is continuous, we can find $x_1$ and $x_2 \in I_n^*$ such that $f(x_1) = \max_{x \in I_n^*} f(x)$ and $f(x_2) = \min_{x \in I_n^*} f(x)$. WLOG we can assume that $x_1 \leq x_2$. Then, 
$$m(f(I_n^*)) = f(x_1) - f(x_2) \leq |f'(\alpha)|(x_1-x_2) $$
$$\leq \max_{x \in I_n^*} f'(x) \times l(I_n) \leq \max_{x \in I_n^*} f'(x) \epsilon$$
where $\alpha \in (x_1,x_2)$

Since $\max_{x \in I_n^*} f'(x) < \infty$ and $\epsilon \rightarrow 0$, we find that $m(f(I_n)) = 0$. This implies $m(f(A_N)) = 0$ which implies 
$$m(f(A)) = m(f(\cup^{\infty}_N A_N)) \leq \sum_{N}^{\infty} m(f(A_N)) = 0$$
Thus, $m(f(A)) = m(E) = 0$. QED



### Prove that if $f:[0,1] \rightarrow (0,\infty)$ is absolutely continuous, then so is $1/f$.
#### My Solution:
Given that $f$ is absolutely continuous, we know then that for all $\epsilon > 0$, there exists a $\delta > 0$ such that if $\{(a_i,b_i)\}^n _{i=1}$ is a finite collection of disjoint intervals of $[0,1]$ with $\sum ^n _{i=1} |b_i - a_i| < \delta$ implies that $\sum ^n _{i=1} |f(b_i) - f(a_i)| < \epsilon$. Also, because $f$ is absolutely continuous, we know then that it must also be continuous. Hence, $f$  must be bounded on $[0,1]$. Let $m = \min(f)$ on $[0,1]$ and choose $\delta$ such that $\sum ^n _{i=1} |b_i - a_i| < \delta$ gives us 
$$\sum ^n _{i=1} |f(b_i) - f(a_i)| < m^2\epsilon$$
Then note that 
$$\sum ^n _{i=1} \left|\frac{1}{f(b_i)} - \frac{1}{f(a_i)} \right| =  \sum ^n _{i=1} \left|\frac{f(b_i) - f(a_i)}{f(a_i)f(b_i)} \right|$$
$$ \leq \frac{1}{m^2} \sum ^n _{i=1} |f(b_i)-f(a_i)| < \frac{m^2 \epsilon}{m^2} = \epsilon$$
Hence, $\frac{1}{f}$ is absolutely continuous as well. QED



### Prove that if $f$ is absolutely continuous on $[0,1]$ and there is a $g \in C([0,1])$ such that $f' = g$ a.e., then $f$ is differentiable on $[0,1]$ and $f'=g$.
#### My Solution:
Using Lebesgue's fundamental theorem of calculus, we know that 
$$f(x) = f(0) + \int_0 ^x f'$$
Then, because $f' = g$ a.e.;
$$f(x) = f(0) + \int_0 ^x g$$
This implies that $\int_0 ^x f' = \int_0 ^x g$, thus by the fundamental theorem of calculus, if we take the derivative of both sides, we can see that $f'(x) = g(x)$ for all $x$. Note, the reason that we can use the fundamental theorem of calculus here is because the function $f$ is absolutely continuous, which implies it's of bounded variation. QED



### Prove that the series $\sum^{\infty} _{k=0} \sin ^k t$ converges uniformly for $t \in [-\pi/4, \pi/4]$ and then evaluate the following series:
$$\sum^{\infty} _{k=0} \int ^{\pi / 4} _{-\pi / 4} \sin ^k (t)dt$$ 

#### My Solution:
Recall the **Weierstrass M Test**: Let $\sum^{\infty} _{n=1} f_n$ be a series of real valued functions on a subset $A \subset \mathbb{R}$. Suppose there exists a convergent series $\sum ^{\infty} _{n=1} M_n$ where $M_n \geq 0$ such that for all $n \in \mathbb{N}$ and $x \in A$, $|f_n(x)| \leq M_n$. Then $\sum^{\infty} _{n=1} f_n$ converges uniformly.

Now, for $t \in [-\pi/4, \pi/4]$, $\sin ^k (t) \leq \left(\frac{1}{\sqrt{2}}\right)^k$ for all $k$. Note, $\sum^{\infty} _ {k=1} \left(\frac{1}{\sqrt{2}}\right)^k$ converges because it is a geometric series. Thus by the Weierstrass M test, the series converges uniformly for $t \in [-\pi/4, \pi/4]$. QED

Because the series converges uniformly on a compact set, 
$$\sum^{\infty} _{k=1} \int^{\pi/4} _{-\pi/4} \sin ^k (t) dt = \int^{\pi/4} _{-\pi/4} \sum^{\infty} _{k=1}\sin ^k (t) dt = \int^{\pi/4} _{-\pi/4} \frac{1}{1-\sin(t)}dt$$
$$= \int^{\pi/4} _{-\pi/4} \frac{1 + \sin(t)}{\cos ^2 (t)}dt = \int^{\pi/4} _{-\pi/4} \sec ^2 (t) dt + \int^{\pi/4} _{-\pi/4} \tan(t) \sec(t) dt$$
$$=\tan(t)|^{\pi/4}_{-\pi/4} +\sec(t)|^{\pi/4}_{-\pi/4}= 1-(-1)+\sqrt{2}-\sqrt{2} = 2$$ QED



### Let $\{E_n\} \subset \mathcal{M}$ be a sequence of Lebesgue measurable subsets of $[0,1]$. Prove: (a) If $\sum m(E_n) < \infty$ then $m(\lim \sup E_n) = 0$; and (b) If $m(E_n) \to 0$ it may not be true that $m(\lim \sup E_n) = 0$
#### My Solution:
a) Let $\epsilon > 0$, since $\sum m(E_n) < \infty$, there exists an $N$ such that $\sum m(E_N) < \epsilon$. So, 
$$\lim \sup (E_n) = \bigcap^{\infty} _{n=1} \bigcup^{\infty} _{k=n} E_k \subset \bigcup^{\infty} _{k=n} E_k$$
Hence,
$$m(\lim \sup (E_n)) \leq m \left(\bigcup^{\infty} _{k=N} E_k \right) \leq \sum^{\infty} _{k=n} m(E_k) < \epsilon$$
This implies that $m(\lim \sup E_n) = 0$.

b) Let $E_1 = [0,1]$, $E_2 = [0,\frac{1}{2}]$, $E_3 = [\frac{1}{2},1]$, $E_4 = [0, \frac{1}{4}]$, $E_5 = [\frac{1}{4},\frac{1}{2}]$, $E_6 = [\frac{1}{2}, \frac{3}{4}]$, $E_7 = [\frac{3}{4}, 1]$, $E_8 = [0, \frac{1}{8}]$,...
We repeat these definitions in this pattern, giving us that $\lim_{n \to \infty} m(E_n) = 0$. But for all $n \in \mathbb{N}$, $\bigcup^{\infty} _{k=n} E_k = [0,1]$ implying that $\lim \sup (E_n) = [0,1]$. Thus it may not be true that if $m(E_n) \rightarrow 0$ that $m(\limsup (E_n))=0$. QED



### Prove that if $f \in L^p([0,\infty))$, $1 \leq p \leq \infty$, then $\lim_{n \to \infty} \int_0 ^{\infty} f(x) \mathrm{e}^{-nx}dx = 0$
#### My Solution:
Let $A = \{x| f(x) < 1\}$ and $B = \{x|f(x) \geq 1\}$. Note, since $f \in L^p$, $m(B) < \infty$. So,
$$\int^{\infty} _0 f(x) \mathrm{e}^{-nx} dx = \int (f(x) \mathrm{e}^{-nx} \chi_A + f(x) \mathrm{e}^{-nx} \chi_B) dx$$
where
$$\int^{\infty} _0 f(x) \mathrm{e}^{-nx} \chi_A dx < \int^{\infty} _0 \mathrm{e}^{-x} = 1$$
and
$$\int f(x) \mathrm{e}^{-nx} \chi_B dx \leq \int |f|^p \chi_B < \infty$$
since $f \in L^p$. Thus by the Lebesgue Dominated Convergence Theorem,
$$\lim_{n \to \infty} \int^{\infty} _0 f(x) \mathrm{e}^{-nx} dx = \int^{\infty} _0 \lim_{n \to \infty} f(x) \mathrm{e}^{-nx} dx = \int 0 dx = 0$$ QED



### Define the function $f:[0,1] \to \mathbb{R}$ by $f(x) = 0$ if $x$ is irrational, and by $f(x) = \frac{1}{q}$ if $x$ is rational and $x = \frac{p}{q}$ when written in least terms. Decide whether or not $f$ is Riemann integrable on $[0,1]$ and if so, evaluate its integral.
#### My Solution:
Let $A = \{x|\lim_{x \to a} f(x) \neq f(a)\}$, then $A = \{x| x\in \mathbb{Q}\}$. Thus $m(A) = 0$. Also $f$ is clearly measurable as $\{x|f(x) \geq a\} = \{(0, \infty)\}$. Hence $f$ is Lebesgue measurable and $\int f = R f$ with $\int f =0$ since $f=0$ a.e. QED



### Let $\{p_n\}$ be a sequence of polynomials. Suppose that for every point $x \in [0,1]$ there exists an index $n$ satisfying $p_n(x) = 0$. Prove at least one of the polynomials is identically zero.
#### My Solution:
Suppose there does not exist an $n$ such that $P_n = 0$ for all $n \in \mathbb{N}$. Let's define $S_n = \{x \in [0,1]|P_n(x) = 0\}$. Note, $S_n$ has to be finite since each polynomial can only have a finite number of zeros. Now consider $\bigcup^{\infty} _{n=1} S_n \supseteq [0,1]$ since for each $x \in [0,1]$ there exists a polynomial such that $p_n(x) = 0$. But a countable collection of finite sets is countable. But $[0,1]$ is uncountable, thus giving us a contradiction. This implies that one of the polynomials must indeed be identically zero. QED



### Let $A \subset \mathbb{R}$. Prove that the following are equivalent to each other: (a) $A$ is not Lebesgue measurable; and (b) There is an $\epsilon > 0$ such that whenever $B$ is measurable and $A \subset B$, then $m^*(B/A) \geq \epsilon$.
#### My Solution:
Let $A$ not be Lebesgue measurable and suppose that for all $\epsilon > 0$ there exists $B$ such that $A \subset B$ and $m^* (B-A) < \epsilon$. So for every $\frac{1}{n}$, let $B_n \supset A$ and $m^* (B_n - A) < \frac{1}{n}$. Then $A \subset \cap B_n$ and $m^*((\cap B_n) - A) = 0$. Since $m^*((\cap B_n) -A) = 0$ which implies $(\cap B_n) - A$ is measurable (because Lebesgue measure is complete). Hence, $A = [(\cup (B_n ^c)) \cup (\cap (B_n) - A)]^c$ is measurable. This is a contradiction, thus we have proven the desired result. QED



### Let $h \in L^{\infty} (\mathbb{R})$. Define a functional $T: L^1 (\mathbb{R}) \to \mathbb{R}$ by $Tf = \int_{\mathbb{R}} (fh) dm$. Prove that $\sup_{||f||_1 \leq 1} Tf = ||h||_{\infty}$
#### My Solution:
- Will show $\leq$:

$$\sup_{||f||_1 \leq 1} Tf = \sup_{||f||_1 \leq 1} \int fh \leq \sup_{||f||_1 \leq 1} ||f||_1 ||h||_{\infty}$$ Note, by Holder's since we have $1, \infty$, 
$$\leq 1 \cdot ||h||_{\infty} = ||h||_{\infty}$$

- Will show $\geq$:

We may assume $||h||_{\infty} = M > 0$. $\mathbb{R}$ is $\sigma$-finite, so there exists $F_n$ increasing towards $x$ such that $m(F_n) < a$. Define $A_n = \{x \in F_n| |h(x)| > a\}$ for $0<a<M$, to be fixed. Hence $m(A_n) > 0$. Define $g_n(x) = \frac{\mathrm{sgn}(h) - \chi_{A_n}}{m(A_n)}$, which is implies $||g_n||_1 = 1$ for all $n$ and $\int h g_n = a$ for all $n$. Thus $a < \int h g_n$ for all $n$. This implies $\sup_{0<a<M} a < \sup_{||g_n||_1 \leq 1} \int h g_n$. $$||f||_{\infty} = M < \sup_{||f||_1 \leq 1} \int fh = \sup_{||f||_1 \leq 1} Tf$$
Thus we have proven the desired result. QED



## August 2016



### Let $C \subset [0,1]$ be a closed set. Prove that $\chi_C$ is Riemann integrable iff $\partial C$ has Lebesgue measure zero.
#### My Solution:
Assume that $\partial C$ has Lesbegue mesure zero. This implies that $m(\{x| \lim_{x \to a} f(x) \neq f(a)\}) = 0$. Thus the Riemann integral exists and agrees with the Lesbesgue integral.

Now assume that $\chi_C$ is Riemann integrable. This is true iff the Lesbegue integral exists and $m(\{x|\lim_{x \to a} f(x) \neq f(a)\}) = 0$. So $\chi_C$ is discontinuous at its boundary points, which implies that $m(\partial C) = 0$. QED



### Let $S \subset \mathbb{R}$ Prove the following statements are equivalent: (a) $S$ is Lebesgue measurable and (b) There is a $G_{\delta}$ set $G$ and a set $N$ of measure zero such that $S = G-N$.
#### My Solution:
($b \implies a$): Given $G$ is a $G_{\delta}$ set, $G$ must then be Borel measurable. Thus it is also Lebesgue measurable. $N$ must be Lebesgue measurable as well since the Lebesgue $\sigma$-algebra is complete. Thus $S = G-N$ is Lebesgue measurable.

($a \implies b$): This follows directly from a proposition stating that if $A \subset [0,1]$ is a Lebesgue measurable set, and $m$ is a Lebesgue measure, then there exists a set $H$ which cintains $A$ that is the countable intersection of a decreasing sequence of open sets and $m(H-A)=0$. QED



###If $f$ is nonnegative and integrable on $[0,1]$, then $\lim_{n \to \infty} \int_0 ^1 \sqrt[n]{f} = m \{x| f(x) > 0\}$
#### My Solution:
$$\int_0 ^1 \sqrt[n]{f} = \int_0 ^1 \sqrt[n]{f} \cdot \chi_{f=0} + \int_0 ^1 \sqrt[n]{f} \cdot \chi_{f>0}$$
where $\int_0 ^1 \sqrt[n]{f} \cdot \chi_{f=0} = \int_0 ^1 \sqrt[n]{0} = 0$. Thus,
$$\int_0 ^1 \sqrt[n]{f} = \int_0 ^1 \sqrt[n]{f} \cdot \chi_{f>0}$$
Since $f$ is integrable, we know that $\int_0 ^1 \sqrt[n]{f} < \int_0 ^1 f < \infty$, thus $\sqrt[n]{f}$ is integrable as well. So,
$$\lim_{n \to \infty} \int_0 ^1 \sqrt[n]{f} \cdot \chi_{f>0} = \int_0 ^1 \lim_{n \to \infty} \sqrt[n]{f} \cdot \chi_{f>0}$$ by the D.C.T., and thus,
$$= \int_0 ^1 1 \cdot \chi_{f>0} = m(\{x|f(x) > 0\})$$
QED




###Let $f \in L^1 (\mathbb{R})$. If $\int_a ^b f = 0$ for all rational numbers $a$ and $b$ with $a<b$, then $f = 0$ a.e.
#### My Solution:
We will claim here that $f$ integrates to $0$ over arbitrary open sets. Thus for any $\epsilon > 0$, choose an open set $B$ such that $A = \{f>0\} \subset B$ and $m(B-A) < \delta$. Hence
$$\left|\int_A f\right| \leq \left|\int_B f - \int_A f \right| = \left|\int_{B-A} f \right| \leq \int_{B-A} |f| < \epsilon$$
because $m(B-A) < \delta$. Thus the integral is $0$ since this is true for all $\epsilon$.

We must now prove our claim in order to complete the problem. For any $(a,b) \in \mathbb{R} \times \mathbb{R}$, there exists $\{a_n\}, \{b_n\} \in \mathbb{Q}$ such that $a_n$ decreases to $a$ and $b_n$ increases to $b$ as $n$ goes to infinity. Thus $\int_{(a,b)} f = \int_{\cup(a_n,b_n)} f$. Using this, and the dominated convergence theorem, we find that
$$\int_{\cup(a_n,b_n)} f = \lim_{n \to \infty} \int_{(a_n,b_n)} f = 0$$ with $|f|$ as the majorant since $f \in L^1$. Now let $B = \bigcup^{\infty} _{n=1} (a_n,b_n)$ with $(a_n,b_n)$ being arbitrary disjoint intervals. Then 
$$\int_B f = \int \sum^{\infty} _{n=1} f \cdot \chi_{(a_n,b_n)}$$
By the dominated convergence theorem, 
$$\int \sum^{\infty} _{n=1} f \cdot \chi_{(a_n,b_n)} = \sum^{\infty} _{n=1} \int f \cdot \chi_{(a_n,b_n)} = \sum 0 = 0$$ with $|f|$ as the majorant because $f \in L^1$. Thus $\int_B f = 0$ for any open set $B$. A similar proof holds for $m(\{x|f(x) < 0\}) = 0$. Hence $f = 0$ a.e. QED



### Suppose that $f \in L^2 ([0,1])$ and $||f||_2 = 1$. Define $g(x) = xf(x)$. Prove that $g \in L^1 ([0,1])$ and that $||g||_1 \leq \frac{1}{\sqrt{3}}$.
#### My Solution:
For $x \in L^2 ([0,1])$, we have 
$$\left(\int_0 ^1 |f|^2 \right) ^{1/2} = \left(\frac{1}{3} x^3 |^1 _0 \right)^{1/2} < \infty$$
So $x \in L^2$. Given this, we can see that 
$$||x \cdot f(x)||_1 \leq ||x||_2 ||f||_2$$ by Holders' because $2$ and $2$ are conjugate.
Then,
$$||x||_2 ||f||_2 \leq \left(\frac{1}{3} x^3 |^1 _0 \right)^{1/2} \cdot 1 \leq \frac{1}{\sqrt{3}}$$
QED



### Let $\{a_k\}$ be a sequence of real numbers with the property that $|a_k| \leq 1$ for all $k$. Prove that both series $f(x) = \sum^{\infty} _{k=1} a_k x^k$, $g(x) = \sum^{\infty} _{k=1} k a_k x^{k-1}$ converge uniformly on every compact subinterval of $(-1,1)$ and that $f'(x) = g(x)$ for all $x \in (-1,1)$.
#### My Solution: 
Since $|a_k| \leq 1$, 
$$\sum^{\infty} _{k=1} a_k x^k \leq \sum^{\infty}_{k=1} x^k$$ which converges uniformly because $|x| < 1$ by the Weirstrass-M test (and because it's a geometric series). Let $C \subset [0,1]$ be a compact interval of $(-1,1)$ and let $a = \mathrm{max}\{|x|: x \in C\}$. Then $\sum |x|^k \leq \sum a^k$ which converges because it's a geometric sequence. Now we apply the Weirstrass M-test to give us the desired result. 

As for proving that $f'(x) = g(x)$, we simply note that by definition of differentiation on power series that this is true (with simple calculus II logic). QED



### Give an example of a continuous function $f:[0,1] \rightarrow \mathbb{R}$ with the property that $f(0) = 0$, $f(1) = 1$, yet $f'(x) \leq -1$ for almost every $x \in [0,1]$.
#### My Solution:
Let $C(x)$ be the Cantor function on $[0,1]$. Consider $f(x) = 2C(x) -x$. Then $f(0) = 2 \cdot 0 - 0 = 0$ and $f(1) = 2 \cdot 1 - 1 = 1$. Also, almost everywhere the derivative of the Cantor function is 0 (because almost everywhere it is constant). Then the derivative almost everywhere of $f(x)$ would be $f'(x) = -1$ almost everywhere. 



### Let $E_1, E_2, E_3,...$ be a sequence of measurable subsets of $\mathbb{R}$ with the property that $\sum^{\infty} _{n=1} m (E_n) < \infty$. Show almost every $x \in \mathbb{R}$ is contained in only finitely many of the $E_n$.
#### My Solution:
By way of contradiction, suppose there exists an $I \subset \mathbb{R}$ such that $m(I) = c > 0$. Also assume that $I \subset E^* _n$ for all $n$ where $\{E^*_n\}$ is a subsequence of $\{E_n\}$. But 
$$\sum^{\infty} _{n=1} m(E^*_n) \geq \sum^{\infty}_{n=1} m(I) = \sum^{\infty}_{n=1} c$$ which diverges because $c > 0$. Thus by contradiction, we have proven the desired result. QED



### Let $f:[0,1] \rightarrow \mathbb{R}$ be Lebesgue measurable. Prove that if $p \leq f(x) \leq q$ for all $x \in [0,1]$, then $\int_{[0,1]} f$ exists and $p \leq \int_{[0,1]} f \leq q$.
#### My Solution:
First off, it is known that $\int_{[0,1]} 1 = 1$. Since $p \leq f \leq q$, and since we're integrating between $0$ and $1$, we can easily see then that $p \leq \int_{[0,1]} f \leq q$. Let $a = \mathrm{max}\{|p|,|q|\}$, then $|f| < a$ which implies that $\int_{[0,1]} |f| < a$. Thus $f$ is integrable. QED



### Define a sequence of functions $f_n \in L^1[0,1]$ by $f_n(x) = n$ if $x \leq \frac{1}{n}$ and $f(x) = 0$ if $x > \frac{1}{n}$. Does $f_n$ converge in $L^1 ([0,1])$? If so, to what function?
#### My Solution: 
Suppose $f_n \rightarrow f$ in $L^p$. Then $||f_n||_1 \rightarrow ||f||_1$. But $\int|f_n| = \frac{1}{n} \cdot n = 1$ for all $n$. Hence $||f|| = 1$. However, this is a contradiction because $\lim_{n \to \infty} f_n = 0$, thus it does not converge in $L^1 ([0,1])$. QED





## January 2016




### Let $S$ be dense in $\mathbb{R}$ and $f: \mathbb{R} \to \mathbb{R}$. Prove or give a counterexample: $f$ is measurable iff $\{x : f(x) \geq s\}$ is measurable for all $s \in S$.
#### My Solution:
First assume $f$ is measurable. This implies that $\{x|f(x) \geq a\}$ is Lebesgue measurable for all $a \in \mathbb{R}$. Hence $\{x| f(x) \geq s\}$ is Lebesgue measurable for all $s \in S$.

Now assume that $\{x: f(x) \geq s\}$ is measurable for all $s \in S$. It suffices to show that $\{x: f(x) > s\}$ is measurable for all $s \in S^c$. So, let $t \in S^c$, given that $S$ is dense in $\mathbb{R}$. Let $\{t_n\} \subset S$ such that $t_n$ decreases to $t$. Thus,
$$\{x: f(x) > t\} = \bigcup^{\infty} _{n=1} \{x|f(x) \geq t_n\}$$
is the union of measurable sets. Hence $f$ is measurable. QED



### Suppose $\lambda(S)$ denotes the Lebesgue measure of the set $S \subset \mathbb{R}$. Let $g: [0,1] \rightarrow \mathbb{R}$ be absolutely continuous and $E \subset [0,1]$ be such that $\lambda(E) = 0$. Prove that $\lambda(g(E)) = 0$.
#### My Solution:
Given $E \subset [0,1]$ with $\lambda(E) = 0$, let $\{(a_i,b_i)\}$ be a collection of disjoint intervals covering $E$ with $\sum^n _{i = 1} |b_i - a_i| < \delta$. $g$ is absolutely continuous, which implies that it must also be continuous. Thus for each $(a_i,b_i)$, let $(c_i,d_i) \subseteq (a_i,b_i)$ such that $\{f(c_i),f(d_i)\} \in \{\mathrm{min}(f)_{(a_i,b_i)}, \mathrm{max}(f)_{(a_i,b_i)}\}$. Also, recall that because $g$ is continuous, this implies that for all $\epsilon > 0$, there exists a $\delta$ such that $|f(a_i)-f(b_i)| < \epsilon$ where $|a_i - b_i| < \delta$. Now notice that 
$$\sum^n _{i=1} |c_i - d_i| < \sum^n _{i=1} |b_i - a_i| < \delta$$
because $(c_i,d_i) \subseteq (a_i,b_i)$. Thus
$$\lambda(g(E)) \leq \lambda \left(g \left(\bigcup^{\infty}_{i=1}(a_i, b_i)\right) \right) = \lambda\left(\bigcup^{\infty}_{i=1} g (a_i,b_i)\right)$$
$$\leq \sum^{\infty} _{i=1} \lambda(g(a_i,b_i)) \leq \sum^{\infty}_{i=1} |f(c_i) - f(d_i)| < \epsilon$$ 
because $\sum |c_i - d_i| < \delta$. Thus $\lambda(g(E)) = 0$. QED



### Let $f_n(x) = x^n$ for each $n \geq 1$. Prove that the sequence $\{f_n\}$ converges uniformly on $[-\delta,\delta]$ for each $0 < \delta < 1$, and converges non-uniformly on $(-1,1)$.
#### My Solution:
Before we begin, note that if $|x|^n < \epsilon$, then $$\ln(|x|^n) < \ln(\epsilon) \implies n \ln(|x|) < \ln(\epsilon)$$
$$ \implies n < \frac{\ln(\epsilon)}{\ln(|x|)}$$. This will be useful in our proof. 

Let $\delta \in (0,1)$ and $\epsilon > 0$. Also let $N = \frac{\ln(\epsilon)}{\ln(\delta)}$. Hence for $n \geq N$, $n \ln(\delta) \leq \ln(\epsilon)$ which implies that $\ln(\delta^n) \leq \ln(\epsilon)$. The reason that the inequality changes directions here is because for $\delta \in (0,1)$ and for very small $\epsilon$ (specifically less than $1$), $\ln(\delta), \ln(\epsilon) < 0$. Thus, we can see that $\delta^n \leq \epsilon$, which implies that $x^n < \delta^n < \epsilon$ for all $x \in (-\delta, \delta)$. Thus $\{f_n\}$ converges uniformly on $[-\delta,\delta]$. 

If we fix $x \in (-1,1)$, this implies that $x^n < \epsilon$ by our previous point in the proof. However, it is not uniform since $N$ depends on $x$. Thus we have proven the desired result. QED



### Let $m(G)$ denote the Lebesgue measure of the set $G$. Find an open set $G$ which is dense in $[0,1]$ such that $m(G) <1$ and $m(G \cap I) > 0$ for any interval $I \subset [0,1]$.
#### My Solution:
Let $\{q_i\}^{\infty}_{i=1}$ represent the rationals in $\mathbb{Q} \cap [0,1]$. For each $n$ define $I_n$ as an interval containing $q_n$, $m(I_n) < \frac{1}{4\cdot 2^n}$ and $I_n \subset[0,1]$. Let $G = \bigcup^{\infty} _{i=1} I_n$ with $$m(G) = m \left(\bigcup ^{\infty}_{i=1} I_n \right) \leq \sum^{\infty} _{i=1} m(I_n)$$
$$<\sum^{\infty}_{i=1} \frac{1}{4 \cdot 2^n} = \frac{1}{4} \cdot \frac{1}{1-(1/2)} = \frac{1}{2}$$
Since $G$ contains the rationals on $[0,1]$, it is also dense on $[0,1]$. $G$ is open because it is the countable union of open intervals on $[0,1]$. let $I \subset [0,1]$. It must contain a rational, which implies that it intersects any $I_n$ nontrivially, thus $m(I \cap G) > 0$. Thus $G$ is a dense open set on $[0,1]$ such that the measure of $G$ is less than $1$ and intersects any interval of $[0,1]$ nontrivially. QED



### Is $L^p([a,b])$ separable, where $1<p< \infty$?
#### My Solution:
Yes! First note that seperable means that it contains a countable number of dense subsets.

Let $S[a,b] \subset L^p([a,b])$ be step functions on $[a,b]$ and let $S_{\mathbb{Q}}[a,b] \subset S[a,b]$ be step functions of $[a,b]$ with rational endpoints. Since $\mathbb{Q}$ is dense in $\mathbb{R}$, $S_{\mathbb{Q}}[a,b]$ is dense in $S[a,b]$ thus it's dense in $L^p([a,b])$. QED



### Suppose that $1 < p,q < \infty$ and that $\frac{1}{p} + \frac{1}{q} = 1$. Prove that if $f_n \rightarrow f$ in $L^p(\mathbb{R})$ and $g_n \rightarrow g$ in $L^q(\mathbb{R})$, then $f_ng_n \rightarrow fg$ in $L^1 (\mathbb{R})$.
#### My Solution:
Here it is sufficient to show that $\lim_{n \to \infty} ||f_ng_n - fg|| = 0$. Well, 
$$\lim_{n \to \infty} ||f_ng_n - fg||_1 = \lim_{n \to \infty}||f_ng_n - f_ng + f_ng - fg||_1 $$
$$= \lim_{n \to \infty} ||f_ng_n - f_ng||_1 + ||f_ng-fg||_1$$
$$\leq \lim_{n \to \infty} ||f_n||_p \cdot ||g_n - g||_q + ||f_n -f||_p \cdot ||g||_q = 0$$
by Holder's Inequality, where $\lim_{n \to \infty} ||f_n||_p \rightarrow ||f||_p < \infty$, $||g_n-g||_q \rightarrow 0$, and $||f_n -f||_p \rightarrow 0$. Thus  we have proven the desired result. QED



### Let $f \in L^1([0,1])$. Prove that $\lim_{n \to \infty} \int_0 ^1 f(x) \cos(nx) dx = 0$.
#### My Solution:
***Hilbert stuff, not yet completed***



### Assume that $f \in L^{\infty}([0,1])$. Prove that $f \in L^p([0,1])$ for each $1 \leq p < \infty$ and that $||f||_{\infty} = \lim_{p \to \infty} ||f||_p$.
#### My Solution:
To complete this proof, we will divide the problem into a group of lemmas and prove them to get the desired result.

**Lemma 1**: $f \in L^{\infty}([0,1]) \implies f \in L^1([0,1])$
*Proof*: Assume $f \in L^{\infty}$. Then $f \leq m = \mathrm{essup}(f)$ a.e. Then $\int_{[0,1]} |f| \leq \int_{[0,1]} m = m < \infty$. Thus $f \in L^1$.

**Lemma 2**: Assume $f \in L^{\infty}([0,1])$. Then $f \in L^p([0,1])$ for $1 \leq p \leq \infty$.
*Proof*: Consider $\int|f|^p = \int_{\{|f|<1 \}} |f|^p + \int_{\{|f| \geq 1\}} |f|^p$.

- where for $p>1$, $\int_{\{|f| <1\}} |f|^p < \int_{\{|f| <1\}} |f| < \infty$ since $f \in L^1$.

- where $\int_{\{|f| \geq 1\}} |f|^p \leq \int_{\{|f| \geq 1\}} m^p = m^p \cdot m(\{|f| \geq 1\}) < \infty$. Thus $\int |f|^p < \infty$, which implies $f \in L^p$. 

**Lemma 3**: $\lim \sup ||f|| \leq ||f||_{\infty}$
*Proof*: $|f| \leq ||f||_{\infty}$ a.e. This implies that $|f|^p \leq ||f||_{\infty}^p$, which implies $(\int_{[0,1]} |f|^p)^{1/p} \leq (\int_{[0,1]} ||f||^p _{\infty}) ^{1/p} = ||f||_{\infty} < \infty$. Hence $\lim \sup ||f||_p \leq ||f||_{\infty}$.

**Lemma 4**:$||f||_{\infty} \leq \liminf ||f||_p$
*Proof*: Let $t \in [0,m = ||f||_{\infty})$. Then $\int |f| = \int _{\{|f| < t\}} |f| + \int _{\{|f| \geq t \}} |f|$. Then $\int |f|^p \geq \int_{\{|f| < 1\}} |f|^p \geq \int_{\{|t| < 1\}} t^p$. Hence $(\int|f|^p)^{(1/p)} \geq (\int_{\{|f| <t\}} t^p)^{1/p} = t \cdot m(\{|f| < t\})^{1/p}$. This implies that $\liminf ||f||_p \geq \liminf t \cdot m(\{|f| < t\})^{1/p} = t \cdot 1$. Thus $\liminf ||f||_p \geq t$ for all $t \in [0, ||f||_{\infty})$. It follows that by our claims then that \lim \sup||f||_p \leq ||f||_{\infty} \leq \liminf ||f||_p$. Thus we have proven the desired result. QED




## August 2015




### Let $C \subset \mathbb{R}$ denote the Cantor set. Let $\chi_C(x) =1$ if $x \in C$ and $0$ otherwise. Explain why $\chi_C$ is Riemann integrable and compute $\int_0 ^1 \chi_C (x)dx$.
#### My Solution:
Given that $m(C) = 0$, $\chi_C (x) = 0$ a.e. which implies that $\int \chi_C = 0$ and since $\chi_C (x)$ is bounded with $m(\{x | \lim_{x \to a} f(x) \neq f(a)\}) = m(C) = 0$. Thus $Rf = \int f = 0$. QED



### Let $E \subset \mathbb{R}$ be a Lebesgue measurable set with $m(E) =1$. Prove there exists a Lebesgue measurable set $F \subset E$ with $m(F) = \frac{1}{2}$. 
#### My Solution:
$E = \bigcup^{\infty} _{n = 1} E \cap [n, n+1]$. This implies that $m(E) = \lim_{n \to \infty} m(E \cap [-n,n]) = 1$. Pick a sufficiently large $n \in \mathbb{N}$ such that $m(E \cap [-n,n]) > \frac{1}{2}$. Consider $f(x) = \int_{-n} ^x \chi_E$ for $x \in [-n,n]$. Since $f$ is continuous with $f(-n) = 0$ and $f(n) > \frac{1}{2}$, there exists $c \in [-n,n]$ such that $f(c) = \frac{1}{2}$ by the Intermediate Value Theorem. Thus $(-n,n) \cap E$ is a Lebesgue measurable set with $m((-n,c)\cap E) = \frac{1}{2}$. QED



### Let $(X, \mathcal{A}, \mu)$ be a measure space. If $f_n : X \rightarrow \mathbb{R}$ is a sequence of functions such that $\sum^{\infty} _{n=1} \int_X |f_n| d \mu$ converges, then prove that $f_n \to 0$ almost everywhere.
#### My Solution:
$$\sum^{\infty}_{n=1} \int_X |f_n| d \mu = \lim_{k \to \infty} \sum^k _{n=1} \int_X |f_n| d \mu = \lim_{k \to \infty} \int_X \sum^k _{n =1} |f_n| d \mu$$
$$ = \int_X \lim_{k \to \infty} \sum^k _{n=1} |f_n| d \mu = \int_X \sum^{\infty} _{n =1} |f_n| d \mu < \infty$$
by the M.C.T. since $\sum^k _{i=1} |f_n|$ is increasing. Thus $|f_n| \rightarrow 0$ almost everywhere because it's integrable when $n$ approachest $\infty$. Hence $f_n \rightarrow 0$ almost everywhere. QED 



### Prove that $f(x) = 0$ if $x = 0$ and $f(x) = x^2 \cos (\frac{1}{x^2})$ if $x \neq 0$ is continuous but not absolutely continuous on $[-1,1]$. 
#### My Solution:
Consider $x^2 \cos \left(\frac{1}{x^2} \right)$, which is constructed of functions that are continuous everywhere on their domains. So it is continuous on $\mathbb{R}$ excluding $\{0\}$. To show continuity at $x = 0$, consider that $-1 \leq \cos \left(\frac{1}{x^2} \right) \leq 1$ which implies that $-x^2 \leq x^2 \cos \left( \frac{1}{x^2} \right) \leq x^2$ with $\lim_{x \to 0} -x^2 = \lim_{x \to 0} x^2 = 0$ Hence  by the squeeze theorem, $\lim_{x \to 0} x^2 \cos \left( \frac{1}{x^2} \right) = f(0) = 0$. 

Suppose $f$ is absolutely continuous on $[-1,1]$. Hence it is of bounded-variation on $[-1,1]$, thus $V_f [0,1] < \infty$. Consider the partition with endpoints 
$$P = \{-1\} \cup \left[ \{ \pm \sqrt{\frac{1}{n \pi}} : n \in \mathbb{N} \} \cap [-1,1] \right] \cup \{1\}$$
Hence for $x_i, x_{i+1} \in P$,
$$\sum^{\infty} _{n =1} |f(x_i) - f(x_{i+1})| = \sum^{\infty} _{n =1} \left|f \left(\sqrt{\frac{1}{n \pi}} \right) - f \left(\sqrt{\frac{1}{(n+1)\pi}} \right) \right|$$
$$= \sum^{\infty} _{n =1} \left| \left[ \left(\sqrt{\frac{1}{n \pi}} \right)^2 \cdot \cos \left( \frac{1}{\sqrt{\frac{1}{(n+1) \pi}}^2} \right) \right] - \left[ \left( \sqrt{\frac{1}{(n+1) \pi}}\right)^2 \cdot \cos \left( \frac{1}{\sqrt{\frac{1}{(n+1) \pi}}^2}\right) \right]  \right|$$
$$= \sum^{\infty} _{n =1} \left| \left( \frac{1}{n \pi} \cos(n \pi) \right) - \left( \frac{1}{(n+1) \pi} \cos((n+1) \pi) \right) \right| = \sum^{\infty} _{n =1} \left| \frac{1}{n \pi} - \frac{-1}{(n+1) \pi} \right|$$
because $n$ is even and $n+1$ is odd. The above sum is equal to $\frac{1}{\pi} \sum^{\infty} _{n =1} \left| \frac{2n+1}{n^2 +n} \right|$ which diverges because it's a harmonic series. Thus $V_f[0,1] \nless \infty$. This is a contradiction to the assumption of $f$ being absolutely continuous, thus we have proven the desired result. QED



### Let $(X, \mathcal{A}, \mu)$ be a finite measure space. If $f$ is $\mu$-measurable and $p \leq f(x) \leq q$ for all $x \in X$, then prove that $\int_X f d \mu$ exists and $p \mu(X) \leq \int_X f d \mu \leq q \mu (X)$. 
#### My Solution:
Since $X$ is finite, and $p \leq f \leq q$, $\mu (X) = \int_X 1 d \mu$. This implies that $p \cdot \mu (X) \leq \int_X f d \mu \leq q \mu(X)$. 

Now, we must show that $\int_X f d \mu$ is integrable. Consider $|f| \leq \mathrm{max} \{|p|,|q|\} = M$. Hence $|f| \leq M$. This implies that $\int_X |f| d \mu \leq \mu (X) \cdot M < \infty$. Hence $f$ is integrable. QED



### Suppose that $1< q,p < \infty$ and that $\frac{1}{p} + \frac{1}{q} = 1$. Prove that if $f_n \rightarrow f$ in $L^p(\mathbb{R})$ and $g_n \rightarrow g$ in $L^q(\mathbb{R})$, then $f_ng_n \rightarrow fg$ in $L^1(\mathbb{R})$. 
#### My Solution:
It is sufficient to show that the $\lim_{n \to \infty} ||f_ng_n - fg||_1 = 0$. Well,
$$\lim_{n \to \infty} ||f_n g_n -fg||_1 = \lim_{n \to \infty}||f_ng_n - f_ng||_1 + ||f_ng -fg||_1$$
$$ \leq \lim_{n \to \infty} ||f_n||_p||g_n-g||_q + ||g||_q||f_n-f||_p$$
by Holder's Inequality where $\lim_{n \to \infty} ||f_n||_p \rightarrow ||f||_p < \infty$. Thus $||g_n - g||_q \rightarrow 0$ and $||f_n - f||_p \rightarrow 0$. So the above limit does in fact imply that $f_ng_n \rightarrow fg$ in $L^1(\mathbb{R})$. QED



### Evaluate $\frac{d}{dt} \int_0 ^1 \frac{\sin(xt)}{x}dx$. Justify your computations.
#### My Solution:
***Not yet completed***



### If $f \in L^1(\mathbb{R}) \cap L^{\infty}(\mathbb{R})$ and $p \geq 1$, then prove that $f \in L^p(\mathbb{R})$. 
#### My Solution:
Given $f \in L^1(\mathbb{R}) \cap L^{\infty}(\mathbb{R})$. This implies that $m = \mathrm{essup}(f) < \infty$ and $\int|f| < \infty$. So,
$$\int|f|^p = \int_{\{x:|f|<1\}} |f|^p + \int_{\{x: |f| >1\}}|f|^p$$
For $p>0$, $\int_{\{x:|f(x)<1\}}|f|^p < \int_{\{x:|f(x)<1\}}|f|$. Thus
$$\int_{\{x:|f|<1\}} |f|^p + \int_{\{x: |f| >1\}}|f|^p \leq \int_{\{x:|f|<1\}} |f| + \int_{\{x: |f| >1\}} m^p$$
where $\int_{\{x:|f|<1\}} |f| < \infty$ and $\int_{\{x: |f| >1\}} m^p = m^p \cdot m(\{x:|f(x) > 1\}) < \infty$ thus the entire equation is less than $\infty$. So $(\int|f|^p)^{1/p} < \infty$ for all $p$. Thus $f \in L^p$. QED



### If $f:\mathbb{R} \rightarrow [0,\infty)$ is measurable, then $\lim_{n \rightarrow \infty} \int_{-n} ^n f = \int_{\mathbb{R}} f$. 
#### My Solution:
Since $f$ is positive, $f \cdot \chi_{[-n,n]}$ is a sequence of increasing positive functions. Thus 
$$\lim_{n \to \infty} \int f \cdot \chi_{[-n,n]} = \int \lim_{n \to \infty} f \cdot \chi_{[-n,n]} = \int_{\mathbb{R}} f$$ with the step of moving the limit inside the integral is by the Monotone Convergence Theorem. QED





## January 2013





### Show that every dense subset of $L^{\infty}([0,1])$ is uncountable.
#### My Solution:
Let $A = \{ \chi_{(0,t)} : t \in (0,1)\}$. Then for any $\chi_{(0,t_1)}, \chi_{(0,t_2)} \in A$ such that $t_1 \neq t_2$. So,
$$||\chi_{(0,t_1)} - \chi_{(0,t_2)}||_{\infty} = 1$$
Without loss of generality, $t_1 < t_2$, then $\chi_{(0,t_1)} - \chi_{(0,t_2)} = 0,1,0$ on $(0,t_1),(t_1,t_2),(t_2,1)$ respectively. This is where we get the above equality, as 
$$\left\|\chi_{(0,t_2)} - \chi_{(0,t_1)}\right\|_\infty = \sup_{x\in[0,1]}\left|\chi_{(0,t_2)}(x) - \chi_{(0,t_1)}(x)\right| = 1$$

Consider $\left\{ B_{\left(\chi_{(0,t)}, \frac{1}{3} \right)} \right\}$ which is an uncountable collection of disjoing balls. And given any dense set $S \subset L^{\infty}([0,1])$ has elements in each ball by definition of density. Thus $S$ is uncountable. QED



### Let $f$ be a Lebesgue measurable function on $\mathbb{R}$ with the property that $\sup_{\{g \in L^2(\mathbb{R}):||g||_2 \leq 1\}}\int_{\mathbb{R}}|fg|d \lambda \leq 1$. Prove that $f \in L^2(\mathbb{R})$ and $||f||_2 \leq 1$.
#### My Solution:
For every $n \in \mathbb{N}$, let 
$$A_n = \{ x \in [-n,n]: |f(x)| \leq n\}$$
and let $f_n = f \chi_{A_n}$. Also define the linear functional $T_n:L^2 \rightarrow \mathbb{R}$ such that 
$$T_n(g) = \int_{\mathbb{R}}f_ng$$
Clearly $T_n$ is a bounded functional in $L^2$, since, by Holder's inequality,
$$|T_n(g)| \leq \int_{\mathbb{R}} |f_ng| \leq ||f_n||_2||g||_2$$
Since
$$|T_n(f_n)| = \left| \int_{\mathbb{R}} f^2 \chi_{A_n} \right| = \int_{\mathbb{R}} f_n ^2 = ||f_n||_2 ^2$$
we can thus conclude that $||T_n|| = ||f_n||_2$. Moreover, $|f_ng|$ increases to $|fg|$ as $n \to \infty$. So
$$\sup_n |T_n(g)| \leq \int_{\mathbb{R}} |fg| < \infty$$
By the uniform boundedness principle, we can conclude that the sequence $(T_n)$ converges to a bounded linear functional $T$ and that
$$||T|| \leq \liminf_n ||T_n|| < \infty$$
On the other hand, by the monotone convergence theorem,
$$\liminf_n ||T_n|| = \liminf_n ||f_n||_2 = \left(\int_{\mathbb{R}} |f|^2 \right)^{1/2}$$
hence $f \in L^2$. Finally, taking $g = \frac{f}{||f||_2}$ in the assumption, we find that
$$\int_{\mathbb{R}} |fg| = ||f||_2 \leq 1$$
Thus we have proven the desired result. QED



### Let $f \geq 0$ and $f \in L^p[0,1]$ for all $p \in [1, \infty)$. If $||f||_p ^p = ||f||_1$ for all $p \in [1, \infty)$, then there is a set $S$ such that $f = \chi_S$ a.e.
#### My Solution:
We know $||f||_1 = \int |f|^p$ for all $p \in [1, \infty)$. Suppose $m(\{x|f > 1\}) \neq 0$. Pick $\epsilon \in (1, \infty)$ such that $1 < \epsilon \leq f < \infty$. Then $$||f||_1 = \int|f|^p \geq \int_{\{1 < |f|\}} |f|^p \geq \int \epsilon ^p \rightarrow \infty$$
since $\epsilon > 1$. 

Cosider $m(\{x | 0 < f<1\})$, which we claim is equal to zero. To prove this, pick $0< |f| \leq \epsilon < 1$. Then 
$$||f||_1 = \int|f|^p \leq \int_{\{0 < |f| \leq \epsilon < 1\}} \epsilon^p \to 0$$ as $p \to \infty$. Hence $f = 0$ or $1$ almost everywhere. If we use this to define $S = \{x| f(x) =1\}$, then $f = \chi_S$ almost everywhere. QED



### If $E$ is a measurable subset of $\mathbb{R}$, then there is an interval $I$ such that $m(E \cap I) > \frac{9}{10} m(I)$ or $m(E^c \cap I) > \frac{9}{10} m (I)$.
#### My Solution:
Suppose not! Then for all $I$, $m(E \cap I) \leq \frac{9}{10} \chi(I)$ and $m(E^c \cap I) \leq \frac{9}{10} \chi(I)$. Suppose $E$ has finite measure and let $E \subset \bigcup^{\infty}_{n=1} I_n$. Then
$$m(E) = m \left(E \cap \bigcup^{\infty}_{n=1} I_n \right) = m\left(\bigcup^{\infty}_{n=1} E \cap I_n \right) \leq m(E \cap I_n) \leq \frac{9}{10} \sum^{\infty} _{n =1} m (I_n)$$
Thus for all covers of $E$, $m(E) \leq \frac{9}{10} \sum^{\infty} _{n =1} m(I_n)$. But, by definition 
$$m(E) = \inf \{m(I_n) : E \subset \bigcup^{\infty}_{n=1} I_n\}$$
Hence 
$$m(E) \leq \frac{9}{10} m(E) \implies m(E) = 0$$
Now for $E$ with any measure, 
$$m(E \cap(-n,n) \cap I_n) \leq m(E \cap I) \leq \frac{9}{n}m(I_n)$$
Hence $m(E \cap (-n,n)) = 0$ for all $n$ where 
$$m(E) = m \left(\bigcup^{\infty}_{n=1} (E \cap(-n,n)) \right) \leq \sum^{\infty}_{n=1} m(E \cap (-n,n)) = 0$$
Note the same proof works for $m(E^c) = 0$. Thus the desired result is proven. QED



### A measure space $(X, \mu)$ is $\sigma$-finite iff there is an $f : X \rightarrow (0, \infty)$ such that $f \in L^1 (X, \mu)$. 
#### My Solution:
Assume that $f : X \rightarrow (0, \infty)$ such that $f \in L^1 (X, \mu)$. Then
$$X = \{f> 0\} = \bigcup^{\infty}_{n =1} \left\{f > \frac{1}{n} \right\}$$
where 
$$\mu \left(\left\{f > \frac{1}{n}\right\} \right) \leq \int \frac{|f|}{\frac{1}{(1/n)}}d \mu \leq n \cdot \int|f| < \infty$$
since $f \in L^1$ and by Chebyshev's Inequality.

Now assume $X$ is $\sigma$-finite. We have $X = \bigcup^{\infty}_{i = 1} A_n$, a union of disjoint sets wuth $\mu (A_n < \infty)$. Define $f = \sum^{\infty} _{n=1} a_n$ where $a_n = \frac{1}{\mu (A_n) \cdot n^2} \cdot \chi_{A_n}$ when $\mu(A_n) > 0$ and $a_n = \frac{1}{n^2} \chi_{A_n}$ when $\mu(A_n) = 0$. Then
$$\int f = \sum^{\infty}_{n=1} \int \frac{1}{\mu(A_n) \cdot n^2} \cdot \chi_{A_n} = \sum^{\infty}_{n=1} \frac{1}{\mu(A_n) \cdot n^2} \int \chi_{A_n} = \sum^{\infty}_{n=1} \frac{1}{n^2} < \infty$$
Thus proving the desired result. QED



### (a) Find a sequence $f_n: [0,1] \rightarrow \mathbb{R}$ such that $\int_0 ^1 |f_n(x)| = 2$ for all $n \in \mathbb{N}$ and $\lim_{n \to \infty} f_n(x) = 1$ for all $x \in [0,1]$. (b) If the $f_n$ are as in part (a), then prove $\lim_{n \to \infty} \int_0 ^1 |f_n(x) -1| dx = 1$. 
#### My Solution:
(a)
$f_n(x):=4n^2x+1 \text{ for }x\in \left[0,\frac{1}{2n}\right]\\
f_n(x):=-4n^2x+1+4n \text{ for }x\in \left[\frac{1}{2n},\frac{1}{n}\right]\text{and }f(x)=1\text{ otherwise}.$

(b)
Given $f_n$ as defined above, we can simply integrate to get this answer. So, given $f_n$ defined as in part (a), $$f_n(x) -1 =4n^2x \text{ for }x\in \left[0,\frac{1}{2n}\right]\\
f_n(x)-1=-4n^2x+4n \text{ for }x\in \left[\frac{1}{2n},\frac{1}{n}\right]\text{and }f(x)=0\text{ otherwise}.$$
Thus 
$$\lim_{n \to \infty} \int_0 ^1 |f_n -1| dx = \lim_{n \to \infty} \left[ \int_0 ^{1/2n} 4n^2x dx + \int_{1/2n} ^ {1/n} (-4n^2x+4n)dx \right]\\
= \lim_{n \to \infty} \left[ \frac{2n^2}{4n^2} -0 - \frac{2n^2}{n^2} + \frac{4n}{n} + \frac{2n^2}{4n^2} - \frac{4n}{2n} \right] = \lim_{n \to \infty} 1 = 1$$ QED




### Show that $\mathcal{G} = \{f \in C[0,1] : \int_0 ^1 f^2 > 1\}$ is open in $C[0,1]$. (Assume $C[0,1]$ has the uniform metric.)
#### My Solution:
The function $\phi(f) = \int_0 ^1 f^2$ is continuous. Thus $\phi ^{-1} ((1, \infty))$ must be open. QED



### Let $(X, \rho)$ be a metric space and suppose $K$ and $F$ are nonempty disjoint subsets of $X$ with $K$ compact and $F$ closed. (a) Prove there is a $\delta >0$ such that $\rho(x,y) \geq \delta$ for all $x \in K$ and $y \in F$. (b) Show that part (a) may fail if $K$ is closed, but not compact. 
#### My Solution:
***Not yest solved***



### The limit superior of a sequence of sets $\{E_k\}$ is defined as $\lim \sup E_k = \bigcap^{\infty}_{j=1} \bigcup^{\infty}_{k=j} E_k$. Let $\{E_k: k \in \mathbb{N}\}$ be a sequence of sets in $\mathcal{L}$. (a) Prove that if $\sum_{k \in \mathbb{N}} \lambda(E_k) < \infty$, then $\lambda(\lim \sup(E_k)) = 0$. (b) Is it true in general that $\lambda(\lim \sup(E_k)) = \lim \sup \lambda(E_k)$?
#### My Solution:
(a):
Let $\epsilon > 0$. Given $\sum^{\infty}_{k=1} m(E_k) < \infty$, there exists $N$ such that $\sum^{\infty}_{k=N} m(E_k) < \epsilon$.
$$\lim \sup(E_k) = \bigcap^{\infty}_{n=1} \bigcup^{\infty}_{k=n} E_k \subset \bigcup^{\infty} _{k=N} E_k$$
Hence $$m(\lim \sup(E_k)) \leq m\left( \bigcup^{\infty}_{k=N} E_k \right) \leq \sum^{\infty}_{k=N} m(E_k) < \epsilon$$
which implies that $m(\lim \sup(E_k)) = 0$. QED

(b):
Consider the sequence of functions: $E_1 = [0,1], E_2 = [0,\frac{1}{2}], E_3 = [\frac{1}{2},1],E_4 = [0,\frac{1}{4}], E_5 = [\frac{1}{4},\frac{1}{2}], E_6 = [\frac{1}{2},\frac{3}{4}], E_7 = [\frac{3}{4},1]$, and so on. Then $\lim_{n \to \infty} m(E_k) = 0$ but for all $n \in \mathbb{N}$, $\bigcup^{\infty}_{k=n} E_k = [0,1]$. This implies that $\limsup(E_n) = [0,1]$. Thus it may not be true  that $\lambda(\lim \sup(E_k)) = \lim \sup \lambda(E_k)$. QED



### Show that $f(x) = x^2 \sin\left( \frac{1}{x} \right)$ where $x \neq 0$ and $f(x) = 0$ where $x = 0$ is in $BV[-1,1]$, but $g(x) = x^2 \sin \left( \frac{1}{x^2} \right)$ where $x \neq 0$ and $g(x) = 0$ where $x = 0$ is not. 
#### My Solution:
***Not yest solved***

















# Extra Problems













# Important Notes
## Undergrad

For reference, these notes are gathered from the book *Real Analysis; A First Course* by Russell A. Gordon. These notes consist of basic real analysis ideas based off of my past undergraduate class taught by Dr. Christine Leverenz at Georgetown College.

### Gordon Chapter 1 (Real Numbers)

- A **field** is a nonempty set $F$ of objects that has two operations defined on it. These operations are usually defined as addition and multiplication. These operations follow a set of properties which will not be listed here as you should know them.

- **Triangle Inequality**: $|a+b| \leq |a|+|b|$. It follows from this that $||a|-|b|| \leq |a-b|$

- If $a \neq 0$ and $r \neq 1$ are real numbers, then 
$$a+ar+ar^2+ar^3+...+ar^n = a \cdot \frac{1-r^{n+1}}{1-r}$$

- **Cauchy-Schwarz Inequality**: Let $n$ be a positive integer. If $a_1,a_2,...,a_n$ and $b_1,b_2,...,b_n$ are real numbers, then
$$\left( \sum^n_{k=1} a_k b_k \right)^2 \leq \left(\sum^n_{k=1} a_k^2 \right) \left( \sum^n_{k=1} b_k^2 \right)$$
Equality occurs iff there is a constant $c$ such that $a_k = cb_k$ for all integers $k$

- The set $S$ is **bounded** if there is a number $M$ such that $|x| \leq M$ for all $x \in S$. The number $M$ is called a **bound** for S.

- Suppose that $S$ is bounded above. A number $\beta$ is the **supremum** of $S$ if $\beta$ is an upper bound of $S$ and any number less than $\beta$ is not an upper bound of $S$. We write $\beta = \sup (S)$

- Suppose that $S$ is bounded below. A number $\alpha$ is the **infimum** of $S$ if $\alpha$ is an lower bound of $S$ and any number greater than $\alpha$ is not an lower bound of $S$. We write $\alpha = \inf (S)$

- **Archimedean Property of the Real Numbers**: If $a$ and $b$ are positive real numbers, then there exists a positive integer $n$ such that $na > b$.

- Between any two distinct real numbers, there exists a rational and an irrational number.

- A countable union of countable sets is countable. 

- Let $I$ be an interval and $f$ be a function such that $f:I \to \mathbb{R}$, and let $J$ be a subinterval of $I$. The function $f$ is **increasing** on $J$ if $f(x) \leq f(y)$ for all $x,y \in J$ such that $x<y$; and **strictly increasing** on $J$ if $f(x) < f(y)$ for all $x,y \in J$ such that $x < y$. The function $f$ is **decreasing** on $J$ if $f(x) \geq f(y)$ for all $x,y \in J$ that satisfy $x<y$; and **strictly decreasing** on $J$ if $f(x) > f(y)$ for all $x,y \in J$ such that $x<y$. The function $f$ is **monotone** on $J$ if it is either increasing or decreasing on $J$ and **strictly monotone** on $J$ if it is either strictly increasing or decreasing on $J$.


### Gordon Chapter 2 (Sequences)

- A **sequence** is a function whose domain is the set of positive integers. A **sequence of real numbers** is a sequence whose codomain is the set $\mathbb{R}$. Although a sequence is a function, the standard notation for a sequence of real numbers is $\{x_n\}$ where the subscript $n$ denotes the **index** of the sequence.

- A sequence $\{x_n\}$ **converges to a number** $L$ if for all $\epsilon>0$ there exists a positive integer $N$ such that $|x_n - L| < \epsilon$ for all $n \geq N$. The sequence is **convergent** if there exists a number $L$ that the sequence converges to, otherwise it is **divergent**.

- The limit of a convergent sequence is unique.

- Suppose that $\{a_n\}$ converges to $a$ and $\{b_n\}$ converges to $b$. Then:

--- $\{ca_n\} \to ca$

--- $\{a_n \pm b_n\} \to a \pm b$

--- $\{a_n b_n\} \to ab$

- A monotone sequence converges iff it is bounded

- A sequence $\{x_n\}$ is a **Cauchy Sequence** if for all $\epsilon > 0$ there exists a positive integer $N$ such that $|x_m - x_n| < \epsilon$ for all $m,n \geq N$.

- A sequence of real numbers converges iff it is a Cauchy sequence

- Let $\{x_n\}$ be a sequence and let $\{p_n\}$ be a strictly increasing sequence of positive integers. The sequence $\{x_{p_n}\}$ is called a **subsequence** of $\{x_n\}$

- If a sequence $\{x_n\}$ converges to $L$, then every subsequence must converge to $L$ as well. 

- **Bolzano-Weierstrass Theorem**: Every bounded sequence has a convergent subsequence. 


### Gordon Chapter 3 (Limits and Continuity)

- Let $I$ be an open interval that contains the point $c$ and suppose that $f$ is a function that is defined on $I$ except possibly at $c$. The function $f$ has **limit** $L$ at point $c$ if for all $\epsilon > 0$ there exists $\delta > 0$ such that $|f(x)-L| < \epsilon$ for all $x \in I$ such that $|x-c| < \delta$. We then write $\lim_{x \to c} f(x) = L$.

- We have linearity for limits.

- Let $I$ be an interval and $f:I \to \mathbb{R}$, and let $c \in I$. The function $f$ is **continuous** at $c$ if for each $\epsilon > 0$ there exists a $\delta > 0$ such that $|f(x) - f(c)| < \epsilon$ for all $x \in I$ such that $|x-c| < \delta$. The function is continuous on $I$ if $f$ is continuous on every point of $I$.

- **Intermediate Value Theorem**: Suppose that $f:[a,b] \to \mathbb{R}$ is continuous on $[a,b]$. If $v$ is a number between $f(a)$ and $f(b)$, then there is a point $c \in (a,b)$ such that $f(c) = v$.

- **Extreme Value Theorem**: If $f:[a,b] \to \mathbb{R}$ is continuous on $[a,b]$, then there exist points $c$ and $d$ in $[a,b]$ such that $f(c) \leq f(x) \leq f(d)$ for all $x \in [a,b]$.

- Let $I$ be an interval. A function $f:I \to \mathbb{R}$ is **uniformly continuous** on $I$ if for each $\epsilon > 0$ there exists a $\delta > 0$ such that $|f(y) - f(x)| < \epsilon$ for all $x,y \in I$ such that $|y-x| < \delta$.

- If $f:[a,b] \to \mathbb{R}$ is continuous on $[a,b]$, then $f$ is uniformly continuous on $[a,b]$.

- A **partition** $P$ of an interval $[c,d]$ is a finite set of points $\{x_i|0 \leq i \leq n\}$ such that 
$$c=x_0 < x_1 < x_2 < ... < x_{n-1} < x_n = d$$

- Let $f: [a,b] \to \mathbb{R}$ be a function and let $[c,d]$ be any closed subinterval of $[a,b]$. The **variation** of $f$ on $[c,d]$ is defined by $V(f,[c,d]) = \sup \{\sum^n _{i=1}|f(x_i)-f(x_{i-1})|\}$. Note that the integer $n$ is not fixed; the supremum is over all possible partitions of $[c,d]$. The function $f$ is of **bounded variation** on $[c,d]$ if $V(f,[c,d])$ is finite.


### Gordon Chapter 4 (Differentiation)

- Let $I$ be an interval, let $f: I \to \mathbb{R}$, and let $c \in I$. The function $f$ id **differentiable** at $c$ provided that the limit 
$$\lim_{v \to c} \frac{f(v) - f(c)}{v-c}$$ exists. The **derivative** of $f$ at $c$ is the value of the prementioned limit denoted by $f'(c)$.

- **Rolle's Theorem**: Let $f:[a,b] \to \mathbb{R}$ be continuous on $[a,b]$ and differentiable on $(a,b)$. If $f(a) = f(b)$, then there exists a point $c \in (a,b)$ such that $f'(c) = 0$.

- **Mean Value Theorem**: If $f:[a,b] \to \mathbb{R}$ is continuous on $[a,b]$ and differentiable on $(a,b)$, then there exists a point $c \in (a,b)$ such that 
$$f'(c) = \frac{f(b)-f(a)}{b-a}$$


### Gordon Chapter 5 (Integration)

- A **tagged partition** $^t P$ of an interval $[a,b]$ consists of a partition $P = \{x_i | 0 \leq i \leq n\}$ of $[a,b]$ along with a set $\{t_i | 1 \leq i \leq n\}$ of points, known as **tags**, that satisfy $x_{i-1} \leq t_i \leq x_i$ for $1 \leq i \leq n$.

- Let $f:[a,b] \to \mathbb{R}$ and let $^t P = \{(t_i, [x_{i-1},x_i])|1 \leq i \leq n \}$ be a tagged partition of $[a,b]$. The **Riemann sum** $S(f, ^t P)$ of $f$ associated with $^t P$ is defined by 
$$S(f, ^t P) = \sum_{i=1} ^n f(t_i)(x_i - x_{i-1})$$

- A function $f:[a,b] \to \mathbb{R}$ is **Riemann integrable** on $[a,b]$ if there exists a number $L$ with the following property: for all $\epsilon >0$ there exists $\delta > 0$ such that $|S(f, ^t P) - L| < \epsilon$ for all tagged partitions $^t P$ of $[a,b]$ that satisfy $||^t P|| < \delta$. The number $L$ is called the **Riemann integral** of $f$ on $[a,b]$.

- **Cauchy Criterion for Riemann Integrability**: A bounded function $f$ is Riemann integrable on $[a,b]$ iff for each $\epsilon > 0$ there exists $\delta > 0$ such that $|S(f,^t P_1)-S(f, ^t P_2)| < \epsilon$ for all tagged partitions $^t P_1$ and $^t P_2$ of $[a,b]$ with norms less than $\delta$.

- Fundamental Theorem of Calculus is a thing

- **Integration by Parts**: 
$$\int_a ^b f'g = f(b)g(b) - f(a)g(a) - \int_a ^b g'f$$


### Gordon Chapter 6 (Infinite Series)

- A **power series** is an expression of the form 
$$a_0 + a_1 x + a_2 x^2 + a_3 x^3 + ...$$
where the $a_k$'s are constants

- A **Fourier series** is an expression of the form
$$a_0 + a_1 \cos (x) + b_1 \sin (x) + a_2 \cos (2x) + b_2 \sin (2x) + ...$$
where the $a_k$'s and $b_k$'s are constants

- An **infinite series** of real numbers is an expression of the form
$$ \sum^{\infty} _{k=1} a_k = a_1 + a_2 + ...$$

- A **partial sum** of an infinite series is represented by $\sum_{k=1} ^n a_k$

- An infinite series **converges** if its corresponding sequence $\{s_n\}$ of partial sums converges. If $S$ is the limit of the previous sequence, then we say the series converges to $S$. If the sequence does not converge, we say that the series **diverges**.

- If the series $\sum^{\infty}_{k=1} a_k$ converges, then the sequence $\{a_k\}$ converges to zero.

- The series $\sum^{\infty}_{k=1} a_k$ converges iff for all $\epsilon > 0$ there exists a positive integer $N$ such that $|\sum^n_{k=m+1} a_k| < \epsilon$ for all positive integers $m$ and $n$ that satisfy $n > m \geq N$

- A series with nonnegative terms converges iff its sequence of partial sums is bounded

- Linearity is preserved

- **Geometric Series**: Suppose that $a \neq 0$. The geometric series $\sum^{\infty}_{k=0} ar^k$ converges if $|r| < 1$ and diverges if $|r| \geq 1$. If $|r| < 1$, 
$$\sum^{\infty}_{k=0} ar^k = \frac{a}{1-r}$$

- The $p$-series $\sum^{\infty}_{k=1} \frac{1}{k^p}$ converges if $p > 1$ and diverges if $p \leq 1$.

- Let $\sum^{\infty}_{k=1} a_k$ be a series of real numbers. If ther series $\sum^{\infty}_{k=1} |a_k|$ converges, then so does $\sum^{\infty}_{k=1} a_k$.

- Rearrangement stuff is cool, but unnecessary for this study guide.


### Gordon Chapter 7 (Sequences and Series of Functions)

- Let $\{f_n\}$ be a sequence of functions defined on an interval $I$ and let $f$ be a function defined on $I$. The sequence $\{f_n\}$ **converges pointwise** to $f$ on $I$ if the sequence $\{f_n(x)\}$ converges to $f(x)$ for each $x \in I$. In other words, $f(x) = \lim_{n \to \infty} f_n(x)$ for all $x \in I$.

- Let $\{f_k\}$ be a sequence of functions defined on an interval $I$ and let $f$ be a function defined on $I$. The series $\sum^{\infty}_{k=1} f_k$ **converges pointwise** to $f$ on $I$ if the sequence $\{s_n\} = \{\sum^n_{k=1} f_k\}$ of partial sums converges pointwise to $f$ on $I$.

- Let $\{f_n\}$ be a sequence of functions defined on an interval $I$ and let $f$ be a function defined on $I$. The sequence $\{f_n\}$ **converges uniformly** to $f$ on $I$ if for all $\epsilon > 0$ there exists a positive integer $N$ such that $|f_n(x) - f(x)| < \epsilon$ for all $x \in I$ and for all $n \geq N$. 

- A lot more information is here, may add later. I just don't think it will help much for the Qual


### Gordon Chapter 8 (Point-Set Topology)

- A point $x$ is an **interior point** of $E$ if there exists a positive number $r$ such that $(x-r,x+r) \subseteq E$

- A point $x$ is an **isolated point** of $E$ if there exists a positive number $r$ such that $(x-r,x+r) \cap E = \{x\}$

- A point $x$ is a **limit point** of $E$ if for each positive number $r$, the set $(x-r,x+r) \cap E$ contains a point of $E$ other than $x$

- The set $E$ is **open** if all of its points are interior points

- The set $E$ is **closed** if it contains all of its limit points

- Every open interval is an open set and every closed interval is a closed set

- Let $E$ be a set of real numbers. A collection $\mathcal{G}$ of sets is an **open cover** of $E$ if each set in $\mathcal{G}$ is open and $E$ is contained in the union of all the sets in $\mathcal{G}$. The open cover $\mathcal{G}$ has a **finite subcover** if $E$ is contained in the union of a finite number of sets in $\mathcal{G}$

- A set $E$ is **compact** if every open cover of $E$ has a finite subcover

- A compact set is closed and bounded

- A closed subset of a compact set is compact

- A set of real numbers is compact iff it is closed and bounded

- More is in this section. Possibly going to add more, but I don't find it necessary for the Qual.









## Graduate Notes/Royden Book

### Royden Chapter 1 (Sets, Sequences, and Functions)
- A nonepmty set $E$ of real numbers is said to be **bounded above** provided that there is a real number $b$ such that $x \leq b$ for all $x \in E$. $b$ is known as an upper bound for $E$. We define bounded below similarly.

- **The Completeness Axiom**: Let $E$ be a nonempty set of real numbers that is bounded above. Then among the set of upper bounds for $E$ there is a smallest, or least, upper bound.

- The least upper bound of $E$ is called the **supremum** of $E$ and denoted by $\mathrm{sup}E$. We define the **infimum** similarly as the greatest lower bound and denote it by $\mathrm{inf}E$.

- **Triangle Inequality**: 
$$|a+b| \leq |a| + |b|$$

- A set $E$ of real numbers is said to be **inductive** provided it contains $1$ and if the number $x \in E$, the number $x+1 \in E$ as well.

- Every nonempty set of natural numbers has a smallest member.

- **Archimedean Property**: For each pair of positive real numbers $a$ and $b$, there is a natural number $n$ for which $na > b$.

- A set $E$ of real numbers is said to be **dense** in $\mathbb{R}$ provided between any two real numbers there lies a member of $E$.

- The rational numbers are dense in $\mathbb{R}$.

- A set $E$ is said to be **finite** provided either it is empty or there is a natural number $n$ such that $E$ is equipotent to $\{1,2,3,...,n\}$. 

- We say that $E$ is **countably infinite** provided $E$ is equipotent to the set $\mathbb{N}$ (the natural numbers). A set that is either finite or countably finite is said to be **countable**. A set that is not countable is **uncountable**.

- A subset of a countable set is countable.

- A nonempty set is countable iff it is the image of a function whose domain is a nonempty countable set.

- The union of countable sets is countable.

- A set $\mathcal{O}$ of real numbers is called **open** provided for each $x \in \mathcal{O}$, there is a $r > 0$ for which the interval $(x-r, x+r)$ is contained in $\mathcal{O}$.

- The set of real numbers and the empty set are open; the intersection of any finite collection of open sets is open; and the union of any collection of open sets is open.

- Every nonempty open set is the disjoint union of a countable collection of open intervals.

- For a set $E$ of real numbers, a real number $x$ is called a **point of closure** of $E$ provided every open interval that contains $x$ also contains a point in $E$. The collection of points of closure of $E$ is called the **closure** of $E$.

- A set of real numbers is open iff its complement in $\mathbb{R}$ is closed.

- A collection of sets $\{E_{\lambda}\}_{\lambda \in \Lambda}$ is said to be a **cover** of a set $E$ provided $E \subseteq \cup_{\lambda \in \Lambda} E_{\lambda}$. By a subcover of a cover of $E$ we mean a subcollection of the cover that itself also is a cover of $E$. If each set $E_{\lambda}$ in a cover is open, then we call $\{E_{\lambda}\}_{\lambda \in \Lambda}$ an **open cover** of $E$. If the cover $\{E_{\lambda}\}_{\lambda \in \Lambda}$ contains only a finite number of sets, we call it a **finite cover**. 

- Let $F$ be a closed and bounded set of real numbers. THen every open cover of $F$ has a finite subcover.

- We say that a countable collection of sets $\{E_n\}^{\infty}_{n=1}$ is **descending** or **nested** provided that $E_{n+1} \subseteq E_n$ for every natural number $n$. It is said to be **ascending** provided $E_n \subseteq E_{n+1}$ for every natural number $n$.

- **$\sigma$-algebra**: Given a set $x$, a collection $\mathcal{A}$ of subsets of $X$ is called a $\sigma$-algebra provided

-- the empty set belongs to $\mathcal{A}$

-- the complement in $X$ of a set in $\mathcal{A}$ also belongs to $\mathcal{A}$

-- the union of a countable collection of sets in $\mathcal{A}$ also belongs to $\mathcal{A}$.

- Let $\mathcal{F}$ be a collection of subsets of a set $X$. Then the intersection $\mathcal{A}$ of all $\sigma$-algebras of subsets of $X$ that contain $\mathcal{F}$ is a $\sigma$-algebra that contains $\mathcal{F}$. Moreover, it is the smallest $\sigma$-algebra of subsets $X$ that contains $\mathcal{F}$ in the sense that any $\sigma$-algebra that contains $\mathcal{F}$ also contains $\mathcal{A}$.

- The collection $\mathcal{B}$ of Borel sets of real numbers is the smallest $\sigma$-algebra of sets of real numbers that contains all of the open sets of real numbers. (every open set is a Borel set)


### Royden Chapter 2 (Lebesgue Measure)

- **The measure of an interval is its length**. Each nonempty interval $I$ is Lebesgue measurable and $$m(I) = l(I)$$

- **Measure is translation invariant**. If $E$ is Lebesgue measurable and $y$ is any number, then the translate of $E$ by $y$, $E+y = \{x+y|x \in E\}$, also is Lebesgue measurable and $$m(E+y) = m(E)$$

- **Measure is countably additive over countable disjoint unions of sets**. If $\{E_k\}^{\infty}_{k=1}$ is a countable disjoint collection of Lebesgue measurable sets, then 
$$m \left(\bigcup_{k=1}^{\infty}E_k \right) = \sum_{k=1}^{\infty} m(E_k)$$

- The **outer measure** of an interval is its length, it is translation invariant, however the outer measure is not finitely additive. Instead:
$$m^* \left(\bigcup_{k=1}^{\infty}E_k \right) \leq \sum_{k=1}^{\infty} m^*(E_k)$$

- Let $I$ be a nonempty interval of real numbers. For a set $A$ of real numbers, consider the countable collections $\{I_k\}^{\infty}_{k=1}$ of nonempty open, bounded intervals that cover $A$, that is, collections for which $A \subseteq \bigcup_{k=1}^{\infty}I_k$. We define the **outer measure** of $A$, $m^*(A)$, to be
$$m^*(A) = \mathrm{inf}\{\sum_{k=1}^{\infty}l(I_k) | A \subseteq \bigcup_{k=1}^{\infty}I_k\}$$

- A measure is **monotone** if for all $A \subseteq B$, then $m^*(A) \leq m^*(B)$.

- A set $E$ is said to be **measurable** provided for any set $A$ that
$$m^*(A) = m^*(A \cap E) + m^*(A \cap E^C)$$

- Any set of outer measure zero is measurable. In particular, any countable set is measurable.

- The union of a finite collection of measurable sets is measurable.

- The union of a countable collection of measurable sets is measurable.

- Every interval is measurable.

- The collection $\mathcal{M}$ of measurable sets is a $\sigma$-algebra that contains the $\sigma$-algebra $\mathcal{B}$ of Borel sets. Each interval, each open set, each closed set, and each clopen set is measurable.

- The translate of a measurable set is measurable.

- If $A$ is a measurable set of finite outer measure that is contained in $B$, then
$$m^*(B/A) = m^*(B) - m^*(A)$$ and $$m^*(B) = m^*(A) + m^*(B/A)$$ 

- The restriction of the set function outer measure to the class of measurable sets is called **Lebesgue Measure**. It is denoted by $m$, so that if $E$ is a measurable set, its Lebesgue measure will be $m(E)$, defined by
$$m(E) = m^*(E)$$

- The Lebesgue measure defined on the $\sigma$-algebra of Lebesgue measurable sets assigns length to any interval, is translation invariant, and is countably additive.

- **The Continuity of Measure**: Lebesgue measure possesses the following continuity properties:

(a) If $\{A_k\}^{\infty}_{k=1}$ is an ascending collection of measurable sets, then,
$$m \left( \bigcup_{k=1}^{\infty}A_k \right) = \lim_{k\to\infty} m(A_k)$$

(b) If $\{B_k\}^{\infty}_{k=1}$ is a descending collection of measurable sets and $m(B_1) < \infty$, then $$m \left( \bigcap_{k=1}^{\infty}B_k \right) = \lim_{k\to\infty} m(B_k)$$

- For a measurable set $E$, we say that a property holds **almost everywhere** on $E$, or it holds for almost all $x \in E$, provided there is a subset $E_0$ of $E$ for which $m(E_0) = 0$ and the property holds for all $x \in E$ ~ $E_0$.

- Let $\{E_k\}^{\infty}_{k=1}$ be a countable collection of measurable sets for which $\sum_{k=1}^{\infty} m(E_k) < \infty$. Then almost all $x \in \mathbb{R}$ belong to at most finitely many of the $E_k$'s.

- Let $E$ be a bounded measurable set of real numbers. Suppose there is a bounded, countably infinite set of real numbers $\Lambda$ for which the collection of translates of $E$, $\{\lambda + E\}_{\lambda \in \Lambda}$, is disjoint. Then $m(E) = 0$

- Any set $E$ of real numbers with positive outer measure contains a subset that fails to be measurable.

- There are disjoint sets of real numbers $A$ and $B$ for which
$$m^*(A \cup B) < m^* (A) + m^*(B)$$

- The Cantor set $C$ is a closed, uncountable set of measure zero

- The Cantor-Lebesgue function $\phi$ is an increasing continuous function that maps $[0,1]$ onto $[0,1]$. Its derivative exists on the open set $\mathcal{O}$, the complement in $[0,1]$ of the Cantor set $\phi '=0$ on $\mathcal{O}$ while $m(\mathcal{O}) = 1$

- There is a measurable set, a subset of the Cantor set, that is not a Borel set.

### Royden Chapter 3 (Lebesgue Measurable Functions)

- Let the function $f$ have a measurable domain $E$. Then the following statements are equivalent:

(i) For all $c \in \mathbb{R}$, the set $\{x \in E|f(x)  > c\}$ is measurable

(ii) For all $c \in \mathbb{R}$, the set $\{x \in E|f(x)  \geq c\}$ is measurable

(iii) For all $c \in \mathbb{R}$, the set $\{x \in E|f(x)  < c\}$ is measurable

(iv) For all $c \in \mathbb{R}$, the set $\{x \in E|f(x)  \leq c\}$ is measurable

- An extended real-valued function $f$ defined on $E$ is said to be **Lebesgue measurable**, or simply **measurable**, provided its domain $E$ is measurable and it satisfies one of the four above statements.

- Let the function $f$ be defined on a measurable set $E$. Then $f$ is measurable iff for all open sets $\mathcal{O}$, the inverse image of $\mathcal{O}$ under $f$, $f^{-1}(\mathcal{O}) = \{x \in E| f(x) \in \mathcal{O}\}$, is measurable

- A real valued function that is continuous on its measurable domain is measurable

- A monotone function that is defined on an interval is measurable

- Let $f$ be an extended real-valued function $E$. Then if $f$ is measurable on $E$ and $f=g$ a.e. on $E$, then $g$ is measurable on $E$. For a measurable subset $D$ of $E$, $f$ is measurable on $E$ iff the restrictions of $f$ to $D$ and $E$~$D$ are measurable.

- Let $f$ and $g$ be measurable functions on $E$ that are finite a.e. on $E$. For any $\alpha$ and $\beta$, $\alpha f + \beta g$ is measurable on $E$ and $fg$ is measurable on $E$.

- Let $g$ be a measurable real-valued function defined on $E$ and $f$ a continuous real-valued function on all of $\mathbb{R}$. Then the composition $f \circ g$ is a measurable function on $E$

- For a sequence $\{f_n\}$ of functions with common domain $E$, a function $f$ on $E$ and a subset $A$ of $E$, we say that the sequence $\{f_n\}$ converges to $f$ pointwise on $A$ provided $\lim_{n \to \infty} f_n(x) = f(x)$ for all $x \in A$; and the sequence $\{f_n\}$ converges to $f$ pointwise a.e. on $A$ provided it converges to $f$ pointwise on $A$~$B$ where $m(B) =0$; and the sequence $\{f_n\}$ converges to $f$ uniformly on $A$ provided for each $\epsilon >0$, there is an index $N$ for which $|f-f_n| < \epsilon$ on $A$ for all $n \geq N$.

- Let $\{f_n\}$ be a sequence of measurable functions on $E$ that converges pointwise a.e. on $E$ to the function $f$. Then $f$ is measurable.

- If $A$ is any set, the **characteristic function** of $A$, $\chi_A$, is the function on $\mathbb{R}$ defined by 
$$\chi_A = \{1|x \in A \& 0 |x \notin A \}$$

- A real-valued function $\phi$ defined on a measurable set $E$ is called **simple** provided it is measurable and takes only a finite number of values

- Let $f$ be a measurable real-valued function on $E$. Assume $f$ is bounded on $E$, that is there exists an $M \geq 0$ for which $|f| \leq M$ on $E$. Then for all $\epsilon > 0$, there are simple functions $\phi_{\epsilon}$ and $\psi_{\epsilon}$ defined on $E$ which have the following approximation properties on $E$:
$$\phi_{\epsilon} \leq f \leq \psi_{\epsilon}; 0 \leq \psi_{\epsilon} - \phi_{\epsilon} < \epsilon$$

- An extended real-valued function $f$ on a measurable set $E$ is measurable iff there is a sequence $\{\phi_n\}$ of simple functions on $E$ which converges pointwise on $E$ to $f$ and has the property that $|\phi_n| \leq |f|$ on $E$ for all $n$. If $f$ is nonnegative, we may choose $\{\phi_n\}$ to be increasing

- **Egoroff's Theorem**: Assume $E$ has finite measure. Let $\{f_n\}$ be a sequence of measurable functions on $E$ that converges pointiwse on $E$ to the real-valued function $f$. THen for all $\epsilon > 0$, there is a closed set $F$ contained in $E$ for which $\{f_n\} \rightarrow f$ uniformly on $F$ and $m(E$~$F) < \epsilon$

- Under the assumptions of Egoroff's Thm, for all $\nu > 0$ and $\delta > 0$, there is a measurable subset $A$ of $E$ and an index $N$ for which $|f_n - f| < \nu$ on $A$ for all $n \geq N$ and $m(E$~$A) < \delta$.

- Let $f$ be a simple function defined on $E$. Then for each $\epsilon > 0$, there is a continuous function $g$ on $\mathbb{R}$ and a closed set $F$ contained in $E$ for which $f=g$ on $F$ and $m(E$~$F) < \epsilon$

- Let $f$ be a real-valued measurable function on $E$. Then for all $\epsilon > 0$, there is a continuous function $g$ on $\mathbb{R}$ amd a closed set $F$ contained in $E$ for which $f=g$ on $F$ and $m(E$~$F) < \epsilon$

### Royden Chapter 4 (Integration)

- The **upper and lower sums** for $f$ with respect to a partition $P$ are
$$L(f,P) = \sum_{i=1}^{n}m_i \times (x_i-x_{i-1})$$
$$U(f,P) = \sum_{i=1}^{n}M_i \times (x_i-x_{i-1})$$
where $m_i$ is the infimum on the given partition, and $M_i$ is the supremum

- The **lower and upper Riemann integrals** of $f$ over $[a,b]$ are defined by (respectively)
$$\int_a^b f = \mathrm{sup}\{L(f,P)\}$$
$$\int_a^b f = \mathrm{inf}\{U(f,P)\}$$
where $P$ is a partition of $[a,b]$.

- If the two above mentioned integrals are equal, then we say that $f$ is **Riemann integrable** over $[a,b]^2$.

- For a simple function $\psi$ defined on a set og finite measure $E$, we define the integral of $\psi$ over $E$ by
$$\int_E \psi = \sum_{i=1}^n a_i \times m(E_i)$$
where $\psi = \sum_{i=1}^n a_i \times \chi_{E_i}$ and each $E_i = \{x \in E| \psi(x) = a_i\}$

- Let $\{E_i\}_{i=1}^n$ be a finite disjoint collection of measurable subsets of a set of finite meausre $E$. For $1 \leq i \leq n$, let $a_i$ be a real number. If $\phi = \sum_{i=1}^n a_i \times \chi_{E_i}$ on $E$, then 
$$\int_E \phi = \sum_{i=1}^n a_i \times m(E_i)$$

- **Linearity and Monotonicity of Integration**: Let $\phi$ and $\psi$ be simple functions defined on a set of finite measure $E$. Then for any $\alpha$ and $\beta$,
$$\int_E (\alpha \phi + \beta \psi) = \alpha \int_E \phi + \beta \int_E \psi$$
Moreover, if $\phi \leq \psi$ on $E$, then
$$\int_E \phi \leq \int_E \psi$$

- A bounded function $f$ ona domain $E$ of finite measure is said to be **Lebesgue integrable** over $E$ provided its upper and lower Lebesgue integrals over $E$ are equal. The common value of the upper and lower integrals is called the **Lebesgue integral**.

- Let $f$ be a bounded function defined on the closed, bounded interval $[a,b]$. If $f$ is Riemann integrable over $[a,b]$, then it is Lebesgue integrable over $[a,b]$ and the two integrals are equal.

- Let $f$ be a bounded measurable function on a set of finite meausre $E$. Then $f$ is integrable over $E$.

- Let $f$ and $g$ be bounded measurable functions on a set of finite measure $E$. Then for any $\alpha$ and $\beta$,
$$\int_E (\alpha f + \beta g) = \alpha \int_E f + \beta \int_E g$$
Moreover, if $f \leq g$ on $E$, then
$$\int_E f \leq \int_E g$$

- Let $f$ be a bounded measurable function on a set of finite measure $E$. Suppose $A$ and $B$ are disjoint meausrable subsets of $E$. Then
$$\int_{A \cup B} f = \int_A f + \int_B f$$

- Let $f$ be a bounded measurable function on a set of finite measure $E$. Then,
$$\left| \int_E f \right| \leq \int_E |f|$$

- Let $\{f_n\}$ be a sequence of bounded measurable functions on a set of finite measure $E$. If $\{f_n\} \rightarrow f$ uniformly on $E$, then $\lim_{n \to \infty} \int_E f_n = \int_E f$

- **The Bounded Convergence Theorem**: Let $\{f_n\}$ be a sequence of measurable functions on a set of finite measure $E$. Suppose $\{f_n\}$ is uniformly pointwise bounded on $E$, that is, there exists a number $M \geq 0$ for which $|f_n| \leq M$ on $E$ for all $n$. If $\{f_n\} \rightarrow f$ pointwise on $E$, then $\lim_{n \to \infty} \int_E f_n = \int_E f$

- **Chebychev's Inequality**: Let $f$ be a nonnegative measurable function on $E$. Then for any $\lambda > 0$, 
$$m(\{x \in E| f(x) \geq \lambda\}) \leq \frac{1}{\lambda} \int_E f$$

- Let $f$ be a nonnegative measurable function on $E$. Then $\int_E f = 0$ iff $f=0$ a.e. on $E$.

- **Linearity and Monotonicity** follow for nonnegative measurable functions.

- **Fatou's Lemma**: Let $\{f_n\}$ be a sequence of nonnegative measurable functions on $E$. If $\{f_n\} \rightarrow f$ pointwise a.e. on $E$, then $\int_E f \leq \mathrm{liminf} \int_E f_n$

- **Monotone Convergence Theorem**: Let $\{f_n\}$ be an increasing sequence of nonnegative measurable functions on $E$. If $\{f_n\} \rightarrow f$ pointwise a.e. on $E$, then 
$$\lim_{n \to \infty} \int_E f_n = \int_E f$$

- A nonnegative measurable function $f$ on a measurable set $E$ is said to be **integrable** over $E$ provided $\int_E f < \infty$

- Let the nonnegative function $f$ be integrable over $E$. Then $f$ is finite a.e. on $E$.

- Let $f$ be a measurable function on $E$. Then $f^+$ and $f^-$ are integrable over $E$ iff $|f|$ is integrable over $E$.

- A measurable function $f$ on $E$ is said to be **integrable** over $E$ provided $\int_E |f| < \infty$. When this is so, we define the integral by 
$$\int_E f = \int_E f^+ - \int_E f^-$$

- Let $f$ be integrable over $E$. THen $f$ is finite a.e. on $E$ and $\int_E f = \int_{E/E_0} f$ if $E_0 \subseteq E$ such that $m(E_0) = 0$.

- **The Integral Comparison Test**: Let $f$ be a measurable function on $E$. Suppose there is a nonnegative function $g$ that is integrable over $E$ and dominates $f$ in the sense that $|f| \leq g$ on $E$. Then $f$ is integrable over $E$ and
$$\left| \int_E f \right| \leq \int_E |f|$$

- If $f$ and $g$ are integrable functions on $E$, then **linearity** and **monotonicity** follow.

- Let $f$ be integrable over $E$. Assume $A$ and $B$ are disjoint measurable subsets of $E$. Then 
$$\int_{A \cup B} f = \int_A f + \int_B f$$

- **Dominated Convergence Theorem**: Let $\{f_n\}$ be a sequence of measurable functions on $E$. Suppose there is an integrable function $g$ on $E$ and dominates $\{f_n\}$ on $E$ in the sense that $|f_n| \leq g$ on $E$ for all $n$. If $\{f_n\} \rightarrow f$ pointwise a.e. on $E$, then $f$ is integrable over $E$ and $\lim_{n \to \infty} \int_E f_n = \int_E f$.

- **General Dominated Convergence Theorem**: Let $\{f_n\}$ be a sequence of measurable functions on $E$ that converges pointwise a.e. on $E$ to $f$. Suppose there is a sequence $\{g_n\}$ of nonnegative measurable functions on $E$ that converges pointwise a.e. on $E$ to $g$ and dominates $\{f_n\}$ on $E$ in the sense that $|f_n| \leq g_n$ on $E$ for all $n$. If
$$\lim_{n \to \infty} \int_E g_n = \int_E g < \infty$$
then,
$$\lim_{n \to \infty} \int_E f_n = \int_E f$$

- Let $E$ be a set of finite measure and $\delta > 0$. Then $E$ is the disjoint union of a finite collection of sets, each of which has measure less than $\delta$.

- A family $\mathcal{F}$ of measuable functions on $E$ is said to be **uniformly integrable** over $E$ provided for each $\epsilon > 0$, there is a $\delta > 0$ such that for each $f \in \mathcal{F}$, if $A \subseteq E$ is measurable and $m(A) < \delta$, then $\int_A |f| < \epsilon$.

- Let $\{f_n\}_{k=1} ^n$ be a finite collection of functions, each of which is integrable over $E$. Then $\{f_n\}_{k=1} ^n$ is uniformly integrable.

- **Vitali COnvergence Theorem**: Let $E$ be of finite measure. Suppose the sequence of functions $\{f_n\}$ is uniformly integrable over $E$. If $\{f_n\} \rightarrow f$ a.e. on $E$, then $f$ is integrable over $E$ and 
$$\lim_{n \to \infty} \int_E f_n = \int_E f$$

- Let $f$ be a bounded function on a set of finite measure $E$. Then $f$ is Lebesgue integrable over $E$ iff it is measurable.

- Let $f$ be a bounded function on the closed, bounded interval of $[a,b]$. THen $f$ is Riemann integrable over $[a,b]$ iff the set of points in $[a,b]$ at which $f$ fails to be continuous has measure zero.

### Royden Chapter 6 (Differentiation)

- Let $f$ be a monotone function on the open interval $(a,b)$. Then $f$ is continuous except possibly at a countable number of points in $(a,b)$.

- If the function $f$ is monotone on the open interval $(a,b)$, then it is differentiable almost everywhere on $(a,b)$

- Define the **variation** of $f$ with respect to $P$ (a partition) by $V(f,P) = \sum_{i=1}^k |f(x_i) - f(x_{i-1})|$, and the **total variation** of $f$ on $[a,b]$ by $TV(f) = \mathrm{sup} \{V(f,P)\}$ where $P$ is a partition on $[a,b]$

- A real valued function $f$ on the closed and bounded interval $[a,b]$ is said to be of **bounded variation** on $[a,b]$ provided $TV(f) < \infty$

- **Jordan's Thm**: A function $f$ is of bounded variation on the closed, bounded interval $[a,b]$ iff it is the difference of two increasing functions on $[a,b]$

- If the function $f$ is of bounded variation on the closed and bounded interval $[a,b]$ then it is differentiable almost everywhere on the open interval $(a,b)$ and $f'$ is integrable over $[a,b]$

- A real valued function $f$ on a closed and bounded interval $[a,b]$ is said to be **absolutely continuous** on $[a,b]$ provided for each $\epsilon > 0$ there is a $\delta > 0$ such that for every finite disjoint collection $\{(a_k,b_k)\}_{k=1}^n$ of open intervals in $(a,b)$, if $\sum_{k=1}^n [b_k - a_k] < \delta$, then 
$$\sum_{k=1}^n |f(b_k) - f(a_k)| < \epsilon$$

- If the function $f$ is Lipschitz on a closed, bounded interval $[a,b]$, then it is absolutely continuous on $[a,b]$

- Let the function $f$ be absolutely continuous on the closed, bounded interval $[a,b]$. Then $f$ is the difference of increasing absolutely continuous functions and, in particular, is of bounded variation

- Let the function $f$ be absolutely continuous on the closed, bounded interval $[a,b]$. Then $f$ is differentiable almost everywhere on $(a,b)$, its derivative $f'$ is integrable over $[a,b]$ and
$$\int_b ^a f' = f(b) - f(a)$$

- We call a function $f$ on a closed, bounded interval $[a,b]$ the **indefinite integral** of $g$ over $[a,b]$ provided that $g$ is Lebesgue integrable over $[a,b]$ and for all $x \in [a,b]$
$$f(x) = f(a) + \int_a ^x g$$

- A function $f$ on a closed, bounded interval $[a,b]$ is absolutely continuous on $[a,b]$ iff it is an indefinite integral over $[a,b]$

- Let the function $f$ be monotone on the closed, bounded interval $[a,b]$. Then $f$ is absolutely continuous on $[a,b]$ iff $\int_a ^b f' = f(b) - f(a)$

- Let $f$ be integrable over the closed, bounded interval $[a,b]$. Then $f(x) = 0$ for almost all $x \in [a,b]$ iff $\int_{x_1} ^{x_2} f = 0$ for all $(x_1, x_2) \subseteq [a,b]$

- Let $f$ be integrable over the closed, bounded interval $[a,b]$. Then for almost all $x \in (a,b)$
$$\frac{d}{dx} \left[ \int_a ^x f \right] = f(x)$$

### Royden Chapter 7 ($L^p$ Spaces)

- For most of this section, unless otherwise stated, define $E$ to be a measurable set of real numbers, and $\mathcal{F}$ to be the collection of all measurable extended real-valued functions on $E$ that are finite a.e. on $E$. Define $f$ and $g \in \mathcal{F}$ to be equivalent and $f \cong g$ iff $f(x) = g(x)$ for almost all $x \in E$.

- We call a function $f \in \mathcal{F}$ **essentially bounded** provided there is some $M \geq 0$ called an **essential upper bound** for $f$ for which $|f(x)| \leq M$ for almost all $x \in E$

- **functionals** are real-valued functions that have as their domain linear spaces of functions

- Let $X$ be a linear space. A real-valued functional $|| \cdot ||$ on $X$ is called a **norm** provided for each $f$ and $g$ in $X$, and each real number $c$, $||f|| \geq 0$ and $||f|| = 0$ iff $f =0$,
$$||f+g|| \leq ||f||+||g||$$
$$||cf|| = |c|||f||$$

- By a **normed linear space** we mean a linear space together with a norm. If $X$ is a linear space normed by $|| \cdot ||$ we say that a function in $X$ is a **unit function** provided $||f|| = 1$

- For any $f \in X$, $f \neq 0$, the function $\frac{f}{||f||}$ is a unit function: it is a scalar multiple of $f$ which we call the **normalization** of $f$

- **The Normed Linear Space $L^1(E)$**
$$||f||_1 = \int_E |f|$$

- **The Normed Linear Space $L^{\infty}(E)$**: For a function $f \in L^{\infty}(E)$, define $||f||_{\infty}$ to be the infimum of the essential upper bounds for $f$. We call $||f||_{\infty}$ the **essential supremum** of $f$ and claim that $|| \cdot ||$ is a norm on $L^{\infty}(E)$

- $||f||_{\mathrm{max}} = \mathrm{max}_{x \in [a,b]} |f(x)|$ is a norm and is called the **maximum norm**

- For a measurable set $E$ where $1<p< \infty$ and a function $f$ in $L^p(E)$, define 
$$||f||_p = \left[ \int_E |f|^p \right]^{1/p}$$

- The conjugate of a number $p \in (1, \infty)$ is the number $q = \frac{p}{p-1}$, which is the unique number $q \in (1, \infty)$ for which 
$$\frac{1}{p} + \frac{1}{q} = 1$$
Note, the conjugate of $1$ is defined to be $\infty$ and vice versa.

- **Young's Inequality**: For $1<p< \infty$, $q$ is the conjugate of $p$ and any two positive numbers $a$ and $b$,
$$ab \leq \frac{a^p}{p}+\frac{b^q}{q}$$

- Let $E$ be a measurable set $1 \leq p < \infty$, and $q$ be the conjugate of $p$. If $f$ belongs to $L^p(E)$ and $g$ belongs to $L^q(E)$, then their product $f \cdot g$ is integrable over $E$ and 
$$\int_E |f \cdot g| \leq ||f||_p \cdot ||g||_q$$
This is known as **Holder's Inequality**. 

- Let $E$ be a measurable set and $1 \leq p < \infty$. If the functions $f$ and $g$ belong to $L^p(E)$, then so does their sum $f+g$ and moreover,
$$||f+g||_p \leq ||f||_p + ||g||_p$$

- **Cauchy-Schwarz Inequality**: Let $E$ be a maeasurable set and $f$ and $g$ measurable functions on $E$ for which $f^2$ and $g^2$ are integrable over $E$. Then their product $f \cdot g$ is also integrable over $E$ and 
$$\int_E |fg| \leq \sqrt{\int_E f^2} \cdot \sqrt{\int_E g^2}$$

- Let $E$ be a measurable set and $1 < p < \infty$. Suppose $\mathcal{F}$ is a family of functions in $L^p(E)$ that is bounded in $L^p(E)$ in the sense that there is a constant $M$ for which $||f||_p \leq M$ for all $f$ in $\mathcal{F}$. Then the family $\mathcal{F}$ is uniformly integrable over $E$.

- Let $E$ be a measurable set of finite measure and $1 \leq p_1 < p_2 \leq \infty$. Then $L^{p_2}(E) \subseteq L^{p_1}(E)$. Furthermore $||f||_{p_1} \leq c||f||_{p_2}$ for all $f$ in $L^{p_2}(E)$ where $c = [m(E)]^{\frac{p_2 - p_1}{p_1p_2}}$ if $p_2 < \infty$ and $c = [m(E)]^{\frac{1}{p_1}}$ if $p_2 = \infty$

- A sequence $\{f_n\}$ in a linear space $X$ that is normed by $|| \cdot ||$ is said to **converge to $f$ in $X$** provided $\lim_{n \to \infty} ||f - f_n|| = 0$. This can also be written as $\{f_n\} \to f$ in $X$ or $\lim_{n \to \infty} f_n = f$ in $X$. 

- A sequence $\{f_n\}$ in a linear space $X$ that is normed by $|| \cdot ||$ is said to be **Cauchy** in $X$ provided for each $\epsilon > 0$, there is a natural number $N$ such that $||f_n - f_m|| < \epsilon$ for all $m,n \geq N$. 

- A normed linear space $X$ is said to be **complete** provided every Cauchy sequence in $X$ converges to a function in $X$. A complete normed linear space is called a **Banach space**

- Let $X$ be a normed linear space. Then every convergent sequence in $X$ is Cauchy. Moreover, a Cauchy sequence in $X$ converges if it has a convergent subsequence.

- Let $X$ be a linear space normed by $|| \cdot ||$. A sequence $\{f_n\}$ in $X$ is said to be **rapidly Cauchy** provided there is a convergent series of positive numbers $\sum_{k=1}^{\infty} \epsilon_k$ for which $||f_{k+1} - f_k|| \leq \epsilon_k ^2$ for all $k$

- Let $X$ be a normed linear space. Then every rapidly Cauchy sequence in $X$ is Cauchy. Furthermore, every Cauchy sequence has a rapidly Cauchy subsequence.

- Let $E$ be a measurable set and $1 \leq p \leq \infty$. Then every rapidly Cauchy sequence in $L^p(E)$ converges both wrt the $L^p(E)$ norm and pointwise a.e. on $E$ to a function in $L^p(E)$.

- Let $E$ be a measurable set and $1 \leq p \leq \infty$. Then $L^p(E)$ is a Banach space. Moreover, if $\{f_n\} \rightarrow f$ in $L^p(E)$, a subsequence of $\{f_n\}$ converges pointwise a.e. on $E$ to $f$

- Let $E$ be a measurable set and $1 \leq p < \infty$. Suppose $\{f_n\}$ is a sequence in $L^p(E)$ that converges pointwise a.e. on $E$ to the function $f$ which belongs to $L^p(E)$. Then $\{f_n\} \rightarrow f$ in $L^p(E)$ iff $\lim_{n \to \infty} \int_E |f_n|^p = \int_E |f|^p$

- Let $E$ be a measurable set and $1 \leq p < \infty$. Suppose $\{f_n\}$ is a sequence in $L^p(E)$ that converges pointwise a.e. on $E$ to the function $f$ which belongs to $L^p(E)$. Then $\{f_n\} \to f$ in $L^p(E)$ iff $\{|f|^p\}$ is uniformly integrable and tight over $E$.

- Let $X$ be a normed linear space with norm $|| \cdot ||$. Given two subsets $\mathcal{F}$ and $\mathcal{G}$ of $X$ with $\mathcal{F} \subseteq \mathcal{G}$, we say that $\mathcal{F}$ is **dense** in $\mathcal{G}$, provided for each function $g \in \mathcal{G}$ and $\epsilon > 0$, there is a function $f \in \mathcal{F}$ for which $||f-g|| < \epsilon$

- Let $E$ be a measurable set and $1 \leq p \leq \infty$. Then the subspace of simple functions in $L^p(E)$ is dense in $L^p(E)$

- Let $[a,b]$ be a closed, bounded interval and $1 \leq p < \infty$. Then the subspace of step functions on $[a,b]$ is dense in $L^p[a,b]$

- A normed linear space $X$ is said to be **separable** provided there is a countable subset that is dense in $X$.

- Let $E$ be a measurable set and $1 \leq p < \infty$. Then the normed linear space $L^p(E)$ is separable.


### Royden Chapter 8 ($L^p$ Spaces Continued)

- A **linear functional** on a linear space $X$ is a real-valued function $T$ on $X$ suxh that for $g$ and $h$ in $X$ and $\alpha$ and $\beta$ real numbers,
$$T(\alpha \cdot g + \beta \cdot h) = \alpha \cdot T(g) + \beta \cdot T(h)$$

- For a normed linear space $X$, a linear functional $T$ on $X$ is said to be **bounded** provided there is an $M \geq 0$ for which $|T(f)| \leq M \cdot ||f||$ for all $f \in X$. The infimum of all such $M$ is called the **norm** of $T$ and denoted by $||T||_*$

- Let $X$ be a normed linear space. Then the collection of bounded linear functionals on $X$ is a linear space on which $|| \cdot ||_*$ is a norm. This normed linear space is called the **dual space** of $X$ and denoted by $X^*$

- Let $E$ be a measurable set, $1 \leq p < \infty$, $q$ be the conjugate of $p$, and $g$ belong to $L^q(E)$. Define the functional $T$ on $L^p(E)$ by $T(f) = \int_E g \cdot f$ for all $f \in L^p(E)$. Then $T$ is a bounded linear functional on $L^p(E)$ and $||T||_* = ||g||_q$

- Let $T$ and $S$ be bounded linear functionals on a normed linear space $X$. If $T=S$ on a dense subset $X_0$ of $X$, then $T = S$

- Let $I = [a,b]$ be a closed, bounded interval and $1 \leq p < \infty$. Suppose $T$ us a bounded linear functional on $L^p[a,b]$. Then there is a function $g$ in $L^q[a,b]$, where $q$ is the conjugate of $p$ for which $T(f) = \int_I g \cdot f$ for all $f \in L^p[a,b]$

- Let $E$ be a measurable set, $1 \leq p < \infty$ and $q$ the conjugate of $p$. For each $g \in L^q(E)$, define the bounded linear functional $\mathcal{R}_g$ on $L^p(E)$ by $\mathcal{R}_g(f) = \int_E g \cdot f$ for all $f$ in $L^p(E)$. Then for each bounded linear functional $T$ on $L^p(E)$, there is a unique function $g \in L^q(E)$ for which $\mathcal{R}_g = T$ and $||T||_* = ||g||_q$

- Let $X$ be a normed linear space. A sequence $\{f_n\}$ in $X$ is said to **converge weakly** in $X$ to $f$ in $X$ provided $\lim_{n \to \infty} T(f_n) = T(f)$ for all $T \in X^*$

- Let $E$ be a measurable set, $1 \leq p < \infty$, and $q$ the conjugate of $p$. Then $\{f_n\}$ converges weakly in $X$ to $f$ in $L^p(E)$ iff $\lim_{n \to \infty} \int_E g \cdot f_n = \int_E g \cdot f$ for all $g \in L^q(E)$

- Let $E$ be a measurable set and $1 \leq p < \infty$. Suppose $\{f_n\}$ converges weakly in $L^p(E)$ to $f$. Then $\{f_n\}$ is bounded in $L^p(E)$ and $||f||_p \leq \mathrm{liminf}||f_n||_p$

- Let $E$ be a measurable set, $1 \leq p < \infty$, and $q$ the conjugate of $p$. Suppose $\{f_n\}$ converges weakly to $f$ in $L^p(E)$ and $\{g_n\}$ converges strongly to $g$ in $L^q(E)$. Then $\lim_{n \to \infty} \int_E g_n \cdot f_n = \int_E g \cdot f$

- The **linear span** of a subset $\mathcal{S}$ of a linear space $X$ is the linear space consisting of all linear combinations of functions in $\mathcal{S}$, that is, the linear space of functions of the form $f = \sum^n _{k=1} \alpha_k \cdot f_k$ where each $\alpha_k$ is a real number and each $f_k$ belongs to $\mathcal{S}$

- Let $E$ be a measurable set and $1 \leq p < \infty$. Suppose $\{f_n\}$ is a bounded sequence in $L^p(E)$ and $f$ belongs to $L^p(E)$. Then $\{f_n\}$ converges weakly to $f$ in $L^p(E)$ iff for every measurable subset $A$ of $E$, $\lim_{n \to \infty} \int_A f_n = \int_A f$. If $p > 1$, it is sufficient to consider sets $A$ of finite measure.

- Let $[a,b]$ be a closed and bounded interval and $1 < p < \infty$. Suppose $\{f_n\}$ is a bounded sequence in $L^p[a,b]$ and $f$ belongs to $L^p[a,b]$. Then $\{f_n\}$ converges weakly to $f$ in $L^p[a,b]$ iff 
$$\lim_{n \to \infty} \left[ \int_a ^x f_n\right] = \int^x _a f$$
for all $x \in [a,b]$. This theorem is false for $p =1$

- Let $E$ be a measurable set and $1 < p < \infty$. Suppose $\{f_n\}$ converges weakly to $f$ in $L^p(E)$. Then $\{f_n\} \to f$ in $L^p(E)$ iff $\lim_{n \to \infty} ||f_n||_p = ||f||_p$

- Let $E$ be a measurable set and $1 < p < \infty$. Suppose $\{f_n\}$ converges weakly $f$ in $L^p(E)$. Then a subsequence of $\{f_n\}$ converges strongly in $L^p(E)$ to $f$ iff $||f||_p = \mathrm{liminf}||f_n||_p$

- Let $E$ be a measurable set and $1 < p < \infty$. Then every bounded sequence in $L^p(E)$ has a subsequence that converges weakly in $L^p(E)$ to a function in $L^p(E)$







